/// Datos de ubicación jerárquica: País → Departamento/Estado → Ciudad/Municipio
/// Para selección de ubicación en formularios
library;

import '../../../../core/errors/error_messages.dart';

/// Clase con datos estáticos de ubicaciones
class LocationData {
  LocationData._();

  /// Lista de países disponibles
  static const List<String> countries = [
    'Perú',
    'Venezuela',
    'Ecuador',
    'Colombia',
    'Argentina',
    'Bolivia',
  ];

  /// Obtener regiones/departamentos para un país
  static List<String> getRegionsForCountry(String country) {
    switch (country) {
      case 'Perú':
        return _peruDepartamentos;
      case 'Venezuela':
        return _venezuelaEstados;
      case 'Ecuador':
        return _ecuadorProvincias;
      case 'Colombia':
        return _colombiaDepartamentos;
      case 'Argentina':
        return _argentinaProvincias;
      case 'Bolivia':
        return _boliviaDepartamentos;
      default:
        return [];
    }
  }

  /// Obtener ciudades/provincias para una región de un país específico
  static List<String> getCitiesForRegion(String region, [String? country]) {
    if (country != null) {
      switch (country) {
        case 'Perú':
          return _peruProvincias[region] ?? [];
        case 'Venezuela':
          return _venezuelaMunicipios[region] ?? [];
        case 'Ecuador':
          return _ecuadorCantones[region] ?? [];
        case 'Colombia':
          return _colombiaMunicipios[region] ?? [];
        case 'Argentina':
          return _argentinaCiudades[region] ?? [];
        case 'Bolivia':
          return _boliviaCiudades[region] ?? [];
        default:
          return [];
      }
    }
    // Fallback sin país (compatibilidad)
    return _peruProvincias[region] ??
        _venezuelaMunicipios[region] ??
        _ecuadorCantones[region] ??
        _colombiaMunicipios[region] ??
        _argentinaCiudades[region] ??
        _boliviaCiudades[region] ??
        [];
  }

  /// Etiqueta para la segunda jerarquía (Departamento/Estado)
  static String getRegionLabel(String country) {
    switch (country) {
      case 'Venezuela':
        return 'Estado';
      case 'Ecuador':
      case 'Argentina':
        return 'Provincia';
      default: // Perú, Colombia, Bolivia
        return 'Departamento';
    }
  }

  /// Etiqueta para la tercera jerarquía (Ciudad/Municipio)
  static String getCityLabel(String country) {
    switch (country) {
      case 'Venezuela':
      case 'Colombia':
        return 'Municipio';
      case 'Ecuador':
        return 'Cantón';
      case 'Argentina':
        return 'Ciudad / Partido';
      case 'Bolivia':
        return 'Ciudad / Municipio';
      default:
        return 'Ciudad / Provincia';
    }
  }

  /// Prefijo telefónico del país
  static String getPhonePrefix(String country) {
    switch (country) {
      case 'Venezuela':
        return '+58';
      case 'Ecuador':
        return '+593';
      case 'Colombia':
        return '+57';
      case 'Argentina':
        return '+54';
      case 'Bolivia':
        return '+591';
      default:
        return '+51';
    }
  }

  /// Longitud esperada del teléfono (sin prefijo)
  static int getPhoneLength(String country) {
    switch (country) {
      case 'Venezuela':
      case 'Colombia':
      case 'Argentina':
        return 10;
      case 'Bolivia':
        return 8;
      default:
        return 9;
    }
  }

  /// Etiqueta del documento fiscal
  static String getFiscalDocLabel(String country) {
    switch (country) {
      case 'Venezuela':
        return 'RIF';
      case 'Colombia':
        return 'NIT';
      case 'Argentina':
        return 'CUIT';
      case 'Bolivia':
        return 'NIT';
      default:
        return 'RUC';
    }
  }

  /// Validar si el inicio del número telefónico es correcto
  static bool isValidPhoneStart(String country, String phone) {
    if (phone.isEmpty) return false;
    switch (country) {
      case 'Venezuela':
        return phone.startsWith('4') || phone.startsWith('2');
      case 'Colombia':
        return phone.startsWith('3');
      case 'Argentina':
        return phone.startsWith('1') ||
            phone.startsWith('2') ||
            phone.startsWith('3');
      case 'Bolivia':
        return phone.startsWith('6') || phone.startsWith('7');
      default: // Perú, Ecuador
        return phone.startsWith('9');
    }
  }

  /// Mensaje de error para inicio de teléfono inválido
  static String getPhoneStartError(String country) {
    switch (country) {
      case 'Venezuela':
        return ErrorMessages.get('PHONE_START_VENEZUELA');
      case 'Colombia':
        return ErrorMessages.get('PHONE_START_COLOMBIA');
      case 'Argentina':
        return ErrorMessages.get('PHONE_START_ARGENTINA');
      case 'Bolivia':
        return ErrorMessages.get('PHONE_START_BOLIVIA');
      default: // Perú, Ecuador
        return ErrorMessages.get('PHONE_START_DEFAULT');
    }
  }

  /// Departamentos del Perú
  static const List<String> _peruDepartamentos = [
    'Amazonas',
    'Áncash',
    'Apurímac',
    'Arequipa',
    'Ayacucho',
    'Cajamarca',
    'Callao',
    'Cusco',
    'Huancavelica',
    'Huánuco',
    'Ica',
    'Junín',
    'La Libertad',
    'Lambayeque',
    'Lima',
    'Loreto',
    'Madre de Dios',
    'Moquegua',
    'Pasco',
    'Piura',
    'Puno',
    'San Martín',
    'Tacna',
    'Tumbes',
    'Ucayali',
  ];

  /// Provincias por departamento
  static const Map<String, List<String>> _peruProvincias = {
    'Amazonas': [
      'Chachapoyas',
      'Bagua',
      'Bongará',
      'Condorcanqui',
      'Luya',
      'Rodríguez de Mendoza',
      'Utcubamba',
    ],
    'Áncash': [
      'Huaraz',
      'Aija',
      'Antonio Raymondi',
      'Asunción',
      'Bolognesi',
      'Carhuaz',
      'Carlos Fermín Fitzcarrald',
      'Casma',
      'Corongo',
      'Huari',
      'Huarmey',
      'Huaylas',
      'Mariscal Luzuriaga',
      'Ocros',
      'Pallasca',
      'Pomabamba',
      'Recuay',
      'Santa',
      'Sihuas',
      'Yungay',
    ],
    'Apurímac': [
      'Abancay',
      'Andahuaylas',
      'Antabamba',
      'Aymaraes',
      'Cotabambas',
      'Chincheros',
      'Grau',
    ],
    'Arequipa': [
      'Arequipa',
      'Camaná',
      'Caravelí',
      'Castilla',
      'Caylloma',
      'Condesuyos',
      'Islay',
      'La Unión',
    ],
    'Ayacucho': [
      'Huamanga',
      'Cangallo',
      'Huanca Sancos',
      'Huanta',
      'La Mar',
      'Lucanas',
      'Parinacochas',
      'Páucar del Sara Sara',
      'Sucre',
      'Víctor Fajardo',
      'Vilcas Huamán',
    ],
    'Cajamarca': [
      'Cajamarca',
      'Cajabamba',
      'Celendín',
      'Chota',
      'Contumazá',
      'Cutervo',
      'Hualgayoc',
      'Jaén',
      'San Ignacio',
      'San Marcos',
      'San Miguel',
      'San Pablo',
      'Santa Cruz',
    ],
    'Callao': ['Callao'],
    'Cusco': [
      'Cusco',
      'Acomayo',
      'Anta',
      'Calca',
      'Canas',
      'Canchis',
      'Chumbivilcas',
      'Espinar',
      'La Convención',
      'Paruro',
      'Paucartambo',
      'Quispicanchi',
      'Urubamba',
    ],
    'Huancavelica': [
      'Huancavelica',
      'Acobamba',
      'Angaraes',
      'Castrovirreyna',
      'Churcampa',
      'Huaytará',
      'Tayacaja',
    ],
    'Huánuco': [
      'Huánuco',
      'Ambo',
      'Dos de Mayo',
      'Huacaybamba',
      'Huamalíes',
      'Leoncio Prado',
      'Marañón',
      'Pachitea',
      'Puerto Inca',
      'Lauricocha',
      'Yarowilca',
    ],
    'Ica': ['Ica', 'Chincha', 'Nazca', 'Palpa', 'Pisco'],
    'Junín': [
      'Huancayo',
      'Concepción',
      'Chanchamayo',
      'Jauja',
      'Junín',
      'Satipo',
      'Tarma',
      'Yauli',
      'Chupaca',
    ],
    'La Libertad': [
      'Trujillo',
      'Ascope',
      'Bolívar',
      'Chepén',
      'Julcán',
      'Otuzco',
      'Pacasmayo',
      'Pataz',
      'Sánchez Carrión',
      'Santiago de Chuco',
      'Gran Chimú',
      'Virú',
    ],
    'Lambayeque': ['Chiclayo', 'Ferreñafe', 'Lambayeque'],
    'Lima': [
      'Lima',
      'Barranca',
      'Cajatambo',
      'Canta',
      'Cañete',
      'Huaral',
      'Huarochirí',
      'Huaura',
      'Oyón',
      'Yauyos',
    ],
    'Loreto': [
      'Maynas',
      'Alto Amazonas',
      'Loreto',
      'Mariscal Ramón Castilla',
      'Requena',
      'Ucayali',
      'Datem del Marañón',
      'Putumayo',
    ],
    'Madre de Dios': ['Tambopata', 'Manu', 'Tahuamanu'],
    'Moquegua': ['Mariscal Nieto', 'General Sánchez Cerro', 'Ilo'],
    'Pasco': ['Pasco', 'Daniel Alcides Carrión', 'Oxapampa'],
    'Piura': [
      'Piura',
      'Ayabaca',
      'Huancabamba',
      'Morropón',
      'Paita',
      'Sullana',
      'Talara',
      'Sechura',
    ],
    'Puno': [
      'Puno',
      'Azángaro',
      'Carabaya',
      'Chucuito',
      'El Collao',
      'Huancané',
      'Lampa',
      'Melgar',
      'Moho',
      'San Antonio de Putina',
      'San Román',
      'Sandia',
      'Yunguyo',
    ],
    'San Martín': [
      'Moyobamba',
      'Bellavista',
      'El Dorado',
      'Huallaga',
      'Lamas',
      'Mariscal Cáceres',
      'Picota',
      'Rioja',
      'San Martín',
      'Tocache',
    ],
    'Tacna': ['Tacna', 'Candarave', 'Jorge Basadre', 'Tarata'],
    'Tumbes': ['Tumbes', 'Contralmirante Villar', 'Zarumilla'],
    'Ucayali': ['Coronel Portillo', 'Atalaya', 'Padre Abad', 'Purús'],
  };

  // ==================== VENEZUELA ====================

  /// Estados de Venezuela
  static const List<String> _venezuelaEstados = [
    'Amazonas',
    'Anzoátegui',
    'Apure',
    'Aragua',
    'Barinas',
    'Bolívar',
    'Carabobo',
    'Cojedes',
    'Delta Amacuro',
    'Distrito Capital',
    'Falcón',
    'Guárico',
    'La Guaira',
    'Lara',
    'Mérida',
    'Miranda',
    'Monagas',
    'Nueva Esparta',
    'Portuguesa',
    'Sucre',
    'Táchira',
    'Trujillo',
    'Yaracuy',
    'Zulia',
  ];

  /// Municipios por estado
  static const Map<String, List<String>> _venezuelaMunicipios = {
    'Amazonas': [
      'Atures',
      'Autana',
      'Atabapo',
      'Maroa',
      'Manapiare',
      'Río Negro',
      'Alto Orinoco',
    ],
    'Anzoátegui': [
      'Anaco',
      'Aragua de Barcelona',
      'Barcelona',
      'Bolívar',
      'Bruzual',
      'Cajigal',
      'Carvajal',
      'Diego Bautista Urbaneja',
      'El Carmen',
      'El Tigre',
      'Freites',
      'Guanipa',
      'Guanta',
      'Independencia',
      'Libertad',
      'McGregor',
      'Miranda',
      'Monagas',
      'Peñalver',
      'Píritu',
      'San José de Guanipa',
      'San Juan de Capistrano',
      'Santa Ana',
      'Simón Bolívar',
      'Simón Rodríguez',
      'Sotillo',
    ],
    'Apure': [
      'Achaguas',
      'Biruaca',
      'Muñoz',
      'Páez',
      'Pedro Camejo',
      'Rómulo Gallegos',
      'San Fernando',
    ],
    'Aragua': [
      'Bolívar',
      'Camatagua',
      'Francisco Linares Alcántara',
      'Girardot',
      'José Ángel Lamas',
      'José Félix Ribas',
      'José Rafael Revenga',
      'Libertador',
      'Mario Briceño Iragorry',
      'Ocumare de la Costa de Oro',
      'San Casimiro',
      'San Sebastián',
      'Santiago Mariño',
      'Santos Michelena',
      'Sucre',
      'Tovar',
      'Zamora',
    ],
    'Barinas': [
      'Alberto Arvelo Torrealba',
      'Andrés Eloy Blanco',
      'Antonio José de Sucre',
      'Arismendi',
      'Barinas',
      'Bolívar',
      'Cruz Paredes',
      'Ezequiel Zamora',
      'Obispos',
      'Pedraza',
      'Rojas',
      'Sosa',
    ],
    'Bolívar': [
      'Angostura del Orinoco',
      'Caroní',
      'Cedeño',
      'El Callao',
      'Gran Sabana',
      'Heres',
      'Piar',
      'Raúl Leoni',
      'Roscio',
      'Sifontes',
      'Sucre',
    ],
    'Carabobo': [
      'Bejuma',
      'Carlos Arvelo',
      'Diego Ibarra',
      'Guacara',
      'Juan José Mora',
      'Libertador',
      'Los Guayos',
      'Miranda',
      'Montalbán',
      'Naguanagua',
      'Puerto Cabello',
      'San Diego',
      'San Joaquín',
      'Valencia',
    ],
    'Cojedes': [
      'Anzoátegui',
      'Ezequiel Zamora',
      'Falcón',
      'Girardot',
      'Lima Blanco',
      'Pao de San Juan Bautista',
      'Ricaurte',
      'Rómulo Gallegos',
      'Tinaco',
    ],
    'Delta Amacuro': ['Antonio Díaz', 'Casacoima', 'Pedernales', 'Tucupita'],
    'Distrito Capital': ['Libertador'],
    'Falcón': [
      'Acosta',
      'Bolívar',
      'Buchivacoa',
      'Cacique Manaure',
      'Carirubana',
      'Colina',
      'Dabajuro',
      'Democracia',
      'Falcón',
      'Federación',
      'Jacura',
      'Los Taques',
      'Mauroa',
      'Miranda',
      'Monseñor Iturriza',
      'Palmasola',
      'Petit',
      'Píritu',
      'San Francisco',
      'Silva',
      'Sucre',
      'Tocópero',
      'Unión',
      'Urumaco',
      'Zamora',
    ],
    'Guárico': [
      'Camaguán',
      'Chaguaramas',
      'El Socorro',
      'Francisco de Miranda',
      'José Félix Ribas',
      'José Tadeo Monagas',
      'Juan Germán Roscio',
      'Julián Mellado',
      'Las Mercedes',
      'Leonardo Infante',
      'Ortiz',
      'San Gerónimo de Guayabal',
      'San José de Guaribe',
      'Santa María de Ipire',
      'Zaraza',
    ],
    'La Guaira': ['Vargas'],
    'Lara': [
      'Andrés Eloy Blanco',
      'Crespo',
      'Iribarren',
      'Jiménez',
      'Morán',
      'Palavecino',
      'Simón Planas',
      'Torres',
      'Urdaneta',
    ],
    'Mérida': [
      'Alberto Adriani',
      'Andrés Bello',
      'Antonio Pinto Salinas',
      'Aricagua',
      'Arzobispo Chacón',
      'Campo Elías',
      'Caracciolo Parra Olmedo',
      'Cardenal Quintero',
      'Guaraque',
      'Julio César Salas',
      'Justo Briceño',
      'Libertador',
      'Miranda',
      'Obispo Ramos de Lora',
      'Padre Noguera',
      'Pueblo Llano',
      'Rangel',
      'Rivas Dávila',
      'Santos Marquina',
      'Sucre',
      'Tovar',
      'Tulio Febres Cordero',
      'Zea',
    ],
    'Miranda': [
      'Acevedo',
      'Andrés Bello',
      'Baruta',
      'Brión',
      'Buroz',
      'Carrizal',
      'Chacao',
      'Cristóbal Rojas',
      'El Hatillo',
      'Guaicaipuro',
      'Independencia',
      'Lander',
      'Los Salias',
      'Páez',
      'Paz Castillo',
      'Pedro Gual',
      'Plaza',
      'Simón Bolívar',
      'Sucre',
      'Urdaneta',
      'Zamora',
    ],
    'Monagas': [
      'Acosta',
      'Aguasay',
      'Bolívar',
      'Caripe',
      'Cedeño',
      'Ezequiel Zamora',
      'Libertador',
      'Maturín',
      'Piar',
      'Punceres',
      'Santa Bárbara',
      'Sotillo',
      'Uracoa',
    ],
    'Nueva Esparta': [
      'Antolín del Campo',
      'Arismendi',
      'Díaz',
      'García',
      'Gómez',
      'Maneiro',
      'Marcano',
      'Mariño',
      'Península de Macanao',
      'Tubores',
      'Villalba',
    ],
    'Portuguesa': [
      'Agua Blanca',
      'Araure',
      'Esteller',
      'Guanare',
      'Guanarito',
      'Monseñor José Vicente de Unda',
      'Ospino',
      'Páez',
      'Papelón',
      'San Genaro de Boconoíto',
      'San Rafael de Onoto',
      'Santa Rosalía',
      'Sucre',
      'Turén',
    ],
    'Sucre': [
      'Andrés Eloy Blanco',
      'Andrés Mata',
      'Arismendi',
      'Benítez',
      'Bermúdez',
      'Bolívar',
      'Cajigal',
      'Cruz Salmerón Acosta',
      'Libertador',
      'Mariño',
      'Mejía',
      'Montes',
      'Ribero',
      'Sucre',
      'Valdez',
    ],
    'Táchira': [
      'Andrés Bello',
      'Antonio Rómulo Costa',
      'Ayacucho',
      'Bolívar',
      'Cárdenas',
      'Córdoba',
      'Fernández Feo',
      'Francisco de Miranda',
      'García de Hevia',
      'Guásimos',
      'Independencia',
      'Jáuregui',
      'José María Vargas',
      'Junín',
      'Libertad',
      'Libertador',
      'Lobatera',
      'Michelena',
      'Panamericano',
      'Pedro María Ureña',
      'Rafael Urdaneta',
      'Samuel Dario Maldonado',
      'San Cristóbal',
      'Seboruco',
      'Simón Rodríguez',
      'Sucre',
      'Torbes',
      'Uribante',
    ],
    'Trujillo': [
      'Andrés Bello',
      'Boconó',
      'Bolívar',
      'Candelaria',
      'Carache',
      'Escuque',
      'José Felipe Márquez Cañizales',
      'Juan Vicente Campo Elías',
      'La Ceiba',
      'Miranda',
      'Monte Carmelo',
      'Motatán',
      'Pampán',
      'Pampanito',
      'Rafael Rangel',
      'San Rafael de Carvajal',
      'Sucre',
      'Trujillo',
      'Urdaneta',
      'Valera',
    ],
    'Yaracuy': [
      'Arístides Bastidas',
      'Bolívar',
      'Bruzual',
      'Cocorote',
      'Independencia',
      'José Antonio Páez',
      'La Trinidad',
      'Manuel Monge',
      'Nirgua',
      'Peña',
      'San Felipe',
      'Sucre',
      'Urachiche',
      'Veroes',
    ],
    'Zulia': [
      'Almirante Padilla',
      'Baralt',
      'Cabimas',
      'Catatumbo',
      'Colón',
      'Francisco Javier Pulgar',
      'Jesús Enrique Lossada',
      'Jesús María Semprún',
      'La Cañada de Urdaneta',
      'Lagunillas',
      'Machiques de Perijá',
      'Mara',
      'Maracaibo',
      'Miranda',
      'Páez',
      'Rosario de Perijá',
      'San Francisco',
      'Santa Rita',
      'Simón Bolívar',
      'Sucre',
      'Valmore Rodríguez',
    ],
  };

  // ==================== ECUADOR ====================

  /// Provincias del Ecuador
  static const List<String> _ecuadorProvincias = [
    'Azuay',
    'Bolívar',
    'Cañar',
    'Carchi',
    'Chimborazo',
    'Cotopaxi',
    'El Oro',
    'Esmeraldas',
    'Galápagos',
    'Guayas',
    'Imbabura',
    'Loja',
    'Los Ríos',
    'Manabí',
    'Morona Santiago',
    'Napo',
    'Orellana',
    'Pastaza',
    'Pichincha',
    'Santa Elena',
    'Santo Domingo de los Tsáchilas',
    'Sucumbíos',
    'Tungurahua',
    'Zamora Chinchipe',
  ];

  /// Cantones por provincia
  static const Map<String, List<String>> _ecuadorCantones = {
    'Azuay': [
      'Cuenca',
      'Girón',
      'Gualaceo',
      'Nabón',
      'Paute',
      'Pucará',
      'San Fernando',
      'Santa Isabel',
      'Sígsig',
      'Oña',
      'Chordeleg',
      'El Pan',
      'Sevilla de Oro',
      'Guachapala',
      'Camilo Ponce Enríquez',
    ],
    'Bolívar': [
      'Guaranda',
      'Chillanes',
      'Chimbo',
      'Echeandía',
      'San Miguel',
      'Caluma',
      'Las Naves',
    ],
    'Cañar': [
      'Azogues',
      'Biblián',
      'Cañar',
      'La Troncal',
      'El Tambo',
      'Déleg',
      'Suscal',
    ],
    'Carchi': [
      'Tulcán',
      'Bolívar',
      'Espejo',
      'Mira',
      'Montúfar',
      'San Pedro de Huaca',
    ],
    'Chimborazo': [
      'Riobamba',
      'Alausí',
      'Colta',
      'Chambo',
      'Chunchi',
      'Guamote',
      'Guano',
      'Pallatanga',
      'Penipe',
      'Cumandá',
    ],
    'Cotopaxi': [
      'Latacunga',
      'La Maná',
      'Pangua',
      'Pujilí',
      'Salcedo',
      'Saquisilí',
      'Sigchos',
    ],
    'El Oro': [
      'Machala',
      'Arenillas',
      'Atahualpa',
      'Balsas',
      'Chilla',
      'El Guabo',
      'Huaquillas',
      'Marcabelí',
      'Pasaje',
      'Piñas',
      'Portovelo',
      'Santa Rosa',
      'Zaruma',
      'Las Lajas',
    ],
    'Esmeraldas': [
      'Esmeraldas',
      'Atacames',
      'Eloy Alfaro',
      'Muisne',
      'Quinindé',
      'Rioverde',
      'San Lorenzo',
    ],
    'Galápagos': ['San Cristóbal', 'Isabela', 'Santa Cruz'],
    'Guayas': [
      'Guayaquil',
      'Alfredo Baquerizo Moreno',
      'Balao',
      'Balzar',
      'Colimes',
      'Daule',
      'Durán',
      'El Empalme',
      'El Triunfo',
      'Milagro',
      'Naranjal',
      'Naranjito',
      'Palestina',
      'Pedro Carbo',
      'Samborondón',
      'Santa Lucía',
      'Salitre',
      'San Jacinto de Yaguachi',
      'Simón Bolívar',
      'Coronel Marcelino Maridueña',
      'Lomas de Sargentillo',
      'Nobol',
      'General Antonio Elizalde',
      'Isidro Ayora',
      'Playas',
    ],
    'Imbabura': [
      'Ibarra',
      'Antonio Ante',
      'Cotacachi',
      'Otavalo',
      'Pimampiro',
      'San Miguel de Urcuquí',
    ],
    'Loja': [
      'Loja',
      'Calvas',
      'Catamayo',
      'Celica',
      'Chaguarpamba',
      'Espíndola',
      'Gonzanamá',
      'Macará',
      'Olmedo',
      'Paltas',
      'Pindal',
      'Puyango',
      'Quilanga',
      'Saraguro',
      'Sozoranga',
      'Zapotillo',
    ],
    'Los Ríos': [
      'Babahoyo',
      'Baba',
      'Montalvo',
      'Puebloviejo',
      'Quevedo',
      'Urdaneta',
      'Ventanas',
      'Vinces',
      'Palenque',
      'Buena Fe',
      'Valencia',
      'Mocache',
      'Quinsaloma',
    ],
    'Manabí': [
      'Portoviejo',
      'Bolívar',
      'Chone',
      'El Carmen',
      'Flavio Alfaro',
      'Jipijapa',
      'Junín',
      'Manta',
      'Montecristi',
      'Paján',
      'Pedernales',
      'Pichincha',
      'Rocafuerte',
      'Santa Ana',
      'Sucre',
      'Tosagua',
      '24 de Mayo',
      'Puerto López',
      'Jama',
      'Jaramijó',
      'San Vicente',
      'Olmedo',
    ],
    'Morona Santiago': [
      'Macas',
      'Gualaquiza',
      'Limón Indanza',
      'Palora',
      'Santiago',
      'Sucúa',
      'Huamboya',
      'San Juan Bosco',
      'Taisha',
      'Logroño',
      'Pablo Sexto',
      'Tiwintza',
    ],
    'Napo': [
      'Tena',
      'Archidona',
      'El Chaco',
      'Quijos',
      'Carlos Julio Arosemena Tola',
    ],
    'Orellana': [
      'Francisco de Orellana',
      'Aguarico',
      'La Joya de los Sachas',
      'Loreto',
    ],
    'Pastaza': ['Puyo', 'Mera', 'Santa Clara', 'Arajuno'],
    'Pichincha': [
      'Quito',
      'Cayambe',
      'Mejía',
      'Pedro Moncayo',
      'Pedro Vicente Maldonado',
      'Puerto Quito',
      'Rumiñahui',
      'San Miguel de los Bancos',
    ],
    'Santa Elena': ['Santa Elena', 'La Libertad', 'Salinas'],
    'Santo Domingo de los Tsáchilas': ['Santo Domingo', 'La Concordia'],
    'Sucumbíos': [
      'Nueva Loja',
      'Cascales',
      'Cuyabeno',
      'Gonzalo Pizarro',
      'Putumayo',
      'Shushufindi',
      'Sucumbíos',
    ],
    'Tungurahua': [
      'Ambato',
      'Baños de Agua Santa',
      'Cevallos',
      'Mocha',
      'Patate',
      'Quero',
      'San Pedro de Pelileo',
      'Santiago de Píllaro',
      'Tisaleo',
    ],
    'Zamora Chinchipe': [
      'Zamora',
      'Chinchipe',
      'Nangaritza',
      'Yacuambi',
      'Yantzaza',
      'El Pangui',
      'Centinela del Cóndor',
      'Palanda',
      'Paquisha',
    ],
  };

  // ==================== COLOMBIA ====================

  /// Departamentos de Colombia
  static const List<String> _colombiaDepartamentos = [
    'Amazonas',
    'Antioquia',
    'Arauca',
    'Atlántico',
    'Bogotá D.C.',
    'Bolívar',
    'Boyacá',
    'Caldas',
    'Caquetá',
    'Casanare',
    'Cauca',
    'Cesar',
    'Chocó',
    'Córdoba',
    'Cundinamarca',
    'Guainía',
    'Guaviare',
    'Huila',
    'La Guajira',
    'Magdalena',
    'Meta',
    'Nariño',
    'Norte de Santander',
    'Putumayo',
    'Quindío',
    'Risaralda',
    'San Andrés y Providencia',
    'Santander',
    'Sucre',
    'Tolima',
    'Valle del Cauca',
    'Vaupés',
    'Vichada',
  ];

  /// Municipios principales por departamento
  static const Map<String, List<String>> _colombiaMunicipios = {
    'Amazonas': ['Leticia', 'Puerto Nariño', 'El Encanto'],
    'Antioquia': [
      'Medellín',
      'Bello',
      'Itagüí',
      'Envigado',
      'Rionegro',
      'Apartadó',
      'Turbo',
      'Caucasia',
      'Santa Fe de Antioquia',
      'Caldas',
      'Copacabana',
      'La Estrella',
      'Sabaneta',
      'Barbosa',
      'Girardota',
    ],
    'Arauca': [
      'Arauca',
      'Arauquita',
      'Saravena',
      'Tame',
      'Fortul',
      'Cravo Norte',
    ],
    'Atlántico': [
      'Barranquilla',
      'Soledad',
      'Malambo',
      'Sabanalarga',
      'Galapa',
      'Baranoa',
      'Puerto Colombia',
    ],
    'Bogotá D.C.': ['Bogotá'],
    'Bolívar': [
      'Cartagena',
      'Magangué',
      'Turbaco',
      'Arjona',
      'San Juan Nepomuceno',
      'El Carmen de Bolívar',
    ],
    'Boyacá': [
      'Tunja',
      'Duitama',
      'Sogamoso',
      'Chiquinquirá',
      'Puerto Boyacá',
      'Paipa',
    ],
    'Caldas': [
      'Manizales',
      'La Dorada',
      'Chinchiná',
      'Villamaría',
      'Riosucio',
      'Anserma',
    ],
    'Caquetá': [
      'Florencia',
      'San Vicente del Caguán',
      'Cartagena del Chairá',
      'Puerto Rico',
      'El Doncello',
    ],
    'Casanare': [
      'Yopal',
      'Aguazul',
      'Villanueva',
      'Tauramena',
      'Paz de Ariporo',
      'Monterrey',
    ],
    'Cauca': [
      'Popayán',
      'Santander de Quilichao',
      'Puerto Tejada',
      'Piendamó',
      'El Tambo',
      'Guapi',
    ],
    'Cesar': [
      'Valledupar',
      'Aguachica',
      'Codazzi',
      'Bosconia',
      'La Jagua de Ibirico',
      'Chimichagua',
    ],
    'Chocó': [
      'Quibdó',
      'Istmina',
      'Condoto',
      'Tadó',
      'Riosucio',
      'Bahía Solano',
    ],
    'Córdoba': [
      'Montería',
      'Cereté',
      'Lorica',
      'Sahagún',
      'Montelíbano',
      'Planeta Rica',
      'Tierralta',
    ],
    'Cundinamarca': [
      'Soacha',
      'Girardot',
      'Zipaquirá',
      'Facatativá',
      'Fusagasugá',
      'Chía',
      'Mosquera',
      'Madrid',
    ],
    'Guainía': ['Inírida'],
    'Guaviare': [
      'San José del Guaviare',
      'Calamar',
      'El Retorno',
      'Miraflores',
    ],
    'Huila': [
      'Neiva',
      'Pitalito',
      'Garzón',
      'La Plata',
      'Campoalegre',
      'San Agustín',
    ],
    'La Guajira': [
      'Riohacha',
      'Maicao',
      'Uribia',
      'Manaure',
      'San Juan del Cesar',
      'Fonseca',
    ],
    'Magdalena': [
      'Santa Marta',
      'Ciénaga',
      'Fundación',
      'El Banco',
      'Plato',
      'Pivijay',
    ],
    'Meta': [
      'Villavicencio',
      'Acacías',
      'Granada',
      'Puerto López',
      'San Martín',
      'Restrepo',
    ],
    'Nariño': [
      'Pasto',
      'Tumaco',
      'Ipiales',
      'Túquerres',
      'La Unión',
      'Samaniego',
    ],
    'Norte de Santander': [
      'Cúcuta',
      'Ocaña',
      'Pamplona',
      'Los Patios',
      'Villa del Rosario',
      'El Zulia',
    ],
    'Putumayo': [
      'Mocoa',
      'Puerto Asís',
      'Orito',
      'Valle del Guamuez',
      'Villagarzón',
      'Puerto Leguízamo',
    ],
    'Quindío': [
      'Armenia',
      'Calarcá',
      'Montenegro',
      'La Tebaida',
      'Circasia',
      'Quimbaya',
    ],
    'Risaralda': [
      'Pereira',
      'Dosquebradas',
      'Santa Rosa de Cabal',
      'La Virginia',
      'Belén de Umbría',
    ],
    'San Andrés y Providencia': ['San Andrés', 'Providencia'],
    'Santander': [
      'Bucaramanga',
      'Floridablanca',
      'Girón',
      'Piedecuesta',
      'Barrancabermeja',
      'San Gil',
    ],
    'Sucre': [
      'Sincelejo',
      'Corozal',
      'San Marcos',
      'Sampués',
      'Tolú',
      'San Onofre',
    ],
    'Tolima': [
      'Ibagué',
      'Espinal',
      'Melgar',
      'Honda',
      'Chaparral',
      'Líbano',
      'Mariquita',
    ],
    'Valle del Cauca': [
      'Cali',
      'Buenaventura',
      'Palmira',
      'Tuluá',
      'Buga',
      'Cartago',
      'Jamundí',
      'Yumbo',
    ],
    'Vaupés': ['Mitú', 'Carurú', 'Taraira'],
    'Vichada': ['Puerto Carreño', 'La Primavera', 'Santa Rosalía', 'Cumaribo'],
  };

  // ==================== ARGENTINA ====================

  /// Provincias de Argentina
  static const List<String> _argentinaProvincias = [
    'Buenos Aires',
    'Ciudad Autónoma de Buenos Aires',
    'Catamarca',
    'Chaco',
    'Chubut',
    'Córdoba',
    'Corrientes',
    'Entre Ríos',
    'Formosa',
    'Jujuy',
    'La Pampa',
    'La Rioja',
    'Mendoza',
    'Misiones',
    'Neuquén',
    'Río Negro',
    'Salta',
    'San Juan',
    'San Luis',
    'Santa Cruz',
    'Santa Fe',
    'Santiago del Estero',
    'Tierra del Fuego',
    'Tucumán',
  ];

  /// Ciudades / Partidos principales por provincia
  static const Map<String, List<String>> _argentinaCiudades = {
    'Buenos Aires': [
      'La Plata',
      'Mar del Plata',
      'Bahía Blanca',
      'Tandil',
      'Quilmes',
      'Lanús',
      'Avellaneda',
      'Lomas de Zamora',
      'Morón',
      'San Isidro',
      'Tigre',
      'Pilar',
      'Campana',
      'Zárate',
      'Junín',
      'Pergamino',
      'Olavarría',
      'Necochea',
      'Tres Arroyos',
      'Azul',
    ],
    'Ciudad Autónoma de Buenos Aires': [
      'Comuna 1 - Retiro, San Nicolás, Puerto Madero, San Telmo, Montserrat, Constitución',
      'Comuna 2 - Recoleta',
      'Comuna 3 - Balvanera, San Cristóbal',
      'Comuna 4 - La Boca, Barracas, Parque Patricios, Nueva Pompeya',
      'Comuna 5 - Almagro, Boedo',
      'Comuna 6 - Caballito',
      'Comuna 7 - Flores, Parque Chacabuco',
      'Comuna 8 - Villa Soldati, Villa Riachuelo, Villa Lugano',
      'Comuna 9 - Liniers, Mataderos, Parque Avellaneda',
      'Comuna 10 - Villa Real, Monte Castro, Versalles, Floresta, Vélez Sarsfield, Villa Luro',
      'Comuna 11 - Villa General Mitre, Villa Devoto, Villa del Parque, Villa Santa Rita',
      'Comuna 12 - Coghlan, Saavedra, Villa Urquiza, Villa Pueyrredón',
      'Comuna 13 - Núñez, Belgrano, Colegiales',
      'Comuna 14 - Palermo',
      'Comuna 15 - Chacarita, Villa Crespo, La Paternal, Villa Ortúzar, Agronomía, Parque Chas',
    ],
    'Catamarca': [
      'San Fernando del Valle de Catamarca',
      'Tinogasta',
      'Andalgalá',
      'Belén',
      'Santa María',
      'Recreo',
    ],
    'Chaco': [
      'Resistencia',
      'Presidencia Roque Sáenz Peña',
      'Villa Ángela',
      'General San Martín',
      'Barranqueras',
      'Charata',
      'Las Breñas',
      'Quitilipi',
    ],
    'Chubut': [
      'Rawson',
      'Comodoro Rivadavia',
      'Trelew',
      'Puerto Madryn',
      'Esquel',
      'Sarmiento',
      'Lago Puelo',
    ],
    'Córdoba': [
      'Córdoba',
      'Río Cuarto',
      'Villa María',
      'San Francisco',
      'Villa Carlos Paz',
      'Alta Gracia',
      'Río Tercero',
      'Bell Ville',
      'Jesús María',
      'La Falda',
      'Cosquín',
    ],
    'Corrientes': [
      'Corrientes',
      'Goya',
      'Paso de los Libres',
      'Curuzú Cuatiá',
      'Mercedes',
      'Monte Caseros',
      'Bella Vista',
    ],
    'Entre Ríos': [
      'Paraná',
      'Concordia',
      'Gualeguaychú',
      'Concepción del Uruguay',
      'Villaguay',
      'Chajarí',
      'Victoria',
      'Colón',
      'Federación',
    ],
    'Formosa': [
      'Formosa',
      'Clorinda',
      'Pirané',
      'El Colorado',
      'Ingeniero Juárez',
      'Las Lomitas',
    ],
    'Jujuy': [
      'San Salvador de Jujuy',
      'San Pedro de Jujuy',
      'Palpalá',
      'Libertador General San Martín',
      'Humahuaca',
      'Tilcara',
      'La Quiaca',
    ],
    'La Pampa': [
      'Santa Rosa',
      'General Pico',
      'Toay',
      'General Acha',
      'Eduardo Castex',
      'Realicó',
    ],
    'La Rioja': [
      'La Rioja',
      'Chilecito',
      'Aimogasta',
      'Chamical',
      'Chepes',
      'Villa Unión',
    ],
    'Mendoza': [
      'Mendoza',
      'San Rafael',
      'Godoy Cruz',
      'Guaymallén',
      'Las Heras',
      'Luján de Cuyo',
      'Maipú',
      'San Martín',
      'Rivadavia',
      'Tunuyán',
      'Tupungato',
      'Malargüe',
    ],
    'Misiones': [
      'Posadas',
      'Oberá',
      'Eldorado',
      'Puerto Iguazú',
      'Jardín América',
      'Apóstoles',
      'Leandro N. Alem',
      'Montecarlo',
    ],
    'Neuquén': [
      'Neuquén',
      'San Martín de los Andes',
      'Zapala',
      'Centenario',
      'Plottier',
      'Cutral Có',
      'Villa La Angostura',
      'Junín de los Andes',
    ],
    'Río Negro': [
      'Viedma',
      'San Carlos de Bariloche',
      'General Roca',
      'Cipolletti',
      'Allen',
      'Choele Choel',
      'El Bolsón',
    ],
    'Salta': [
      'Salta',
      'San Ramón de la Nueva Orán',
      'Tartagal',
      'General Güemes',
      'Metán',
      'Rosario de la Frontera',
      'Cafayate',
      'Joaquín V. González',
    ],
    'San Juan': [
      'San Juan',
      'Rawson',
      'Rivadavia',
      'Chimbas',
      'Pocito',
      'Santa Lucía',
      'Caucete',
      'Jáchal',
    ],
    'San Luis': [
      'San Luis',
      'Villa Mercedes',
      'Merlo',
      'Justo Daract',
      'La Punta',
      'Concarán',
    ],
    'Santa Cruz': [
      'Río Gallegos',
      'Caleta Olivia',
      'Pico Truncado',
      'El Calafate',
      'Puerto Deseado',
      'Las Heras',
      'Puerto San Julián',
    ],
    'Santa Fe': [
      'Santa Fe',
      'Rosario',
      'Rafaela',
      'Venado Tuerto',
      'Reconquista',
      'Villa Gobernador Gálvez',
      'Santo Tomé',
      'Esperanza',
      'Casilda',
      'San Lorenzo',
    ],
    'Santiago del Estero': [
      'Santiago del Estero',
      'La Banda',
      'Termas de Río Hondo',
      'Añatuya',
      'Frías',
      'Fernández',
    ],
    'Tierra del Fuego': ['Ushuaia', 'Río Grande', 'Tolhuin'],
    'Tucumán': [
      'San Miguel de Tucumán',
      'Yerba Buena',
      'Tafí Viejo',
      'Banda del Río Salí',
      'Concepción',
      'Aguilares',
      'Monteros',
      'Famaillá',
    ],
  };

  // ==================== BOLIVIA ====================

  /// Departamentos de Bolivia
  static const List<String> _boliviaDepartamentos = [
    'Beni',
    'Chuquisaca',
    'Cochabamba',
    'La Paz',
    'Oruro',
    'Pando',
    'Potosí',
    'Santa Cruz',
    'Tarija',
  ];

  /// Ciudades / Municipios principales por departamento
  static const Map<String, List<String>> _boliviaCiudades = {
    'Beni': [
      'Trinidad',
      'Riberalta',
      'Guayaramerín',
      'San Borja',
      'San Ignacio de Moxos',
      'Reyes',
      'Santa Ana del Yacuma',
      'Rurrenabaque',
    ],
    'Chuquisaca': [
      'Sucre',
      'Camargo',
      'Monteagudo',
      'Padilla',
      'Tarabuco',
      'Villa Serrano',
      'Zudáñez',
      'Mojocoya',
    ],
    'Cochabamba': [
      'Cochabamba',
      'Quillacollo',
      'Sacaba',
      'Tiquipaya',
      'Colcapirhua',
      'Vinto',
      'Punata',
      'Cliza',
      'Arani',
      'Capinota',
      'Tarata',
      'Shinahota',
      'Villa Tunari',
    ],
    'La Paz': [
      'La Paz',
      'El Alto',
      'Viacha',
      'Achacachi',
      'Copacabana',
      'Coroico',
      'Caranavi',
      'Patacamaya',
      'Desaguadero',
      'Sorata',
      'Guanay',
      'Mapiri',
    ],
    'Oruro': [
      'Oruro',
      'Huanuni',
      'Challapata',
      'Eucaliptus',
      'Caracollo',
      'Machacamarca',
      'Poopó',
    ],
    'Pando': [
      'Cobija',
      'Porvenir',
      'Bolpebra',
      'Bella Flor',
      'Puerto Rico',
      'San Lorenzo',
      'El Sena',
      'Santa Rosa del Abuná',
    ],
    'Potosí': [
      'Potosí',
      'Villazón',
      'Tupiza',
      'Uyuni',
      'Llallagua',
      'Uncía',
      'Betanzos',
      'Cotagaita',
      'Porco',
    ],
    'Santa Cruz': [
      'Santa Cruz de la Sierra',
      'Montero',
      'Warnes',
      'La Guardia',
      'Cotoca',
      'Camiri',
      'Puerto Suárez',
      'San Ignacio de Velasco',
      'Yapacaní',
      'Mineros',
      'San José de Chiquitos',
      'Portachuelo',
      'Samaipata',
      'Buena Vista',
      'Concepción',
    ],
    'Tarija': [
      'Tarija',
      'Yacuiba',
      'Bermejo',
      'Villamontes',
      'Entre Ríos',
      'San Lorenzo',
      'Padcaya',
      'Caraparí',
    ],
  };
}
