#!/usr/bin/env python3
"""Add ARB keys for big feature presentation: ventas, costos, inventario, salud."""
import json, os

ARB_DIR = os.path.join(os.path.dirname(__file__), '..', 'lib', 'l10n')
ES = os.path.join(ARB_DIR, 'app_es.arb')
EN = os.path.join(ARB_DIR, 'app_en.arb')

# (key, spanish, english)
KEYS = [
    # ─── SHARED / COMMON ────────────────────────────────────────
    ('commonCancel', 'Cancelar', 'Cancel'),
    ('commonDelete', 'Eliminar', 'Delete'),
    ('commonEdit', 'Editar', 'Edit'),
    ('commonBack', 'Volver', 'Back'),
    ('commonClose', 'Cerrar', 'Close'),
    ('commonRetry', 'Reintentar', 'Retry'),
    ('commonSaving', 'Guardando...', 'Saving...'),
    ('commonLoading', 'Cargando...', 'Loading...'),
    ('commonPrevious', 'Anterior', 'Previous'),
    ('commonNext', 'Siguiente', 'Next'),
    ('commonContinue', 'Continuar', 'Continue'),
    ('commonLeave', 'Salir', 'Leave'),
    ('commonConfirm', 'Confirmar', 'Confirm'),
    ('commonApply', 'Aplicar', 'Apply'),
    ('commonRestore', 'Restaurar', 'Restore'),
    ('commonDiscard', 'Descartar', 'Discard'),
    ('commonUpdate', 'Actualizar', 'Update'),
    ('commonSave', 'Guardar', 'Save'),
    ('commonAccept', 'Aceptar', 'Accept'),
    ('commonProcessing', 'Procesando...', 'Processing...'),
    ('commonTotal', 'Total', 'Total'),
    ('commonStatus', 'Estado', 'Status'),
    ('commonObservations', 'Observaciones', 'Observations'),
    ('commonName', 'Nombre', 'Name'),
    ('commonDocument', 'Documento', 'Document'),
    ('commonPhone', 'Teléfono', 'Phone'),
    ('commonSupplier', 'Proveedor', 'Supplier'),
    ('commonAmount', 'Monto', 'Amount'),
    ('commonRole', 'Rol', 'Role'),
    ('commonRegistrationDate', 'Fecha de registro', 'Registration date'),
    ('commonRegisteredBy', 'Registrado por', 'Registered by'),
    ('commonRegistrationInfo', 'Información de Registro', 'Registration Info'),
    ('commonLastUpdate', 'Última actualización', 'Last update'),
    ('commonMoreOptions', 'Más opciones', 'More options'),
    ('commonError', 'Error', 'Error'),
    ('commonDraftFoundTitle', 'Borrador encontrado', 'Draft found'),
    ('commonExitWithoutCompleting', '¿Salir sin completar?', 'Leave without completing?'),
    ('commonDataSafe', 'No te preocupes, tus datos están seguros.', "Don't worry, your data is safe."),
    ('commonSubtotal', 'Subtotal', 'Subtotal'),
    ('commonLocation', 'Ubicación', 'Location'),
    ('commonFarm', 'Granja', 'Farm'),
    ('commonBatch', 'Lote', 'Lot'),
    ('commonFarmNotFound', 'Granja no encontrada', 'Farm not found'),
    ('commonBatchNotFound', 'Lote no encontrado', 'Lot not found'),
    ('commonApplyFilters', 'Aplicar filtros', 'Apply filters'),
    ('commonAllTypes', 'Todos los tipos', 'All types'),
    ('commonImportantInfo', 'Información importante', 'Important information'),

    # ─── SHARED MONTH NAMES ─────────────────────────────────────
    ('monthJanuary', 'Enero', 'January'),
    ('monthFebruary', 'Febrero', 'February'),
    ('monthMarch', 'Marzo', 'March'),
    ('monthApril', 'Abril', 'April'),
    ('monthMay', 'Mayo', 'May'),
    ('monthJune', 'Junio', 'June'),
    ('monthJuly', 'Julio', 'July'),
    ('monthAugust', 'Agosto', 'August'),
    ('monthSeptember', 'Septiembre', 'September'),
    ('monthOctober', 'Octubre', 'October'),
    ('monthNovember', 'Noviembre', 'November'),
    ('monthDecember', 'Diciembre', 'December'),
    ('monthJanAbbr', 'ene', 'Jan'),
    ('monthFebAbbr', 'feb', 'Feb'),
    ('monthMarAbbr', 'mar', 'Mar'),
    ('monthAprAbbr', 'abr', 'Apr'),
    ('monthMayAbbr', 'may', 'May'),
    ('monthJunAbbr', 'jun', 'Jun'),
    ('monthJulAbbr', 'jul', 'Jul'),
    ('monthAugAbbr', 'ago', 'Aug'),
    ('monthSepAbbr', 'sep', 'Sep'),
    ('monthOctAbbr', 'oct', 'Oct'),
    ('monthNovAbbr', 'nov', 'Nov'),
    ('monthDecAbbr', 'dic', 'Dec'),

    # ═════════════════════════════════════════════════════════════
    #  VENTAS
    # ═════════════════════════════════════════════════════════════
    # ventas_list_page.dart
    ('ventaLoteTitle', 'Ventas del Lote', 'Lot Sales'),
    ('ventaAllTitle', 'Todas las Ventas', 'All Sales'),
    ('ventaFilterTooltip', 'Filtrar', 'Filter'),
    ('ventaEmptyTitle', 'Sin ventas registradas', 'No sales registered'),
    ('ventaEmptyDescription', 'Registra tu primera venta para comenzar a llevar un control de tus ingresos', 'Register your first sale to start tracking your income'),
    ('ventaEmptyAction', 'Registrar primera venta', 'Register first sale'),
    ('ventaFilterEmptyTitle', 'No se encontraron ventas', 'No sales found'),
    ('ventaFilterEmptyDescription', 'Prueba modificando los filtros de búsqueda para encontrar las ventas que buscas', 'Try modifying the search filters to find the sales you are looking for'),
    ('ventaNewButton', 'Nueva Venta', 'New Sale'),
    ('ventaNewTooltip', 'Registrar nueva venta', 'Register new sale'),
    ('ventaDeleteTitle', '¿Eliminar venta?', 'Delete sale?'),
    ('ventaDeleteSuccess', 'Venta eliminada correctamente', 'Sale deleted successfully'),
    ('ventaFilterTitle', 'Filtrar ventas', 'Filter sales'),
    ('ventaFilterProductType', 'Tipo de producto', 'Product type'),
    ('ventaFilterSaleState', 'Estado de venta', 'Sale status'),
    ('ventaFilterAllStates', 'Todos los estados', 'All statuses'),
    ('ventaStatePending', 'Pendiente', 'Pending'),
    ('ventaStateConfirmed', 'Confirmada', 'Confirmed'),
    ('ventaStateSold', 'Vendida', 'Sold'),
    ('ventaSheetClient', 'Cliente', 'Client'),
    ('ventaSheetDiscount', 'Descuento', 'Discount'),
    ('ventaSheetInvoiceNumber', 'Nº Factura', 'Invoice No.'),
    ('ventaSheetCarrier', 'Transportista', 'Carrier'),
    ('ventaSheetGuideNumber', 'Nº Guía', 'Guide No.'),
    ('ventaSheetBirdCount', 'Cantidad aves', 'Bird count'),
    ('ventaSheetAvgWeight', 'Peso promedio', 'Average weight'),
    ('ventaSheetPricePerKg', 'Precio por kg', 'Price per kg'),
    ('ventaSheetSlaughteredWeight', 'Peso faenado', 'Slaughtered weight'),
    ('ventaSheetYield', 'Rendimiento', 'Yield'),
    ('ventaSheetTotalEggs', 'Total huevos', 'Total eggs'),

    # venta_detail_page.dart
    ('ventaDetailNotFound', 'Venta no encontrada', 'Sale not found'),
    ('ventaDetailTitle', 'Detalle de Venta', 'Sale Detail'),
    ('ventaDetailEditTooltip', 'Editar venta', 'Edit sale'),
    ('ventaDetailClient', 'Cliente', 'Client'),
    ('ventaDetailProductDetails', 'Detalles del Producto', 'Product Details'),
    ('ventaDetailBirdCount', 'Cantidad de aves', 'Bird count'),
    ('ventaDetailAvgWeight', 'Peso promedio', 'Average weight'),
    ('ventaDetailPricePerKg', 'Precio por kg', 'Price per kg'),
    ('ventaDetailQuantity', 'Cantidad', 'Quantity'),
    ('ventaDetailUnitPrice', 'Precio unitario', 'Unit price'),
    ('ventaDetailCarcassYield', 'Rendimiento canal', 'Carcass yield'),
    ('ventaDetailTotalLabel', 'TOTAL', 'TOTAL'),
    ('ventaDetailShare', 'Compartir', 'Share'),
    ('ventaDetailSlaughteredWeight', 'Peso faenado', 'Slaughtered weight'),

    # registrar_venta_page.dart
    ('ventaStepProduct', 'Producto', 'Product'),
    ('ventaStepClient', 'Cliente', 'Client'),
    ('ventaStepDetails', 'Detalles', 'Details'),
    ('ventaDraftFoundMessage', '¿Deseas restaurar el borrador de venta guardado anteriormente?', 'Do you want to restore the previously saved sale draft?'),
    ('ventaDraftRestored', 'Borrador restaurado', 'Draft restored'),
    ('ventaDraftJustNow', 'ahora mismo', 'just now'),
    ('ventaExitMessage', 'No te preocupes, tus datos están seguros.', "Don't worry, your data is safe."),
    ('ventaNoEditPermission', 'No tienes permiso para editar ventas en esta granja', "You don't have permission to edit sales on this farm"),
    ('ventaNoCreatePermission', 'No tienes permiso para registrar ventas en esta granja', "You don't have permission to register sales on this farm"),
    ('ventaUpdateSuccess', 'Venta actualizada correctamente', 'Sale updated successfully'),
    ('ventaCreateSuccess', '¡Venta registrada exitosamente!', 'Sale registered successfully!'),
    ('ventaInventoryWarning', 'Venta registrada, pero hubo un error al actualizar inventario', 'Sale registered, but there was an error updating inventory'),
    ('ventaEditTitle', 'Editar Venta', 'Edit Sale'),
    ('ventaNewTitle', 'Nueva Venta', 'New Sale'),
    ('ventaSelectProductFirst', 'Selecciona un tipo de producto primero', 'Select a product type first'),
    ('ventaDetailsHint', 'Ingresa cantidades, precios y otros detalles', 'Enter quantities, prices and other details'),
    ('ventaNoFarmSelected', 'No hay una granja seleccionada. Por favor selecciona una granja primero.', 'No farm selected. Please select a farm first.'),
    ('ventaLotLabel', 'Lote *', 'Lot *'),
    ('ventaNoActiveLots', 'No hay lotes activos en esta granja.', 'No active lots on this farm.'),
    ('ventaSelectLotHint', 'Selecciona un lote', 'Select a lot'),
    ('ventaSelectLotError', 'Selecciona un lote', 'Select a lot'),
    ('ventaSaleDate', 'Fecha de venta', 'Sale date'),
    ('ventaBirdCount', 'Cantidad de aves', 'Bird count'),
    ('ventaBirdCountRequired', 'Ingresa la cantidad de aves', 'Enter the bird count'),
    ('ventaTotalWeight', 'Peso total (kg)', 'Total weight (kg)'),
    ('ventaSlaughteredWeight', 'Peso faenado total (kg)', 'Total slaughtered weight (kg)'),
    ('ventaWeightRequired', 'Ingresa el peso total', 'Enter the total weight'),
    ('ventaPricePerKg', 'Precio por kg (S/)', 'Price per kg (S/)'),
    ('ventaPriceRequired', 'Ingresa el precio por kg', 'Enter the price per kg'),
    ('ventaEggInstructions', 'Ingresa la cantidad y precio por docena para cada clasificación', 'Enter the quantity and price per dozen for each classification'),
    ('ventaEggQuantity', 'Cantidad', 'Quantity'),
    ('ventaEggPricePerDozen', 'S/ por docena', 'S/ per dozen'),
    ('ventaSaleUnit', 'Unidad de venta', 'Sale unit'),
    ('ventaQuantityRequired', 'Ingresa la cantidad', 'Enter the quantity'),
    ('ventaPriceRequired2', 'Ingresa el precio', 'Enter the price'),
    ('ventaObservations', 'Observaciones', 'Observations'),
    ('ventaObservationsHint', 'Notas adicionales (opcional)', 'Additional notes (optional)'),
    ('ventaSubmitButton', 'Registrar Venta', 'Register Sale'),

    # editar_venta_page.dart
    ('ventaEditPageTitle', 'Editar Venta', 'Edit Sale'),
    ('ventaEditNotFound', 'Venta no encontrada', 'Sale not found'),
    ('ventaEditLoadError', 'Error al cargar la venta', 'Error loading sale'),

    # tipo_producto_step.dart
    ('ventaWhatToSell', '¿Qué deseas vender?', 'What do you want to sell?'),
    ('ventaSelectProductType', 'Selecciona el tipo de producto para esta venta', 'Select the product type for this sale'),
    ('ventaDescAvesVivas', 'Venta de aves en pie, listas para transporte o crianza', 'Sale of live birds, ready for transport or breeding'),
    ('ventaDescHuevos', 'Venta de huevos por clasificación y docena', 'Sale of eggs by classification and dozen'),
    ('ventaDescPollinaza', 'Venta de abono orgánico por bulto, saco o tonelada', 'Sale of organic fertilizer by bag, sack or ton'),
    ('ventaDescAvesFaenadas', 'Aves procesadas y listas para consumo', 'Processed birds, ready for consumption'),
    ('ventaDescAvesDescarte', 'Aves de descarte por fin de ciclo productivo', 'Cull birds at end of production cycle'),

    # cliente_step.dart
    ('ventaClientData', 'Datos del Cliente', 'Client Data'),
    ('ventaClientHint', 'Ingresa la información del comprador', 'Enter the buyer information'),
    ('ventaClientName', 'Nombre completo', 'Full name'),
    ('ventaClientNameHint', 'Ej: Juan Pérez García', 'E.g.: Juan Pérez García'),
    ('ventaClientDocType', 'Tipo de documento *', 'Document type *'),
    ('ventaClientCE', 'Carnet de Extranjería', 'Foreign ID Card'),
    ('ventaClientDocNumber', 'Número de documento', 'Document number'),
    ('ventaClientDni8', '8 dígitos', '8 digits'),
    ('ventaClientRuc11', '11 dígitos', '11 digits'),
    ('ventaClientPhone', 'Teléfono de contacto', 'Contact phone'),
    ('ventaClient9Digits', '9 dígitos', '9 digits'),
    ('ventaClientNameRequired', 'Ingresa el nombre del cliente', 'Enter the client name'),
    ('ventaClientNameMinLength', 'El nombre debe tener al menos 3 caracteres', 'Name must be at least 3 characters'),
    ('ventaClientDocRequired', 'Ingresa el número de documento', 'Enter the document number'),
    ('ventaClientDniError', 'El DNI debe tener 8 dígitos', 'DNI must have 8 digits'),
    ('ventaClientRucError', 'El RUC debe tener 11 dígitos', 'RUC must have 11 digits'),
    ('ventaClientInvalidNumber', 'Número inválido', 'Invalid number'),
    ('ventaClientPhoneRequired', 'Ingresa el teléfono de contacto', 'Enter the contact phone'),
    ('ventaClientPhoneError', 'El teléfono debe tener 9 dígitos', 'Phone must have 9 digits'),

    # seleccion_granja_lote_venta_step.dart
    ('ventaSelectLocation', 'Seleccionar Ubicación', 'Select Location'),
    ('ventaSelectLocationHint', 'Selecciona la granja y el lote para registrar la venta', 'Select the farm and lot to register the sale'),
    ('ventaNoFarms', 'No tienes granjas registradas', 'You have no registered farms'),
    ('ventaCreateFarmFirst', 'Debes crear una granja antes de registrar una venta', 'You must create a farm before registering a sale'),
    ('ventaFarmLabel', 'Granja *', 'Farm *'),
    ('ventaSelectFarmHint', 'Selecciona una granja', 'Select a farm'),
    ('ventaFarmRequired', 'Por favor selecciona una granja', 'Please select a farm'),
    ('ventaNoActiveLots2', 'No hay lotes activos', 'No active lots'),
    ('ventaNoActiveLotsHint', 'Esta granja no tiene lotes activos para registrar ventas', 'This farm has no active lots to register sales'),
    ('ventaLotLabel2', 'Lote *', 'Lot *'),
    ('ventaSelectLotHint2', 'Selecciona un lote', 'Select a lot'),
    ('ventaLotRequired', 'Por favor selecciona un lote', 'Please select a lot'),
    ('ventaFarmLoadError', 'Error al cargar granjas', 'Error loading farms'),
    ('ventaLotLoadError2', 'Error al cargar lotes', 'Error loading lots'),

    # ventas_resumen_card.dart
    ('ventaSummaryTitle', 'Resumen de Ventas', 'Sales Summary'),
    ('ventaSummaryTotal', 'Total en ventas', 'Total in sales'),
    ('ventaSummaryActive', 'Activas', 'Active'),
    ('ventaSummaryCompleted', 'Completadas', 'Completed'),

    # ventas_error_state.dart
    ('ventaLoadError', 'Error al cargar ventas', 'Error loading sales'),
    ('ventaLoadErrorDetail', 'Ocurrió un problema al obtener las ventas', 'A problem occurred while fetching sales'),

    # venta_list_card.dart
    ('ventaCardBuyer', 'Comprador: ', 'Buyer: '),
    ('ventaCardProduct', 'Producto: ', 'Product: '),
    ('ventaCardBirds', 'aves', 'birds'),
    ('ventaCardEggs', 'huevos', 'eggs'),

    # share text
    ('ventaShareReceiptTitle', '📋 COMPROBANTE DE VENTA', '📋 SALE RECEIPT'),

    # ═════════════════════════════════════════════════════════════
    #  COSTOS
    # ═════════════════════════════════════════════════════════════
    # costos_list_page.dart
    ('costoLoteTitle', 'Costos del Lote', 'Lot Costs'),
    ('costoAllTitle', 'Todos los Costos', 'All Costs'),
    ('costoFilterTooltip', 'Filtrar', 'Filter'),
    ('costoEmptyTitle', 'Sin costos registrados', 'No costs registered'),
    ('costoEmptyDescription', 'Registra tus gastos operativos para llevar un control detallado de los costos de producción', 'Register your operating expenses to keep detailed track of production costs'),
    ('costoEmptyAction', 'Registrar Costo', 'Register Cost'),
    ('costoFilterEmptyTitle', 'No se encontraron costos', 'No costs found'),
    ('costoFilterEmptyDescription', 'Intenta ajustar los filtros o buscar con otros términos', 'Try adjusting the filters or searching with other terms'),
    ('costoNewButton', 'Nuevo Costo', 'New Cost'),
    ('costoNewTooltip', 'Registrar nuevo costo', 'Register new cost'),
    ('costoRejectTitle', 'Rechazar Costo', 'Reject Cost'),
    ('costoRejectReasonLabel', 'Motivo del rechazo', 'Rejection reason'),
    ('costoRejectReasonHint', 'Explica por qué se rechaza este costo', 'Explain why this cost is rejected'),
    ('costoRejectButton', 'Rechazar', 'Reject'),
    ('costoRejectReasonRequired', 'Ingresa un motivo de rechazo', 'Enter a rejection reason'),
    ('costoDeleteTitle', 'Eliminar Costo', 'Delete Cost'),
    ('costoDeleteWarning', 'Esta acción no se puede deshacer.', 'This action cannot be undone.'),
    ('costoDeleteSuccess', 'Costo eliminado correctamente', 'Cost deleted successfully'),
    ('costoFilterTitle', 'Filtrar costos', 'Filter costs'),
    ('costoFilterExpenseType', 'Tipo de gasto', 'Expense type'),

    # costo_detail_page.dart
    ('costoDetailLoadError', 'No pudimos cargar el detalle del costo', "We couldn't load the cost details"),
    ('costoDetailNotFound', 'Costo no encontrado', 'Cost not found'),
    ('costoDetailTitle', 'Detalle del Costo', 'Cost Detail'),
    ('costoDetailEditTooltip', 'Editar costo', 'Edit cost'),
    ('costoDetailPending', 'Pendiente', 'Pending'),
    ('costoDetailRejected', 'Rechazado', 'Rejected'),
    ('costoDetailApproved', 'Aprobado', 'Approved'),
    ('costoDetailNoStatus', 'Sin estado', 'No status'),
    ('costoDetailGeneralInfo', 'Información General', 'General Information'),
    ('costoDetailConcept', 'Concepto', 'Concept'),
    ('costoDetailInvoiceNo', 'Nº Factura', 'Invoice No.'),
    ('costoDetailDeleteConfirm', '¿Estás seguro de que deseas eliminar este costo?', 'Are you sure you want to delete this cost?'),
    ('costoDetailDeleteWarning', 'Esta acción no se puede deshacer.', 'This action cannot be undone.'),
    ('costoDetailDeleteError', 'Error al eliminar', 'Error deleting'),
    ('costoDetailDeleteSuccess', 'Costo eliminado exitosamente', 'Cost deleted successfully'),

    # registrar_costo_page.dart
    ('costoStepType', 'Tipo', 'Type'),
    ('costoStepAmount', 'Monto', 'Amount'),
    ('costoStepDetails', 'Detalles', 'Details'),
    ('costoDraftFoundMessage', '¿Deseas restaurar el borrador guardado anteriormente?', 'Do you want to restore the previously saved draft?'),
    ('costoTypeRequired', 'Por favor selecciona un tipo de gasto', 'Please select an expense type'),
    ('costoNoEditPermission', 'No tienes permiso para editar costos en esta granja', "You don't have permission to edit costs on this farm"),
    ('costoNoCreatePermission', 'No tienes permiso para registrar costos en esta granja', "You don't have permission to register costs on this farm"),
    ('costoUpdateSuccess', 'Costo actualizado correctamente', 'Cost updated successfully'),
    ('costoCreateSuccess', 'Costo registrado correctamente', 'Cost registered successfully'),
    ('costoInventoryWarning', 'Costo registrado, pero hubo un error al actualizar inventario', 'Cost registered, but there was an error updating inventory'),
    ('costoEditTitle', 'Editar Costo', 'Edit Cost'),
    ('costoRegisterTitle', 'Registrar Costo', 'Register Cost'),
    ('costoRegisterButton', 'Registrar', 'Register'),
    ('costoFarmRequired', 'Por favor selecciona una granja', 'Please select a farm'),

    # tipo_concepto_step.dart
    ('costoWhatType', '¿Qué tipo de gasto es?', 'What type of expense is it?'),
    ('costoSelectCategory', 'Selecciona la categoría que mejor describe este gasto', 'Select the category that best describes this expense'),

    # monto_step.dart
    ('costoAmountTitle', 'Monto del Gasto', 'Expense Amount'),
    ('costoAmountHint', 'Ingresa el monto total del gasto en soles', 'Enter the total amount of the expense in soles'),
    ('costoConceptLabel', 'Concepto del gasto', 'Expense concept'),
    ('costoConceptHint', 'Ej: Compra de alimento balanceado', 'E.g.: Purchase of balanced feed'),
    ('costoConceptRequired', 'Ingresa el concepto del gasto', 'Enter the expense concept'),
    ('costoConceptMinLength', 'El concepto debe tener al menos 5 caracteres', 'Concept must be at least 5 characters'),
    ('costoAmountLabel', 'Monto', 'Amount'),
    ('costoAmountRequired', 'Ingresa el monto', 'Enter the amount'),
    ('costoAmountInvalid', 'Ingresa un monto válido', 'Enter a valid amount'),
    ('costoDateLabel', 'Fecha del gasto *', 'Expense date *'),
    ('costoInventoryLinkInfo', 'Puedes vincular este gasto a un producto del inventario para actualizar el stock automáticamente.', 'You can link this expense to an inventory product to update stock automatically.'),
    ('costoLinkFood', 'Vincular a alimento del inventario', 'Link to inventory food'),
    ('costoLinkMedicine', 'Vincular a medicamento del inventario', 'Link to inventory medicine'),
    ('costoInventorySearchHint', 'Buscar en inventario (opcional)...', 'Search inventory (optional)...'),
    ('costoLinkedProduct', 'Producto vinculado', 'Linked product'),
    ('costoStockUpdateNote', 'Se actualizará el stock al guardar', 'Stock will be updated on save'),

    # detalles_step.dart
    ('costoAdditionalDetails', 'Detalles Adicionales', 'Additional Details'),
    ('costoAdditionalDetailsHint', 'Información complementaria del gasto', 'Complementary expense information'),
    ('costoSupplierHint', 'Nombre del proveedor o empresa', 'Supplier or company name'),
    ('costoSupplierRequired', 'Ingresa el nombre del proveedor', 'Enter the supplier name'),
    ('costoSupplierMinLength', 'El nombre debe tener al menos 3 caracteres', 'Name must be at least 3 characters'),
    ('costoInvoiceLabel', 'Número de Factura/Recibo', 'Invoice/Receipt Number'),
    ('costoObservationsHint', 'Notas adicionales sobre este gasto', 'Additional notes about this expense'),

    # costo_list_card.dart
    ('costoCardType', 'Tipo: ', 'Type: '),
    ('costoCardConcept', 'Concepto: ', 'Concept: '),
    ('costoCardSupplier', 'Proveedor: ', 'Supplier: '),
    ('costoTypeAlimento', 'Alimento', 'Feed'),
    ('costoTypeManoDeObra', 'Mano de Obra', 'Labor'),
    ('costoTypeEnergia', 'Energía', 'Energy'),
    ('costoTypeMedicamento', 'Medicamento', 'Medicine'),
    ('costoTypeMantenimiento', 'Mantenimiento', 'Maintenance'),
    ('costoTypeAgua', 'Agua', 'Water'),
    ('costoTypeTransporte', 'Transporte', 'Transport'),
    ('costoTypeAdministrativo', 'Administrativo', 'Administrative'),
    ('costoTypeDepreciacion', 'Depreciación', 'Depreciation'),
    ('costoTypeFinanciero', 'Financiero', 'Financial'),
    ('costoTypeOtros', 'Otros', 'Others'),

    # costos_resumen_card.dart
    ('costoSummaryTitle', 'Resumen de Costos', 'Costs Summary'),
    ('costoSummaryTotal', 'Total en costos', 'Total in costs'),
    ('costoSummaryApproved', 'Aprobados', 'Approved'),
    ('costoSummaryPending', 'Pendientes', 'Pending'),

    # costos_empty_state.dart
    ('costoLoadError', 'Error al cargar costos', 'Error loading costs'),

    # ═════════════════════════════════════════════════════════════
    #  INVENTARIO
    # ═════════════════════════════════════════════════════════════
    # inventario_page.dart
    ('inventarioTitle', 'Inventario', 'Inventory'),
    ('invFilterByType', 'Filtrar por tipo', 'Filter by type'),
    ('invSearchByNameOrCode', 'Buscar por nombre o código...', 'Search by name or code...'),
    ('invTabItems', 'Items', 'Items'),
    ('invTabMovements', 'Movimientos', 'Movements'),
    ('invNoFarmSelected', 'Sin granja seleccionada', 'No farm selected'),
    ('invSelectFarmFromHome', 'Selecciona una granja desde el inicio', 'Select a farm from the home screen'),
    ('invAddNewItemTooltip', 'Agregar nuevo ítem al inventario', 'Add new inventory item'),
    ('invNewItem', 'Nuevo Item', 'New Item'),
    ('invNoResults', 'Sin resultados', 'No results'),
    ('invNoMovements', 'Sin movimientos', 'No movements'),
    ('invNoMovementsMatchSearch', 'No hay movimientos que coincidan con tu búsqueda', 'No movements match your search'),
    ('invNoMovementsYet', 'No hay movimientos registrados aún', 'No movements recorded yet'),
    ('invErrorLoadingMovements', 'No pudimos cargar los movimientos', 'Could not load movements'),
    ('invNoItemsInInventory', 'Sin items en inventario', 'No items in inventory'),
    ('invNoItemsMatchFilters', 'No hay items que coincidan con los filtros', 'No items match the filters'),
    ('invAddYourFirstItem', 'Agrega tu primer item de inventario', 'Add your first inventory item'),
    ('invClearFilters', 'Limpiar filtros', 'Clear filters'),
    ('invAddItem', 'Agregar Item', 'Add Item'),
    ('invItemDeletedSuccess', 'Item eliminado correctamente', 'Item deleted successfully'),
    ('invApplyFilter', 'Aplicar filtro', 'Apply filter'),

    # item_detalle_inventario_page.dart
    ('invItemDetail', 'Detalle del Item', 'Item Detail'),
    ('invRegisterEntry', 'Registrar Entrada', 'Register Entry'),
    ('invRegisterExit', 'Registrar Salida', 'Register Exit'),
    ('invAdjustStock', 'Ajustar Stock', 'Adjust Stock'),
    ('invItemNotFound', 'Item no encontrado', 'Item not found'),
    ('invErrorLoadingItem', 'No pudimos cargar el item de inventario', 'Could not load the inventory item'),
    ('invStockDepleted', 'Agotado', 'Depleted'),
    ('invStockLow', 'Stock Bajo', 'Low Stock'),
    ('invStockAvailable', 'Disponible', 'Available'),
    ('invStockCurrent', 'Stock Actual', 'Current Stock'),
    ('invStockMinimum', 'Stock Mínimo', 'Minimum Stock'),
    ('invTotalValue', 'Valor Total', 'Total Value'),
    ('invInformation', 'Información', 'Information'),
    ('invCode', 'Código', 'Code'),
    ('invDescription', 'Descripción', 'Description'),
    ('invUnit', 'Unidad', 'Unit'),
    ('invUnitPrice', 'Precio Unitario', 'Unit Price'),
    ('invExpiration', 'Vencimiento', 'Expiration'),
    ('invSupplierBatch', 'Lote Proveedor', 'Supplier Batch'),
    ('invWarehouse', 'Almacén', 'Warehouse'),
    ('invAlerts', 'Alertas', 'Alerts'),
    ('invAlertStockDepleted', 'Stock agotado', 'Stock depleted'),
    ('invAlertProductExpired', 'Producto vencido', 'Product expired'),
    ('invLastMovements', 'Últimos Movimientos', 'Recent Movements'),
    ('invViewAll', 'Ver todo', 'View all'),
    ('invNoMovementsRegistered', 'Sin movimientos registrados', 'No movements recorded'),
    ('invCouldNotLoadMovements', 'No se pudieron cargar los movimientos', 'Could not load movements'),
    ('invItemDeleted', 'Item eliminado', 'Item deleted'),

    # crear_item_inventario_page.dart
    ('invStepType', 'Tipo', 'Type'),
    ('invStepBasic', 'Básico', 'Basic'),
    ('invStepStock', 'Stock', 'Stock'),
    ('invStepDetails', 'Detalles', 'Details'),
    ('invDraftFound', 'Borrador encontrado', 'Draft found'),
    ('invEditItem', 'Editar Item', 'Edit Item'),
    ('invNewItemTitle', 'Nuevo Item', 'New Item'),
    ('invCreateItem', 'Crear Item', 'Create Item'),
    ('invImageTooLarge', 'La imagen excede 5MB. Elige una más pequeña', 'Image exceeds 5MB. Choose a smaller one'),
    ('invImageSelected', 'Imagen seleccionada', 'Image selected'),
    ('invErrorSelectingImage', 'Error al seleccionar imagen', 'Error selecting image'),
    ('invCouldNotUploadImage', 'No se pudo subir la imagen', 'Could not upload image'),
    ('invItemSavedWithoutImage', 'El item se guardará sin imagen', 'Item will be saved without image'),
    ('invItemUpdatedSuccess', 'Item actualizado correctamente', 'Item updated successfully'),
    ('invDraftAutoSaveMessage', 'No te preocupes, tus datos están seguros. Tu progreso se guarda automáticamente.', "Don't worry, your data is safe. Your progress is saved automatically."),

    # historial_movimientos_page.dart
    ('invMovementsTitle', 'Movimientos', 'Movements'),
    ('invFilter', 'Filtrar', 'Filter'),
    ('invErrorLoadingMovementsPage', 'Error al cargar movimientos', 'Error loading movements'),
    ('invNoMovementsWithFilters', 'No hay movimientos con los filtros aplicados', 'No movements with the applied filters'),
    ('invNoMovementsRegisteredHist', 'Sin movimientos registrados', 'No movements recorded'),
    ('invClearFiltersHist', 'Limpiar filtros', 'Clear filters'),
    ('invToday', 'Hoy', 'Today'),
    ('invYesterday', 'Ayer', 'Yesterday'),
    ('invFilterMovements', 'Filtrar Movimientos', 'Filter Movements'),
    ('invMovementType', 'Tipo de movimiento', 'Movement type'),
    ('invAll', 'Todos', 'All'),
    ('invDateRange', 'Rango de fechas', 'Date range'),
    ('invFrom', 'Desde', 'From'),
    ('invUntil', 'Hasta', 'Until'),
    ('invClear', 'Limpiar', 'Clear'),

    # inventario_dialogs.dart
    ('invDialogRegisterEntry', 'Registrar Entrada', 'Register Entry'),
    ('invDialogRegisterExit', 'Registrar Salida', 'Register Exit'),
    ('invDialogMovementType', 'Tipo de movimiento', 'Movement type'),
    ('invSelectType', 'Seleccionar tipo', 'Select type'),
    ('invEnterQuantity', 'Ingresa una cantidad', 'Enter a quantity'),
    ('invEnterValidNumberGt0', 'Ingresa un número válido mayor a 0', 'Enter a valid number greater than 0'),
    ('invQuantityExceedsStock', 'Cantidad mayor al stock disponible', 'Quantity exceeds available stock'),
    ('invTotalCost', 'Costo Total', 'Total Cost'),
    ('invSupplierName', 'Nombre del proveedor', 'Supplier name'),
    ('invObservation', 'Observación', 'Observation'),
    ('invReasonOrObservation', 'Motivo u observación', 'Reason or observation'),
    ('invDialogAdjustStock', 'Ajustar Stock', 'Adjust Stock'),
    ('invEnterNewStock', 'Ingresa el nuevo stock', 'Enter the new stock'),
    ('invEnterValidNumber', 'Ingresa un número válido', 'Enter a valid number'),
    ('invAdjustmentReason', 'Motivo del ajuste', 'Adjustment reason'),
    ('invReasonRequired', 'El motivo es requerido', 'Reason is required'),
    ('invAdjust', 'Ajustar', 'Adjust'),
    ('invStockAdjustedSuccess', 'Stock ajustado correctamente', 'Stock adjusted successfully'),
    ('invEntryRegistered', 'Entrada registrada', 'Entry registered'),
    ('invExitRegistered', 'Salida registrada', 'Exit registered'),
    ('invDeleteItem', 'Eliminar Item', 'Delete Item'),
    ('invActionIrreversible', 'Esta acción es irreversible:', 'This action is irreversible:'),
    ('invDeleteWarningDetails', '• Se eliminarán todos los movimientos\n• Se perderá el historial de stock\n• No se podrá recuperar la información', '• All movements will be deleted\n• Stock history will be lost\n• Information cannot be recovered'),
    ('invTypeNameToConfirm', 'Escribe el nombre para confirmar:', 'Type the name to confirm:'),
    ('invTypeHere', 'Escribe aquí', 'Type here'),

    # item_inventario_card.dart
    ('invCardDepleted', 'Agotado', 'Depleted'),
    ('invCardLowStock', 'Stock Bajo', 'Low Stock'),
    ('invCardAvailable', 'Disponible', 'Available'),
    ('invCardProductExpired', 'Producto vencido', 'Product expired'),
    ('invViewDetails', 'Ver Detalles', 'View Details'),
    ('invMoreOptionsItem', 'Más opciones del item', 'More item options'),
    ('invCardDetails', 'Detalles', 'Details'),
    ('invCardStock', 'Stock', 'Stock'),
    ('invCardMinimum', 'Mínimo', 'Minimum'),
    ('invCardValue', 'Valor', 'Value'),

    # inventario_selector.dart
    ('invSelectProduct', 'Seleccionar producto', 'Select product'),
    ('invSearchInventory', 'Buscar en inventario...', 'Search inventory...'),
    ('invSearchProduct', 'Buscar producto...', 'Search product...'),
    ('invNoProductsFound', 'No se encontraron productos', 'No products found'),
    ('invNoProductsAvailable', 'No hay productos disponibles', 'No products available'),
    ('invSelectorStockLow', 'Stock bajo', 'Low stock'),
    ('invErrorLoadingInventory', 'Error al cargar inventario', 'Error loading inventory'),

    # stock_step.dart
    ('invStockTitle', 'Stock', 'Stock'),
    ('invConfigureQuantities', 'Configura las cantidades y unidad de medida', 'Configure quantities and unit of measure'),
    ('invUnitsFilteredAutomatically', 'Las unidades se filtran automáticamente según el tipo de producto seleccionado.', 'Units are automatically filtered by the selected product type.'),
    ('invUnitOfMeasure', 'Unidad de Medida *', 'Unit of Measure *'),
    ('invStockActual', 'Stock Actual', 'Current Stock'),
    ('invEnterCurrentStock', 'Ingresa el stock actual', 'Enter the current stock'),
    ('invEnterValidNumberStock', 'Ingresa un número válido', 'Enter a valid number'),
    ('invStockMin', 'Stock Mínimo', 'Minimum Stock'),
    ('invStockMax', 'Stock Máximo', 'Maximum Stock'),
    ('invOptional', 'Opcional', 'Optional'),
    ('invStockAlerts', 'Alertas de stock', 'Stock alerts'),
    ('invStockAlertMessage', 'Recibirás una notificación cuando el stock esté por debajo del mínimo configurado.', 'You will receive a notification when stock falls below the configured minimum.'),

    # basic_info_step.dart
    ('invBasicInfo', 'Información Básica', 'Basic Information'),
    ('invEnterMainData', 'Ingresa los datos principales del item', 'Enter the main item data'),
    ('invItemName', 'Nombre del Item', 'Item Name'),
    ('invEnterItemName', 'Ingresa el nombre del item', 'Enter the item name'),
    ('invNameMinChars', 'El nombre debe tener al menos 2 caracteres', 'Name must be at least 2 characters'),
    ('invCodeSkuOptional', 'Código/SKU (opcional)', 'Code/SKU (optional)'),
    ('invDescriptionOptional', 'Descripción (opcional)', 'Description (optional)'),
    ('invDescribeProductCharacteristics', 'Describe las características del producto...', 'Describe the product features...'),
    ('invSkuHelpsIdentify', 'El código/SKU te ayudará a identificar rápidamente el item en tu inventario.', 'The Code/SKU will help you quickly identify the item in your inventory.'),

    # details_step.dart
    ('invAdditionalDetails', 'Detalles Adicionales', 'Additional Details'),
    ('invOptionalInfoBetterControl', 'Información opcional para mejor control', 'Optional information for better control'),
    ('invUnitPriceLabel', 'Precio Unitario', 'Unit Price'),
    ('invSupplierLabel', 'Proveedor', 'Supplier'),
    ('invSupplierNameHint', 'Nombre del proveedor', 'Supplier name'),
    ('invWarehouseLocation', 'Ubicación en Almacén', 'Warehouse Location'),
    ('invExpirationTitle', 'Vencimiento', 'Expiration'),
    ('invExpirationDateOptional', 'Fecha de vencimiento (opcional)', 'Expiration date (optional)'),
    ('invSelectDate', 'Seleccionar fecha', 'Select date'),
    ('invSupplierBatchLabel', 'Lote del Proveedor', 'Supplier Batch'),
    ('invBatchNumber', 'Número de lote', 'Batch number'),
    ('invDetailsOptionalHelp', 'Estos datos son opcionales pero ayudan a un mejor control y trazabilidad del inventario.', 'This data is optional but helps with better inventory control and traceability.'),

    # tipo_item_step.dart
    ('invWhatTypeOfItem', '¿Qué tipo de item es?', 'What type of item is it?'),
    ('invSelectItemCategory', 'Selecciona la categoría del item de inventario', 'Select the inventory item category'),
    ('invDescAlimento', 'Concentrados, maíz, soya y otros alimentos para aves', 'Concentrates, corn, soy and other poultry feed'),
    ('invDescMedicamento', 'Antibióticos, antiparasitarios y tratamientos veterinarios', 'Antibiotics, antiparasitics and veterinary treatments'),
    ('invDescVacuna', 'Vacunas y productos de inmunización', 'Vaccines and immunization products'),
    ('invDescEquipo', 'Bebederos, comederos, equipos de calefacción y herramientas', 'Drinkers, feeders, heating equipment and tools'),
    ('invDescInsumo', 'Materiales de cama, desinfectantes y otros insumos', 'Bedding materials, disinfectants and other supplies'),
    ('invDescLimpieza', 'Productos de limpieza y desinfección', 'Cleaning and disinfection products'),
    ('invDescOtro', 'Otros items que no encajan en las categorías anteriores', "Other items that don't fit previous categories"),

    # imagen_producto_section.dart
    ('invProductImage', 'Imagen del Producto', 'Product Image'),
    ('invTakePhoto', 'Tomar Foto', 'Take Photo'),
    ('invGallery', 'Galería', 'Gallery'),
    ('invImageSelectedLabel', 'Imagen seleccionada', 'Image selected'),
    ('invReady', 'Lista', 'Ready'),
    ('invNoImageAdded', 'No hay imagen agregada', 'No image added'),
    ('invCanAddProductPhoto', 'Puedes agregar una foto del producto', 'You can add a product photo'),

    # movimiento_inventario_card.dart
    ('invStockBefore', 'Stock anterior', 'Previous stock'),
    ('invStockAfter', 'Stock nuevo', 'New stock'),

    # stock_indicator.dart
    ('invInventoryLabel', 'Inventario', 'Inventory'),
    ('invItemsRegistered', 'items registrados', 'items registered'),
    ('invViewAllItems', 'Ver todo', 'View all'),
    ('invTotalItems', 'Total Items', 'Total Items'),
    ('invLowStock', 'Stock Bajo', 'Low Stock'),
    ('invDepletedItems', 'Agotados', 'Depleted'),
    ('invExpiringSoon', 'Por Vencer', 'Expiring Soon'),

    # ═════════════════════════════════════════════════════════════
    #  SALUD
    # ═════════════════════════════════════════════════════════════
    # salud_list_page.dart
    ('saludFilterAll', 'Todos', 'All'),
    ('saludFilterInTreatment', 'En tratamiento', 'In treatment'),
    ('saludFilterClosed', 'Cerrados', 'Closed'),
    ('saludRecordsTitle', 'Registros de Salud', 'Health Records'),
    ('saludFilterTooltip', 'Filtrar', 'Filter'),
    ('saludEmptyTitle', 'Sin registros de salud', 'No health records'),
    ('saludEmptyDescription', 'Registra tratamientos, diagnósticos y seguimiento sanitario del lote', 'Register treatments, diagnoses and health monitoring for the batch'),
    ('saludRegisterTreatment', 'Registrar Tratamiento', 'Register Treatment'),
    ('saludNoRecordsFound', 'No se encontraron registros', 'No records found'),
    ('saludNoFilterResults', 'No hay registros que coincidan con los filtros aplicados', 'No records match the applied filters'),
    ('saludFilterByBatch', 'Filtrar por lote', 'Filter by batch'),
    ('saludNewTreatment', 'Nuevo Tratamiento', 'New Treatment'),
    ('saludNewTreatmentTooltip', 'Registrar nuevo tratamiento', 'Register new treatment'),
    ('saludFilterRecords', 'Filtrar registros', 'Filter records'),
    ('saludTreatmentStatus', 'Estado del tratamiento', 'Treatment status'),
    ('saludDeleteRecordTitle', '¿Eliminar registro?', 'Delete record?'),
    ('saludRecordDeleted', 'Registro eliminado correctamente', 'Record deleted successfully'),
    ('saludCloseTreatmentTitle', 'Cerrar Tratamiento', 'Close Treatment'),
    ('saludDescribeResult', 'Describe el resultado del tratamiento aplicado', 'Describe the result of the applied treatment'),
    ('saludResultRequired', 'Resultado *', 'Result *'),
    ('saludResultHint', 'Ej: Recuperación completa, sin síntomas', 'E.g.: Complete recovery, no symptoms'),
    ('saludResultValidation', 'El resultado es obligatorio', 'Result is required'),
    ('saludResultMinLength', 'Describe el resultado (mínimo 10 caracteres)', 'Describe the result (minimum 10 characters)'),
    ('saludFinalObservations', 'Observaciones finales', 'Final observations'),
    ('saludAdditionalNotesOptional', 'Notas adicionales (opcional)', 'Additional notes (optional)'),
    ('saludTreatmentClosedSuccess', 'Tratamiento cerrado exitosamente', 'Treatment closed successfully'),
    ('saludStatusInTreatment', 'En tratamiento', 'In treatment'),
    ('saludStatusClosed', 'Cerrado', 'Closed'),
    ('saludDiagnosis', 'Diagnóstico', 'Diagnosis'),
    ('saludSymptoms', 'Síntomas', 'Symptoms'),
    ('saludTreatment', 'Tratamiento', 'Treatment'),
    ('saludMedications', 'Medicamentos', 'Medications'),
    ('saludDosage', 'Dosis', 'Dosage'),
    ('saludDuration', 'Duración', 'Duration'),
    ('saludDays', 'días', 'days'),
    ('saludVeterinarian', 'Veterinario', 'Veterinarian'),
    ('saludResult', 'Resultado', 'Result'),
    ('saludCloseDate', 'Fecha de cierre', 'Close date'),
    ('saludTreatmentDays', 'Días de tratamiento', 'Treatment days'),
    ('saludAllBatches', 'Todos', 'All'),

    # salud_detail_page.dart
    ('saludDetailTitle', 'Detalle de Registro', 'Record Detail'),
    ('saludRecordNotFound', 'Registro no encontrado', 'Record not found'),
    ('saludLoadError', 'No pudimos cargar el registro de salud', 'We could not load the health record'),
    ('saludDetailStatusClosed', 'Cerrado', 'Closed'),
    ('saludDetailStatusInTreatment', 'En tratamiento', 'In treatment'),
    ('saludDetailDiagnosisSection', 'Diagnóstico', 'Diagnosis'),
    ('saludDetailDateLabel', 'Fecha', 'Date'),
    ('saludDetailTreatmentSection', 'Tratamiento', 'Treatment'),
    ('saludDetailUser', 'Usuario', 'User'),
    ('saludDetailCloseTreatment', 'Cerrar Tratamiento', 'Close Treatment'),
    ('saludDetailCloseDate', 'Fecha de Cierre', 'Close Date'),
    ('saludDetailResultOptional', 'Resultado (Opcional)', 'Result (Optional)'),
    ('saludDetailDescribeResult', 'Describe el resultado del tratamiento', 'Describe the treatment result'),
    ('saludDetailDeleteTitle', '¿Eliminar registro?', 'Delete record?'),
    ('saludDetailRecordDeleted', 'Registro eliminado', 'Record deleted'),
    ('saludDetailTreatmentClosed', 'Tratamiento cerrado', 'Treatment closed'),
    ('saludDetailCloseError', 'Error al cerrar tratamiento', 'Error closing treatment'),
    ('saludDetailDeleteError', 'Error al eliminar registro', 'Error deleting record'),

    # vacunacion_list_page.dart
    ('vacFilterAll', 'Todos', 'All'),
    ('vacFilterApplied', 'Aplicadas', 'Applied'),
    ('vacFilterPending', 'Pendientes', 'Pending'),
    ('vacFilterExpired', 'Vencidas', 'Expired'),
    ('vacFilterUpcoming', 'Próximas', 'Upcoming'),
    ('vacTitle', 'Vacunaciones', 'Vaccinations'),
    ('vacFilterTooltip', 'Filtrar', 'Filter'),
    ('vacEmptyTitle', 'No hay vacunaciones programadas', 'No vaccinations scheduled'),
    ('vacEmptyDescription', 'Programa las vacunas para mantener la salud del lote', 'Schedule vaccines to maintain batch health'),
    ('vacScheduleVaccination', 'Programar Vacunación', 'Schedule Vaccination'),
    ('vacNoResults', 'Sin resultados', 'No results'),
    ('vacNoFilterResults', 'No se encontraron vacunaciones con los filtros aplicados', 'No vaccinations found with the applied filters'),
    ('vacSchedule', 'Programar', 'Schedule'),
    ('vacScheduleTooltip', 'Programar nueva vacunación', 'Schedule new vaccination'),
    ('vacNoFarmSelected', 'No hay granja seleccionada', 'No farm selected'),
    ('vacNoFarmDescription', 'Selecciona una granja desde el menú principal para ver las vacunaciones programadas.', 'Select a farm from the main menu to view scheduled vaccinations.'),
    ('vacGoHome', 'Ir al inicio', 'Go to home'),
    ('vacFilterTitle', 'Filtrar vacunaciones', 'Filter vaccinations'),
    ('vacVaccinationStatus', 'Estado de vacunación', 'Vaccination status'),
    ('vacAllStatuses', 'Todos los estados', 'All statuses'),
    ('vacDeleteTitle', '¿Eliminar vacunación?', 'Delete vaccination?'),
    ('vacDeleted', 'Vacunación eliminada correctamente', 'Vaccination deleted successfully'),
    ('vacMarkAppliedTitle', 'Marcar como Aplicada', 'Mark as Applied'),
    ('vacApplicationDetails', 'Registra los detalles de la aplicación', 'Register the application details'),
    ('vacAgeWeeksRequired', 'Edad (semanas) *', 'Age (weeks) *'),
    ('vacAgeRequired', 'La edad es obligatoria', 'Age is required'),
    ('vacAgeInvalid', 'La edad debe ser un número mayor a 0', 'Age must be a number greater than 0'),
    ('vacDosisRequired', 'Dosis *', 'Dosage *'),
    ('vacDosisValidation', 'La dosis es obligatoria', 'Dosage is required'),
    ('vacRouteRequired', 'Vía de aplicación *', 'Application route *'),
    ('vacRouteValidation', 'La vía es obligatoria', 'Route is required'),
    ('vacMarkedApplied', 'Vacuna marcada como aplicada', 'Vaccine marked as applied'),
    ('vacSheetApplied', 'Aplicada', 'Applied'),
    ('vacSheetExpired', 'Vencida', 'Expired'),
    ('vacSheetUpcoming', 'Próxima', 'Upcoming'),
    ('vacSheetPending', 'Pendiente', 'Pending'),
    ('vacVaccine', 'Vacuna', 'Vaccine'),
    ('vacScheduledDate', 'Fecha programada', 'Scheduled date'),
    ('vacApplicationDate', 'Fecha aplicación', 'Application date'),
    ('vacAgeApplication', 'Edad aplicación', 'Application age'),
    ('vacWeeks', 'semanas', 'weeks'),
    ('vacDosis', 'Dosis', 'Dosage'),
    ('vacRoute', 'Vía', 'Route'),
    ('vacLaboratory', 'Laboratorio', 'Laboratory'),
    ('vacVaccineBatch', 'Lote vacuna', 'Vaccine batch'),
    ('vacResponsible', 'Responsable', 'Responsible'),
    ('vacNextApplication', 'Próxima aplicación', 'Next application'),
    ('vacScheduledBy', 'Programado por', 'Scheduled by'),
    ('vacMarkAppliedButton', 'Marcar Aplicada', 'Mark Applied'),
    ('vacDeleteButton', 'Eliminar', 'Delete'),

    # vacunacion_detail_page.dart
    ('vacDetailTitle', 'Detalle de Vacunación', 'Vaccination Detail'),
    ('vacDetailNotFound', 'Vacunación no encontrada', 'Vaccination not found'),
    ('vacDetailLoadError', 'No pudimos cargar la vacunación', 'We could not load the vaccination'),
    ('vacDetailStatusApplied', 'Aplicada', 'Applied'),
    ('vacDetailStatusExpired', 'Vencida', 'Expired'),
    ('vacDetailStatusUpcoming', 'Próxima', 'Upcoming'),
    ('vacDetailStatusPending', 'Pendiente', 'Pending'),
    ('vacDetailVaccineInfo', 'Información de la Vacuna', 'Vaccine Information'),
    ('vacDetailScheduledDate', 'Fecha Programada', 'Scheduled Date'),
    ('vacDetailAgeApplication', 'Edad Aplicación', 'Application Age'),
    ('vacDetailVaccineBatch', 'Lote Vacuna', 'Vaccine Batch'),
    ('vacDetailNextApplication', 'Próxima Aplicación', 'Next Application'),
    ('vacDetailMarkAppliedButton', 'Marcar como Aplicada', 'Mark as Applied'),
    ('vacDetailSelectDate', 'Selecciona la fecha de aplicación', 'Select the application date'),
    ('vacDetailMarkedApplied', 'Vacunación marcada como aplicada', 'Vaccination marked as applied'),
    ('vacDetailMarkError', 'Error al marcar vacunación', 'Error marking vaccination'),
    ('vacDetailDeleteTitle', '¿Eliminar vacunación?', 'Delete vaccination?'),
    ('vacDetailDeleted', 'Vacunación eliminada', 'Vaccination deleted'),
    ('vacDetailDeleteError', 'Error al eliminar vacunación', 'Error deleting vaccination'),

    # registrar_tratamiento_page.dart
    ('treatFormStepLocation', 'Ubicación', 'Location'),
    ('treatFormStepLocationDesc', 'Selecciona granja y lote', 'Select farm and batch'),
    ('treatFormStepDiagnosis', 'Diagnóstico', 'Diagnosis'),
    ('treatFormStepDiagnosisDesc', 'Información del diagnóstico y síntomas', 'Diagnosis and symptoms information'),
    ('treatFormStepTreatment', 'Tratamiento', 'Treatment'),
    ('treatFormStepTreatmentDesc', 'Detalles del tratamiento y medicamentos', 'Treatment and medication details'),
    ('treatFormStepInfo', 'Información', 'Information'),
    ('treatFormStepInfoDesc', 'Veterinario y observaciones adicionales', 'Veterinarian and additional observations'),
    ('treatDraftFoundMessage', '¿Deseas restaurar el borrador del tratamiento guardado anteriormente?', 'Do you want to restore the previously saved treatment draft?'),
    ('treatSavedMomentAgo', 'Guardado hace un momento', 'Saved a moment ago'),
    ('treatExit', 'Salir', 'Leave'),
    ('treatNewTitle', 'Nuevo Tratamiento', 'New Treatment'),
    ('treatSelectFarmBatch', 'Por favor selecciona una granja y un lote', 'Please select a farm and a batch'),
    ('treatDurationRange', 'La duración debe ser entre 1 y 365 días', 'Duration must be between 1 and 365 days'),
    ('treatFutureDate', 'La fecha no puede ser futura', 'Date cannot be in the future'),
    ('treatCompleteRequired', 'Por favor completa los campos obligatorios', 'Please complete the required fields'),
    ('treatRegisteredSuccess', 'Tratamiento registrado exitosamente', 'Treatment registered successfully'),
    ('treatRegisteredInventoryError', 'Tratamiento registrado, pero hubo un error al actualizar inventario', 'Treatment registered, but there was an error updating inventory'),
    ('treatRegisterError', 'Error al registrar tratamiento', 'Error registering treatment'),

    # programar_vacunacion_page.dart
    ('vacFormStepVaccine', 'Vacuna', 'Vaccine'),
    ('vacFormStepApplication', 'Aplicación', 'Application'),
    ('vacFormTitle', 'Programar Vacunación', 'Schedule Vaccination'),
    ('vacFormSubmit', 'Programar Vacunación', 'Schedule Vaccination'),
    ('vacFormDraftFound', 'Borrador encontrado', 'Draft found'),
    ('vacFormSelectBatch', 'Debes seleccionar un lote', 'You must select a batch'),
    ('vacFormSuccess', '¡Vacunación programada exitosamente!', 'Vaccination scheduled successfully!'),
    ('vacFormInventoryError', 'Vacunación registrada, pero hubo un error al descontar inventario', 'Vaccination registered, but there was an error deducting inventory'),
    ('vacFormError', 'Error al programar vacunación', 'Error scheduling vaccination'),
    ('vacFormScheduleError', 'Error al programar', 'Error scheduling'),

    # catalogo_enfermedades_page.dart
    ('diseaseCatalogTitle', 'Catálogo de Enfermedades', 'Disease Catalog'),
    ('diseaseCatalogSearchHint', 'Buscar enfermedad, síntoma...', 'Search disease, symptom...'),
    ('diseaseCatalogAll', 'Todas', 'All'),
    ('diseaseCatalogCritical', 'Crítica', 'Critical'),
    ('diseaseCatalogSevere', 'Grave', 'Severe'),
    ('diseaseCatalogModerate', 'Moderada', 'Moderate'),
    ('diseaseCatalogMild', 'Leve', 'Mild'),
    ('diseaseCatalogMandatoryNotification', 'Notificación obligatoria', 'Mandatory notification'),
    ('diseaseCatalogVaccinable', 'Vacunable', 'Vaccinable'),
    ('diseaseCatalogCategory', 'Categoría', 'Category'),
    ('diseaseCatalogSymptoms', 'Síntomas', 'Symptoms'),
    ('diseaseCatalogSeverity', 'Gravedad', 'Severity'),
    ('diseaseCatalogViewDetails', 'Ver Detalles', 'View Details'),
    ('diseaseCatalogNoResults', 'No se encontraron enfermedades', 'No diseases found'),
    ('diseaseCatalogEmpty', 'Catálogo vacío', 'Empty catalog'),
    ('diseaseCatalogTryOther', 'Intenta con otros términos de búsqueda o filtros', 'Try other search terms or filters'),
    ('diseaseCatalogNoneRegistered', 'No hay enfermedades registradas', 'No diseases registered'),
    ('diseaseCatalogClearFilters', 'Limpiar filtros', 'Clear filters'),

    # bioseguridad_overview_page.dart
    ('bioOverviewTitle', 'Bioseguridad', 'Biosecurity'),
    ('bioNewInspection', 'Nueva Inspección', 'New Inspection'),
    ('bioNewInspectionTooltip', 'Crear nueva inspección', 'Create new inspection'),
    ('bioEmptyTitle', 'Todavía no hay inspecciones registradas', 'No inspections registered yet'),
    ('bioMetricInspections', 'Inspecciones', 'Inspections'),
    ('bioMetricAverage', 'Promedio', 'Average'),
    ('bioMetricCritical', 'Críticas', 'Critical'),
    ('bioMetricLastLevel', 'Último nivel', 'Last level'),
    ('bioRecentHistory', 'Historial reciente', 'Recent history'),
    ('bioGeneralInspection', 'Inspección general', 'General inspection'),
    ('bioShedInspection', 'Inspección por galpón', 'Shed inspection'),
    ('bioScore', 'Puntaje', 'Score'),
    ('bioNonCompliant', 'No cumple', 'Non-compliant'),
    ('bioPending', 'Pendientes', 'Pending'),
    ('bioLoadError', 'No se pudo cargar bioseguridad', 'Could not load biosecurity'),
    ('bioNoInspectionYet', 'Aún no hay una inspección completada.', 'No inspection completed yet.'),
    ('bioLastInspection', 'Última inspección:', 'Last inspection:'),

    # inspeccion_bioseguridad_page.dart
    ('bioInspectionTitle', 'Inspección de Bioseguridad', 'Biosecurity Inspection'),
    ('bioInspectionNewTitle', 'Nueva Inspección', 'New Inspection'),
    ('bioInspectionStepLocation', 'Ubicación', 'Location'),
    ('bioInspectionStepChecklist', 'Checklist', 'Checklist'),
    ('bioInspectionStepSummary', 'Resumen', 'Summary'),
    ('bioInspectionSave', 'Guardar Inspección', 'Save Inspection'),
    ('bioInspectionLoadError', 'Error al cargar datos', 'Error loading data'),
    ('bioInspectionExitTitle', '¿Salir sin completar?', 'Leave without completing?'),
    ('bioInspectionExitMessage', 'Tienes una inspección en progreso. Si sales ahora, perderás los cambios.', "You have an inspection in progress. If you leave now, you'll lose the changes."),
    ('bioInspectionSaveMessage', 'Se guardará la inspección y se generará el reporte correspondiente.', 'The inspection will be saved and the corresponding report will be generated.'),
    ('bioInspectionSaveSuccess', 'Inspección guardada exitosamente', 'Inspection saved successfully'),
    ('bioInspectionLoadingFarm', 'Cargando granja…', 'Loading farm…'),
    ('bioInspectionMinProgress', 'Evalúa al menos el 50% de los items para continuar', 'Evaluate at least 50% of items to continue'),

    # salud_resumen_card.dart
    ('saludSummaryTitle', 'Resumen de Salud', 'Health Summary'),
    ('saludAllUnderControl', 'Todo bajo control', 'Everything under control'),
    ('saludHealthStatus', 'Estado sanitario', 'Health status'),
    ('saludActive', 'Activos', 'Active'),
    ('saludClosedCount', 'Cerrados', 'Closed'),

    # salud_list_card.dart
    ('saludCardActive', 'Activo', 'Active'),
    ('saludCardClosed', 'Cerrado', 'Closed'),
    ('saludCardDiagnosisPrefix', 'Diagnóstico: ', 'Diagnosis: '),
    ('saludCardTreatmentPrefix', 'Tratamiento: ', 'Treatment: '),

    # salud_error_state.dart
    ('saludErrorTitle', 'Error al cargar registros', 'Error loading records'),

    # vacunacion_resumen_card.dart
    ('vacSummaryTitle', 'Resumen de Vacunación', 'Vaccination Summary'),
    ('vacSummaryExpiredWarning', '¡Atención! Hay vacunas vencidas', 'Attention! There are expired vaccines'),
    ('vacSummaryUpcomingWarning', 'Hay vacunas próximas a aplicar', 'There are upcoming vaccines to apply'),
    ('vacSummaryUpToDate', 'Vacunaciones al día', 'Vaccinations up to date'),
    ('vacSummaryAllApplied', 'Todas las vacunas aplicadas', 'All vaccines applied'),
    ('vacSummaryApplied', 'Aplicadas', 'Applied'),

    # vacunacion_list_card.dart
    ('vacCardStatusApplied', 'Aplicada', 'Applied'),
    ('vacCardStatusExpired', 'Vencida', 'Expired'),
    ('vacCardStatusUpcoming', 'Próxima', 'Upcoming'),
    ('vacCardStatusPending', 'Pendiente', 'Pending'),
    ('vacCardVaccinePrefix', 'Vacuna: ', 'Vaccine: '),
    ('vacCardDosisPrefix', 'Dosis: ', 'Dosage: '),
    ('vacCardRoutePrefix', 'Vía: ', 'Route: '),
    ('vacCardExpiredAgo', 'Vencida hace: ', 'Expired ago: '),
    ('vacCardDaysLeft', 'Faltan: ', 'Remaining: '),

    # vacunacion_error_state.dart
    ('vacErrorTitle', 'Error al cargar vacunaciones', 'Error loading vaccinations'),

    # vacuna_info_step.dart
    ('vacStepVaccineInfoTitle', 'Información de la Vacuna', 'Vaccine Information'),
    ('vacStepVaccineInfoDesc', 'Ingresa los datos de la vacuna a programar', 'Enter the data for the vaccine to schedule'),
    ('vacStepBatchRequired', 'Lote *', 'Batch *'),
    ('vacStepSelectBatch', 'Selecciona un lote', 'Select a batch'),
    ('vacStepSelectFromInventory', 'Seleccionar del inventario', 'Select from inventory'),
    ('vacStepSelectVaccineInventory', 'Seleccionar vacuna del inventario', 'Select vaccine from inventory'),
    ('vacStepOptionalSelectVaccine', 'Opcional - Selecciona una vacuna registrada', 'Optional - Select a registered vaccine'),
    ('vacStepInventoryNote', 'Si seleccionas del inventario, el stock se descontará automáticamente.', 'If you select from inventory, stock will be automatically deducted.'),
    ('vacStepVaccineName', 'Nombre de la vacuna', 'Vaccine name'),
    ('vacStepVaccineNameHint', 'Ej: Newcastle + Bronquitis', 'E.g.: Newcastle + Bronchitis'),
    ('vacStepVaccineNameRequired', 'Ingresa el nombre de la vacuna', 'Enter the vaccine name'),
    ('vacStepVaccineNameMinLength', 'El nombre debe tener al menos 3 caracteres', 'Name must have at least 3 characters'),
    ('vacStepVaccineBatch', 'Lote de la vacuna (opcional)', 'Vaccine batch (optional)'),
    ('vacStepVaccineBatchHint', 'Ej: LOT123456', 'E.g.: LOT123456'),
    ('vacStepScheduledDate', 'Fecha programada *', 'Scheduled date *'),
    ('vacStepTipTitle', 'Consejo', 'Tip'),
    ('vacStepTipMessage', 'Programa las vacunaciones con anticipación para mantener el calendario sanitario al día.', 'Schedule vaccinations in advance to keep the health calendar up to date.'),

    # aplicacion_observaciones_step.dart
    ('vacStepAppObsTitle', 'Aplicación y Observaciones', 'Application and Observations'),
    ('vacStepAppObsDesc', 'Registra cuándo se aplicó y añade observaciones', 'Record when it was applied and add observations'),
    ('vacStepAppDateOptional', 'Fecha de aplicación (opcional)', 'Application date (optional)'),
    ('vacStepSelectDate', 'Seleccionar fecha', 'Select date'),
    ('vacStepRemoveDate', 'Quitar fecha', 'Remove date'),
    ('vacStepObservationsOptional', 'Observaciones (opcional)', 'Observations (optional)'),
    ('vacStepObservationsHint', 'Reacciones observadas, notas especiales, etc.', 'Observed reactions, special notes, etc.'),
    ('vacStepVaccineApplied', 'Vacuna aplicada', 'Vaccine applied'),
    ('vacStepAppliedNote', 'La vacunación quedará registrada como aplicada.', 'The vaccination will be registered as applied.'),
    ('vacStepScheduled', 'Vacunación programada', 'Vaccination scheduled'),
    ('vacStepScheduledNote', 'Quedará pendiente. Podrás marcarla como aplicada más tarde.', 'It will remain pending. You can mark it as applied later.'),
    ('vacStepCalendarReminder', 'Las vacunaciones programadas aparecerán en tu calendario y recibirás recordatorios.', 'Scheduled vaccinations will appear in your calendar and you will receive reminders.'),

    # diagnostico_info_step.dart
    ('treatStepDiagTitle', 'Diagnóstico y Síntomas', 'Diagnosis and Symptoms'),
    ('treatStepDiagDesc', 'Registra el diagnóstico y los síntomas observados en las aves', 'Record the diagnosis and symptoms observed in the birds'),
    ('treatStepDiagImportant', 'Información importante', 'Important information'),
    ('treatStepDiagImportantMsg', 'Un diagnóstico preciso permite seleccionar el tratamiento más efectivo y prevenir la propagación.', 'An accurate diagnosis allows selecting the most effective treatment and preventing spread.'),
    ('treatStepDateRequired', 'Fecha del tratamiento *', 'Treatment date *'),
    ('treatStepDiagnosisHint', 'Ej: Enfermedad respiratoria crónica', 'E.g.: Chronic respiratory disease'),
    ('treatStepDiagRequired', 'El diagnóstico es obligatorio', 'Diagnosis is required'),
    ('treatStepDiagMinLength', 'Debe tener al menos 5 caracteres', 'Must have at least 5 characters'),
    ('treatStepSymptoms', 'Síntomas observados', 'Observed symptoms'),
    ('treatStepSymptomsHint', 'Describe los síntomas: tos, estornudos, decaimiento...', 'Describe symptoms: cough, sneezing, lethargy...'),

    # tratamiento_detalles_step.dart
    ('treatStepDetailsTitle', 'Detalles del Tratamiento', 'Treatment Details'),
    ('treatStepDetailsDesc', 'Describe el tratamiento aplicado y los medicamentos', 'Describe the applied treatment and medications'),
    ('treatStepDetailsImportant', 'Información importante', 'Important information'),
    ('treatStepDetailsImportantMsg', 'Si seleccionas un medicamento del inventario, el stock se descontará automáticamente al guardar.', 'If you select a medication from inventory, stock will be automatically deducted on save.'),
    ('treatStepTreatmentDesc', 'Descripción del tratamiento', 'Treatment description'),
    ('treatStepTreatmentHint', 'Describe el protocolo de tratamiento aplicado', 'Describe the applied treatment protocol'),
    ('treatStepTreatmentRequired', 'El tratamiento es obligatorio', 'Treatment is required'),
    ('treatStepTreatmentMinLength', 'Debe tener al menos 5 caracteres', 'Must have at least 5 characters'),
    ('treatStepInventoryMed', 'Medicamento del inventario (opcional)', 'Medication from inventory (optional)'),
    ('treatStepSelectMed', 'Seleccionar medicamento del inventario...', 'Select medication from inventory...'),
    ('treatStepAutoDeduct', 'Se descontará automáticamente del inventario', 'Will be automatically deducted from inventory'),
    ('treatStepMedications', 'Medicamentos', 'Medications'),
    ('treatStepMedicationsHint', 'Ej: Enrofloxacina + Vitaminas A, D, E', 'E.g.: Enrofloxacin + Vitamins A, D, E'),
    ('treatStepDosis', 'Dosis', 'Dosage'),
    ('treatStepDosisHint', 'Ej: 1ml/L', 'E.g.: 1ml/L'),
    ('treatStepDuration', 'Duración (días)', 'Duration (days)'),
    ('treatStepDurationHint', 'Ej: 5', 'E.g.: 5'),
    ('treatStepDurationMin', 'Debe ser > 0', 'Must be > 0'),
    ('treatStepDurationMax', 'Máximo 365', 'Maximum 365'),

    # seleccion_granja_lote_step.dart
    ('treatStepSelectLocationTitle', 'Seleccionar Ubicación', 'Select Location'),
    ('treatStepSelectBatchTitle', 'Seleccionar Lote', 'Select Batch'),
    ('treatStepSelectLocationDesc', 'Selecciona la granja y el lote para registrar el tratamiento', 'Select the farm and batch to register the treatment'),
    ('treatStepSelectBatchDesc', 'Selecciona el lote para registrar el tratamiento', 'Select the batch to register the treatment'),
    ('treatStepSelectBatchSubDesc', 'Selecciona el lote donde se aplicará el tratamiento', 'Select the batch where the treatment will be applied'),
    ('treatStepNoFarms', 'No tienes granjas registradas', 'You have no registered farms'),
    ('treatStepNoFarmsDesc', 'Debes crear una granja antes de registrar un tratamiento', 'You must create a farm before registering a treatment'),
    ('treatStepFarmsError', 'Error al cargar granjas', 'Error loading farms'),
    ('treatStepFarmRequired', 'Granja *', 'Farm *'),
    ('treatStepSelectFarm', 'Selecciona una granja', 'Select a farm'),
    ('treatStepFarmValidation', 'Por favor selecciona una granja', 'Please select a farm'),
    ('treatStepBatchRequired', 'Lote *', 'Batch *'),
    ('treatStepSelectBatch', 'Selecciona un lote', 'Select a batch'),
    ('treatStepBatchValidation', 'Por favor selecciona un lote', 'Please select a batch'),
    ('treatStepNoActiveBatches', 'No hay lotes activos', 'No active batches'),
    ('treatStepNoActiveBatchesDesc', 'Esta granja no tiene lotes activos para registrar tratamientos', 'This farm has no active batches to register treatments'),
    ('treatStepBatchesError', 'Error al cargar lotes', 'Error loading batches'),

    # informacion_adicional_step.dart
    ('treatStepAdditionalTitle', 'Información Adicional', 'Additional Information'),
    ('treatStepAdditionalDesc', 'Datos complementarios del tratamiento', 'Supplementary treatment data'),
    ('treatStepAdditionalImportant', 'Información importante', 'Important information'),
    ('treatStepAdditionalImportantMsg', 'Estos campos son opcionales pero ayudan a un mejor seguimiento del tratamiento.', 'These fields are optional but help with better treatment monitoring.'),
    ('treatStepVeterinarian', 'Veterinario responsable', 'Responsible veterinarian'),
    ('treatStepVetName', 'Nombre del veterinario', 'Veterinarian name'),
    ('treatStepGeneralObs', 'Observaciones generales', 'General observations'),
    ('treatStepGeneralObsHint', 'Notas adicionales, evolución esperada, etc.', 'Additional notes, expected evolution, etc.'),

    # granja_galpon_step.dart
    ('bioStepLocationTitle', '¿Dónde se realizará la inspección?', 'Where will the inspection take place?'),
    ('bioStepLocationDesc', 'Selecciona el galpón o deja en blanco para una inspección general.', 'Select the shed or leave blank for a general inspection.'),
    ('bioStepInspector', 'Inspector', 'Inspector'),
    ('bioStepDate', 'Fecha', 'Date'),
    ('bioStepShed', 'Galpón', 'Shed'),
    ('bioStepShedOptional', 'Opcional — si no seleccionas, la inspección aplica a toda la granja.', "Optional — if you don't select, inspection applies to the entire farm."),
    ('bioStepLoadingFarm', 'Cargando granja…', 'Loading farm…'),
    ('bioStepNoSheds', 'No hay galpones registrados. Se realizará inspección general.', 'No sheds registered. A general inspection will be performed.'),
    ('bioStepWholeFarm', 'Toda la granja', 'Whole farm'),

    # checklist_bioseguridad_step.dart
    ('bioChecklistCritical', 'Crítico', 'Critical'),
    ('bioChecklistTapToEvaluate', 'Toca para evaluar', 'Tap to evaluate'),
    ('bioChecklistCompliant', 'Cumple', 'Compliant'),
    ('bioChecklistNonCompliant', 'No cumple', 'Non-compliant'),
    ('bioChecklistPartial', 'Parcial', 'Partial'),
    ('bioChecklistNotApplicable', 'No aplica', 'Not applicable'),
    ('bioChecklistPending', 'Pendiente', 'Pending'),
    ('bioChecklistSelectResult', 'Selecciona el resultado de la evaluación', 'Select the evaluation result'),
    ('bioChecklistObservation', 'Observación', 'Observation'),
    ('bioChecklistObservationHint', 'Escribe una observación (opcional)', 'Write an observation (optional)'),

    # observaciones_firma_step.dart
    ('bioSummaryTitle', 'Resumen de la inspección', 'Inspection summary'),
    ('bioSummarySubtitle', 'Revisa los resultados antes de guardar.', 'Review the results before saving.'),
    ('bioSummaryCumple', 'Cumple', 'Compliant'),
    ('bioSummaryParcial', 'Parcial', 'Partial'),
    ('bioSummaryNoCumple', 'No cumple', 'Non-compliant'),
    ('bioSummaryCriticalItems', 'Items críticos sin cumplir', 'Critical items not met'),
    ('bioSummaryPendingNote', 'Puedes guardar, pero el puntaje solo refleja lo evaluado.', 'You can save, but the score only reflects what was evaluated.'),
    ('bioSummaryGeneralObs', 'Observaciones generales', 'General observations'),
    ('bioSummaryGeneralObsHint', 'Describe hallazgos generales de la inspección…', 'Describe general findings of the inspection…'),
    ('bioSummaryCorrectiveActions', 'Acciones correctivas', 'Corrective actions'),
    ('bioSummaryCorrectiveHint', 'Describe las acciones a implementar…', 'Describe the actions to implement…'),
    ('bioSummaryRecommended', 'Recomendado', 'Recommended'),
    ('bioSummaryNote', 'Al guardar se generará un reporte descargable y el historial quedará registrado.', 'A downloadable report will be generated and the history recorded.'),
    ('bioRatingExcellent', 'Excelente', 'Excellent'),
    ('bioRatingVeryGood', 'Muy Bueno', 'Very Good'),
    ('bioRatingGood', 'Bueno', 'Good'),
    ('bioRatingAcceptable', 'Aceptable', 'Acceptable'),
    ('bioRatingRegular', 'Regular', 'Regular'),
    ('bioRatingPoor', 'Deficiente', 'Poor'),

    # dialog_helpers.dart
    ('saludDialogCancel', 'Cancelar', 'Cancel'),
    ('saludDialogDelete', 'Eliminar', 'Delete'),
    ('saludDialogContinue', 'Continuar', 'Continue'),
    ('saludDialogConfirm', 'Confirmar', 'Confirm'),
    ('saludDialogAccept', 'Aceptar', 'Accept'),
    ('saludDialogProcessing', 'Procesando...', 'Processing...'),

    # swipeable_card.dart
    ('saludSwipeClose', 'Cerrar', 'Close'),
    ('saludSwipeApply', 'Aplicar', 'Apply'),
    ('saludSwipeDelete', 'Eliminar', 'Delete'),

    # parametrized keys
    ('ventaDeleteMessage', 'Se eliminará la venta de {product}. Esta acción no se puede deshacer.', 'The sale of {product} will be deleted. This action cannot be undone.'),
    ('ventaDeleteError', 'Error al eliminar: {error}', 'Error deleting: {error}'),
    ('ventaDetailsOf', 'Detalles de {product}', 'Details of {product}'),
    ('ventaLotLoadError', 'Error al cargar lotes: {error}', 'Error loading lots: {error}'),
    ('costoDeleteError2', 'Error al eliminar: {error}', 'Error deleting: {error}'),
    ('costoApproveError', 'Error al aprobar: {error}', 'Error approving: {error}'),
    ('costoRejectError', 'Error al rechazar: {error}', 'Error rejecting: {error}'),
    ('saludDeleteRecordMessage', 'Se eliminará el registro "{diagnosis}". Esta acción no se puede deshacer.', 'The record "{diagnosis}" will be deleted. This action cannot be undone.'),
    ('saludActiveTreatments', '{count} tratamiento(s) activo(s)', '{count} active treatment(s)'),
    ('saludCardDays', '{count} días', '{count} days'),
    ('bioEmptyDescription', 'Inicia la primera inspección de bioseguridad para {farmName} y lleva un registro continuo del cumplimiento sanitario.', 'Start the first biosecurity inspection for {farmName} and keep a continuous record of health compliance.'),
    ('bioChecklistProgress', '{evaluated} de {total} evaluados', '{evaluated} of {total} evaluated'),
    ('bioSummaryRisk', 'Riesgo {level} · {evaluated} de {total} evaluados', 'Risk {level} · {evaluated} of {total} evaluated'),
    ('bioSummaryPendingItems', '{count} items pendientes', '{count} pending items'),
    ('vacSummaryExpiredBadge', '{count} vencida(s)', '{count} expired'),
    ('vacSummaryUpcomingBadge', '{count} próxima(s)', '{count} upcoming'),
    ('vacCardAppliedDate', 'Aplicada: {date}', 'Applied: {date}'),
    ('vacCardDays', '{count} días', '{count} days'),
    ('vacDetailScheduled', 'Programada: {date}', 'Scheduled: {date}'),
    ('vacDetailAppliedOn', 'Aplicada el {date}', 'Applied on {date}'),
    ('vacFormDraftMessage', 'Se encontró un borrador guardado del {date}.\n¿Deseas restaurarlo?', 'A saved draft was found from {date}.\nDo you want to restore it?'),
    ('treatSavedMinAgo', 'Guardado hace {count} min', 'Saved {count} min ago'),
    ('treatSavedAtTime', 'Guardado a las {time}', 'Saved at {time}'),
]

# Parametrized keys metadata
PARAM_METADATA = {
    'ventaDeleteMessage': {'placeholders': {'product': {'type': 'String'}}},
    'ventaDeleteError': {'placeholders': {'error': {'type': 'String'}}},
    'ventaDetailsOf': {'placeholders': {'product': {'type': 'String'}}},
    'ventaLotLoadError': {'placeholders': {'error': {'type': 'String'}}},
    'costoDeleteError2': {'placeholders': {'error': {'type': 'String'}}},
    'costoApproveError': {'placeholders': {'error': {'type': 'String'}}},
    'costoRejectError': {'placeholders': {'error': {'type': 'String'}}},
    'saludDeleteRecordMessage': {'placeholders': {'diagnosis': {'type': 'String'}}},
    'saludActiveTreatments': {'placeholders': {'count': {'type': 'int'}}},
    'saludCardDays': {'placeholders': {'count': {'type': 'int'}}},
    'bioEmptyDescription': {'placeholders': {'farmName': {'type': 'String'}}},
    'bioChecklistProgress': {'placeholders': {'evaluated': {'type': 'int'}, 'total': {'type': 'int'}}},
    'bioSummaryRisk': {'placeholders': {'level': {'type': 'String'}, 'evaluated': {'type': 'int'}, 'total': {'type': 'int'}}},
    'bioSummaryPendingItems': {'placeholders': {'count': {'type': 'int'}}},
    'vacSummaryExpiredBadge': {'placeholders': {'count': {'type': 'int'}}},
    'vacSummaryUpcomingBadge': {'placeholders': {'count': {'type': 'int'}}},
    'vacCardAppliedDate': {'placeholders': {'date': {'type': 'String'}}},
    'vacCardDays': {'placeholders': {'count': {'type': 'int'}}},
    'vacDetailScheduled': {'placeholders': {'date': {'type': 'String'}}},
    'vacDetailAppliedOn': {'placeholders': {'date': {'type': 'String'}}},
    'vacFormDraftMessage': {'placeholders': {'date': {'type': 'String'}}},
    'treatSavedMinAgo': {'placeholders': {'count': {'type': 'int'}}},
    'treatSavedAtTime': {'placeholders': {'time': {'type': 'String'}}},
}


def load_arb(path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def save_arb(path, data):
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=4)
        f.write('\n')


def main():
    es_data = load_arb(ES)
    en_data = load_arb(EN)

    added = 0
    skipped = 0

    for key, es_val, en_val in KEYS:
        if key in es_data:
            skipped += 1
            continue
        es_data[key] = es_val
        en_data[key] = en_val
        if key in PARAM_METADATA:
            es_data[f'@{key}'] = PARAM_METADATA[key]
            en_data[f'@{key}'] = PARAM_METADATA[key]
        added += 1

    save_arb(ES, es_data)
    save_arb(EN, en_data)

    print(f'Added {added} new keys, skipped {skipped} existing.')
    print(f'Total ES keys: {sum(1 for k in es_data if not k.startswith("@") and k != "@@locale")}')
    print(f'Total EN keys: {sum(1 for k in en_data if not k.startswith("@") and k != "@@locale")}')


if __name__ == '__main__':
    main()
