"""
Add presentation-layer ARB keys for reportes, notificaciones, perfil, and granjas.
"""
import json

es_path = r'c:\Users\Lenovo\Desktop\smartGranjaAves_pro\lib\l10n\app_es.arb'
en_path = r'c:\Users\Lenovo\Desktop\smartGranjaAves_pro\lib\l10n\app_en.arb'

keys = [
    # === REPORTES ===
    ("reportPageTitle", "Reportes", "Reports"),
    ("reportSelectType", "Selecciona el tipo de reporte", "Select report type"),
    ("reportSelectFarm", "Selecciona una granja", "Select a farm"),
    ("reportSelectFarmHint", "Para generar reportes, primero debes seleccionar una granja desde el inicio.", "To generate reports, you must first select a farm from the home screen."),
    ("reportPeriodPrefix", "Período:", "Period:"),
    ("reportPeriodTitle", "Período del reporte", "Report period"),
    ("reportDateFrom", "Desde", "From"),
    ("reportDateTo", "Hasta", "To"),
    ("reportGenerating", "Generando...", "Generating..."),
    ("reportGeneratePdf", "Generar Reporte PDF", "Generate PDF Report"),
    ("reportNoFarmSelected", "No hay granja seleccionada", "No farm selected"),
    ("reportNoActiveBatches", "No hay lotes activos para generar el reporte", "No active batches to generate the report"),
    ("reportInsufficientData", "No hay datos suficientes para el reporte", "Insufficient data for the report"),
    ("reportGenerateError", "Error al generar reporte", "Error generating report"),
    ("reportGenerated", "Reporte Generado", "Report Generated"),
    ("reportPrint", "Imprimir", "Print"),
    ("reportShareText", "Reporte generado por Smart Granja Aves Pro", "Report generated by Smart Granja Aves Pro"),
    ("reportShareError", "Error al compartir", "Error sharing"),
    ("reportPrintError", "Error al imprimir", "Error printing"),
    ("commonComingSoon", "Próximamente", "Coming soon"),
    ("commonSelected", "Seleccionado", "Selected"),
    ("commonShare", "Compartir", "Share"),

    # === NOTIFICACIONES ===
    ("notifPageTitle", "Notificaciones", "Notifications"),
    ("notifMarkAllRead", "Marcar todas como leídas", "Mark all as read"),
    ("notifDeleteRead", "Eliminar leídas", "Delete read"),
    ("notifLoadError", "Error al cargar notificaciones", "Error loading notifications"),
    ("commonRetry", "Reintentar", "Retry"),
    ("notifAllMarkedRead", "Todas marcadas como leídas", "All marked as read"),
    ("notifDeleteTitle", "Eliminar notificaciones", "Delete notifications"),
    ("notifDeleteReadConfirm", "¿Deseas eliminar todas las notificaciones leídas?", "Do you want to delete all read notifications?"),
    ("commonCancel", "Cancelar", "Cancel"),
    ("commonDelete", "Eliminar", "Delete"),
    ("notifDeleted", "Notificaciones eliminadas", "Notifications deleted"),
    ("notifNoDestination", "Esta notificación no tiene un destino disponible", "This notification has no available destination"),
    ("notifSingleDeleted", "Notificación eliminada", "Notification deleted"),
    ("notifPriorityUrgent", "Urgente", "Urgent"),
    ("notifPriorityHigh", "Alta", "High"),
    ("notifAllCaughtUp", "¡Todo al día!", "All caught up!"),
    ("notifEmptyMessage", "No tienes notificaciones pendientes.\nTe avisaremos cuando haya algo importante.", "You have no pending notifications.\nWe'll let you know when something important comes up."),
    ("notifTooltip", "Notificaciones", "Notifications"),

    # === PERFIL ===
    ("profileEditProfile", "Editar perfil", "Edit profile"),
    ("syncTitle", "Sincronización y Datos", "Sync & Data"),
    ("syncConnectionStatus", "Estado de Conexión", "Connection Status"),
    ("syncPendingData", "Datos pendientes", "Pending data"),
    ("syncChangesPending", "Hay cambios por sincronizar", "There are changes to sync"),
    ("syncAllSynced", "Todo sincronizado", "All synced"),
    ("syncLastSync", "Última sincronización", "Last sync"),
    ("syncCheckConnection", "Verificar conexión", "Check connection"),
    ("syncCompleted", "Sincronización completada", "Sync completed"),
    ("syncForceSync", "Forzar sincronización", "Force sync"),
    ("syncOfflineInfo", "Los datos se guardan automáticamente en tu dispositivo y se sincronizan cuando hay conexión a internet.", "Data is automatically saved to your device and synced when internet connection is available."),
    ("syncJustNow", "Hace un momento", "Just now"),
    ("syncMinutesAgo", "Hace {n} minutos", "{n} minutes ago"),
    ("syncHoursAgo", "Hace {n} horas", "{n} hours ago"),
    ("syncDaysAgo", "Hace {n} días", "{n} days ago"),

    # === GRANJAS ===
    ("commonNotSpecified", "No especificada", "Not specified"),
    ("farmBirds", "aves", "birds"),
    ("farmBroiler", "Engorde", "Broiler"),
    ("farmLayer", "Ponedora", "Layer"),
    ("farmBreeder", "Reproductor", "Breeder"),
    ("farmBird", "Ave", "Bird"),
    ("farmStatusActive", "Activa", "Active"),
    ("farmStatusInactive", "Inactiva", "Inactive"),
    ("farmStatusMaintenance", "Mantenimiento", "Maintenance"),
    ("farmStatusActiveDesc", "Operando normalmente", "Operating normally"),
    ("farmStatusInactiveDesc", "Operaciones suspendidas", "Operations suspended"),
    ("farmStatusMaintenanceDesc", "En proceso de mantenimiento", "Under maintenance"),
    ("formStepBasic", "Básico", "Basic"),
    ("formStepLocation", "Ubicación", "Location"),
    ("formStepContact", "Contacto", "Contact"),
    ("formStepCapacity", "Capacidad", "Capacity"),
    ("farmUpdatedSuccess", "¡Granja actualizada!", "Farm updated!"),
    ("farmCreatedSuccess", "¡Granja creada!", "Farm created!"),
]

# Parametrized keys need @key metadata
parametrized = {
    "syncMinutesAgo": {"placeholders": {"n": {"type": "int"}}},
    "syncHoursAgo": {"placeholders": {"n": {"type": "int"}}},
    "syncDaysAgo": {"placeholders": {"n": {"type": "int"}}},
}

for path, lang in [(es_path, 'es'), (en_path, 'en')]:
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    added = 0
    skipped = 0
    for key, es_val, en_val in keys:
        if key in data:
            skipped += 1
            continue
        data[key] = es_val if lang == 'es' else en_val
        if key in parametrized:
            data[f'@{key}'] = parametrized[key]
        added += 1
    
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(data, f, ensure_ascii=False, indent=4)
        f.write('\n')
    
    print(f'{lang}: Added {added}, Skipped {skipped}, Total {len([k for k in data if not k.startswith("@")])}')

print('Done!')
