$esFile = "c:\Users\Lenovo\Desktop\smartGranjaAves_pro\lib\l10n\app_es.arb"
$enFile = "c:\Users\Lenovo\Desktop\smartGranjaAves_pro\lib\l10n\app_en.arb"

$esContent = Get-Content $esFile -Raw
$enContent = Get-Content $enFile -Raw

$newKeysEs = @'

    "batchTitle": "Lotes",
    "@batchTitle": {},
    "batchDeleteBatch": "Eliminar Lote",
    "@batchDeleteBatch": {},
    "batchFilterTitle": "Filtrar Lotes",
    "@batchFilterTitle": {},
    "batchFilterClear": "Limpiar",
    "@batchFilterClear": {},
    "batchFilterStatus": "Estado",
    "@batchFilterStatus": {},
    "batchFilterAll": "Todos",
    "@batchFilterAll": {},
    "batchFilterBirdType": "Tipo de ave",
    "@batchFilterBirdType": {},
    "batchFilterEntryDate": "Fecha de ingreso",
    "@batchFilterEntryDate": {},
    "batchFilterFrom": "Desde",
    "@batchFilterFrom": {},
    "batchFilterTo": "Hasta",
    "@batchFilterTo": {},
    "batchFilterAny": "Cualquiera",
    "@batchFilterAny": {},
    "batchFilterCancel": "Cancelar",
    "@batchFilterCancel": {},
    "batchFilterApply": "Aplicar",
    "@batchFilterApply": {},
    "batchCloseSummary": "Resumen de Cierre",
    "@batchCloseSummary": {},
    "batchCloseStartDate": "Fecha de inicio",
    "@batchCloseStartDate": {},
    "batchCloseEndDate": "Fecha de cierre",
    "@batchCloseEndDate": {},
    "batchCloseDate": "Fecha de cierre",
    "@batchCloseDate": {},
    "batchCloseDuration": "Duración",
    "@batchCloseDuration": {},
    "batchCloseDays": "días",
    "@batchCloseDays": {},
    "batchCloseCycleDuration": "Duración del ciclo",
    "@batchCloseCycleDuration": {},
    "batchCloseCycleInfo": "Información del ciclo",
    "@batchCloseCycleInfo": {},
    "batchClosePopulation": "Población",
    "@batchClosePopulation": {},
    "batchCloseTotalMortality": "Mortalidad total",
    "@batchCloseTotalMortality": {},
    "batchCloseMortality": "Mortalidad",
    "@batchCloseMortality": {},
    "batchCloseMortalityPercent": "% de mortalidad",
    "@batchCloseMortalityPercent": {},
    "batchCloseFinalMetrics": "Métricas Finales",
    "@batchCloseFinalMetrics": {},
    "batchCloseFinalWeight": "Peso final",
    "@batchCloseFinalWeight": {},
    "batchCloseFinalWeightLabel": "Peso final (kg)",
    "@batchCloseFinalWeightLabel": {},
    "batchCloseWeightGain": "Ganancia de peso",
    "@batchCloseWeightGain": {},
    "batchCloseEstimatedWeight": "Peso estimado",
    "@batchCloseEstimatedWeight": {},
    "batchCloseFeedConversion": "Conversión alimenticia",
    "@batchCloseFeedConversion": {},
    "batchCloseGrams": "gramos",
    "@batchCloseGrams": {},
    "batchCloseWeightRequired": "El peso es requerido",
    "@batchCloseWeightRequired": {},
    "batchCloseWeightMustBePositive": "El peso debe ser positivo",
    "@batchCloseWeightMustBePositive": {},
    "batchCloseWeightTooHigh": "El peso parece demasiado alto",
    "@batchCloseWeightTooHigh": {},
    "batchCloseWeightHelper": "Peso promedio por ave en kg",
    "@batchCloseWeightHelper": {},
    "batchCloseFinalObservations": "Observaciones Finales",
    "@batchCloseFinalObservations": {},
    "batchCloseObservationsHint": "Escriba sus observaciones aquí...",
    "@batchCloseObservationsHint": {},
    "batchCloseIrreversible": "Acción irreversible",
    "@batchCloseIrreversible": {},
    "batchCloseIrreversibleMessage": "Una vez cerrado, el lote no podrá reabrirse",
    "@batchCloseIrreversibleMessage": {},
    "batchCloseConfirm": "Confirmar cierre",
    "@batchCloseConfirm": {},
    "batchCloseSaleInfo": "Información de Venta",
    "@batchCloseSaleInfo": {},
    "batchCloseBirdsToSell": "Aves a vender",
    "@batchCloseBirdsToSell": {},
    "batchCloseBirdsUnit": "aves",
    "@batchCloseBirdsUnit": {},
    "batchCloseSalePriceLabel": "Precio de venta por kg",
    "@batchCloseSalePriceLabel": {},
    "batchCloseSalePriceHelper": "Precio en moneda local",
    "@batchCloseSalePriceHelper": {},
    "batchClosePricePerKg": "Precio por kg",
    "@batchClosePricePerKg": {},
    "batchCloseEstimatedValue": "Valor estimado",
    "@batchCloseEstimatedValue": {},
    "batchCloseBuyerLabel": "Comprador",
    "@batchCloseBuyerLabel": {},
    "batchCloseBuyerHint": "Nombre del comprador (opcional)",
    "@batchCloseBuyerHint": {},
    "batchCloseFinancialBalance": "Balance financiero",
    "@batchCloseFinancialBalance": {},
    "batchCloseTotalIncome": "Ingresos totales",
    "@batchCloseTotalIncome": {},
    "batchCloseTotalExpenses": "Gastos totales",
    "@batchCloseTotalExpenses": {},
    "batchCloseProfitability": "Rentabilidad",
    "@batchCloseProfitability": {},
    "batchCloseEnterValidNumber": "Ingrese un número válido",
    "@batchCloseEnterValidNumber": {},
    "batchFormName": "Nombre del lote",
    "@batchFormName": {},
    "batchFormBasicInfoSubtitle": "Información básica del lote",
    "@batchFormBasicInfoSubtitle": {},
    "batchFormBasicInfoNote": "Complete la información básica del lote",
    "@batchFormBasicInfoNote": {},
    "batchFormDetailsSubtitle": "Detalles adicionales del lote",
    "@batchFormDetailsSubtitle": {},
    "batchFormReviewSubtitle": "Revise la información antes de crear",
    "@batchFormReviewSubtitle": {},
    "batchFormFarm": "Granja",
    "@batchFormFarm": {},
    "batchFormLocation": "Ubicación",
    "@batchFormLocation": {},
    "batchFormShedInfo": "Información del galpón",
    "@batchFormShedInfo": {},
    "batchFormShedLocationInfo": "Ubicación del galpón",
    "@batchFormShedLocationInfo": {},
    "batchFormCapacity": "Capacidad",
    "@batchFormCapacity": {},
    "batchFormMaxCapacity": "Capacidad máxima",
    "@batchFormMaxCapacity": {},
    "batchFormArea": "Área",
    "@batchFormArea": {},
    "batchFormAvailable": "Disponible",
    "@batchFormAvailable": {},
    "batchFormShedCapacity": "Capacidad del galpón",
    "@batchFormShedCapacity": {},
    "batchFormShedCapacityNote": "La cantidad no puede exceder la capacidad",
    "@batchFormShedCapacityNote": {},
    "batchFormExceedsCapacity": "Excede la capacidad del galpón",
    "@batchFormExceedsCapacity": {},
    "batchFormUtilization": "Utilización",
    "@batchFormUtilization": {},
    "batchFormCreateShedFirst": "Cree un galpón primero",
    "@batchFormCreateShedFirst": {},
    "batchFormAgeAtEntry": "Edad al ingreso",
    "@batchFormAgeAtEntry": {},
    "batchFormAgeHint": "Edad en días (opcional)",
    "@batchFormAgeHint": {},
    "batchFormAgeInfoNote": "La edad se calcula automáticamente",
    "@batchFormAgeInfoNote": {},
    "batchFormOptional": "Opcional",
    "@batchFormOptional": {},
    "batchFormNotSelected": "No seleccionado",
    "@batchFormNotSelected": {},
    "batchFormNotSpecified": "No especificado",
    "@batchFormNotSpecified": {},
    "batchFormNotFound": "No encontrado",
    "@batchFormNotFound": {},
    "batchFormUnits": "unidades",
    "@batchFormUnits": {},
    "batchFormDirty": "Sucio",
    "@batchFormDirty": {},
    "batchFormCurrentBirds": "Aves actuales",
    "@batchFormCurrentBirds": {},
    "batchFormInvalidNumber": "Número inválido",
    "@batchFormInvalidNumber": {},
    "batchFormInvalidValue": "Valor inválido",
    "@batchFormInvalidValue": {},
    "batchFormMortalityEventInfo": "Información del evento de mortalidad",
    "@batchFormMortalityEventInfo": {},
    "batchFormMortalityEventSubtitle": "Registre los detalles del evento",
    "@batchFormMortalityEventSubtitle": {},
    "batchFormMortalityDetailsTitle": "Detalles de Mortalidad",
    "@batchFormMortalityDetailsTitle": {},
    "batchFormMortalityDetailsSubtitle": "Describa los detalles adicionales",
    "@batchFormMortalityDetailsSubtitle": {},
    "batchFormMortalityDescription": "Descripción de mortalidad",
    "@batchFormMortalityDescription": {},
    "batchFormMortalityDescriptionHint": "Describa las circunstancias...",
    "@batchFormMortalityDescriptionHint": {},
    "batchFormRecommendation": "Recomendación",
    "@batchFormRecommendation": {},
    "batchFormRecommendedActions": "Acciones recomendadas",
    "@batchFormRecommendedActions": {},
    "batchFormPhotoEvidence": "Evidencia fotográfica",
    "@batchFormPhotoEvidence": {},
    "batchFormPhotoOptional": "Fotos opcionales",
    "@batchFormPhotoOptional": {},
    "batchFormPhotoHelpText": "Tome o seleccione fotos como evidencia",
    "@batchFormPhotoHelpText": {},
    "batchFormNoPhotos": "Sin fotos",
    "@batchFormNoPhotos": {},
    "batchFormMaxPhotos": "Máximo de fotos alcanzado",
    "@batchFormMaxPhotos": {},
    "batchFormSelectedPhotos": "Fotos seleccionadas",
    "@batchFormSelectedPhotos": {},
    "batchFormTakePhoto": "Tomar foto",
    "@batchFormTakePhoto": {},
    "batchFormGallery": "Galería",
    "@batchFormGallery": {},
    "batchFormObservationsAndEvidence": "Observaciones y Evidencia",
    "@batchFormObservationsAndEvidence": {},
    "batchFormObservationsSubtitle": "Agregue observaciones adicionales",
    "@batchFormObservationsSubtitle": {},
    "batchFormWeightInfo": "Información de Peso",
    "@batchFormWeightInfo": {},
    "batchFormWeightSubtitle": "Registre el peso del lote",
    "@batchFormWeightSubtitle": {},
    "batchFormWeightMethod": "Método de pesaje",
    "@batchFormWeightMethod": {},
    "batchFormWeightRanges": "Rangos de Peso",
    "@batchFormWeightRanges": {},
    "batchFormWeightRangesSubtitle": "Clasifique por rangos de peso",
    "@batchFormWeightRangesSubtitle": {},
    "batchFormWeightMin": "Peso mínimo",
    "@batchFormWeightMin": {},
    "batchFormWeightMax": "Peso máximo",
    "@batchFormWeightMax": {},
    "batchFormWeightSummary": "Resumen de Peso",
    "@batchFormWeightSummary": {},
    "batchFormWeightSummarySubtitle": "Resumen de los datos registrados",
    "@batchFormWeightSummarySubtitle": {},
    "batchFormAutoCalculatedWeight": "Peso calculado automáticamente",
    "@batchFormAutoCalculatedWeight": {},
    "batchFormCalculatedAvgWeight": "Peso promedio calculado",
    "@batchFormCalculatedAvgWeight": {},
    "batchFormCalculatedMetrics": "Métricas calculadas",
    "@batchFormCalculatedMetrics": {},
    "batchFormMetricsAutoCalculated": "Las métricas se calculan automáticamente",
    "@batchFormMetricsAutoCalculated": {},
    "batchFormConsumptionInfo": "Información de Consumo",
    "@batchFormConsumptionInfo": {},
    "batchFormConsumptionSubtitle": "Registre el consumo de alimento",
    "@batchFormConsumptionSubtitle": {},
    "batchFormConsumptionSaveNote": "Los datos se guardarán al continuar",
    "@batchFormConsumptionSaveNote": {},
    "batchFormFoodFromInventory": "Alimento del inventario",
    "@batchFormFoodFromInventory": {},
    "batchFormSelectFoodHint": "Seleccione un alimento",
    "@batchFormSelectFoodHint": {},
    "batchFormNoFoodInInventory": "No hay alimentos en inventario",
    "@batchFormNoFoodInInventory": {},
    "batchFormFoodBatch": "Lote de alimento",
    "@batchFormFoodBatch": {},
    "batchFormLowStock": "Stock bajo",
    "@batchFormLowStock": {},
    "batchFormDetailsCosts": "Detalles y Costos",
    "@batchFormDetailsCosts": {},
    "batchFormDetailsCostsSubtitle": "Ingrese detalles y costos",
    "@batchFormDetailsCostsSubtitle": {},
    "batchFormCostPerBird": "Costo por ave",
    "@batchFormCostPerBird": {},
    "batchFormCostThisRecord": "Costo de este registro",
    "@batchFormCostThisRecord": {},
    "batchFormProductionInfo": "Información de Producción",
    "@batchFormProductionInfo": {},
    "batchFormProductionInfoSubtitle": "Registre la producción de huevos",
    "@batchFormProductionInfoSubtitle": {},
    "batchFormEggsCollected": "Huevos recolectados",
    "@batchFormEggsCollected": {},
    "batchFormDefectiveEggs": "Huevos defectuosos",
    "@batchFormDefectiveEggs": {},
    "batchFormLayingPercentage": "Porcentaje de postura",
    "@batchFormLayingPercentage": {},
    "batchFormLayingIndicator": "Indicador de postura",
    "@batchFormLayingIndicator": {},
    "batchFormExcellentPerformance": "Rendimiento excelente",
    "@batchFormExcellentPerformance": {},
    "batchFormAcceptablePerformance": "Rendimiento aceptable",
    "@batchFormAcceptablePerformance": {},
    "batchFormBelowExpectedPerformance": "Rendimiento por debajo de lo esperado",
    "@batchFormBelowExpectedPerformance": {},
    "batchFormProductionSummary": "Resumen de producción",
    "@batchFormProductionSummary": {},
    "batchFormCompleteAmountToSeeMetrics": "Complete la cantidad para ver métricas",
    "@batchFormCompleteAmountToSeeMetrics": {},
    "batchFormEggClassification": "Clasificación de Huevos",
    "@batchFormEggClassification": {},
    "batchFormEggClassificationSubtitle": "Clasifique los huevos recolectados",
    "@batchFormEggClassificationSubtitle": {},
    "batchFormClassifyForWeight": "Clasificar por peso",
    "@batchFormClassifyForWeight": {},
    "batchFormSmallEggs": "Huevos pequeños",
    "@batchFormSmallEggs": {},
    "batchFormMediumEggs": "Huevos medianos",
    "@batchFormMediumEggs": {},
    "batchFormLargeEggs": "Huevos grandes",
    "@batchFormLargeEggs": {},
    "batchFormExtraLargeEggs": "Huevos extra grandes",
    "@batchFormExtraLargeEggs": {},
    "batchFormBroken": "Rotos",
    "@batchFormBroken": {},
    "batchFormGoodEggs": "Huevos buenos",
    "@batchFormGoodEggs": {},
    "batchFormTotalClassified": "Total clasificados",
    "@batchFormTotalClassified": {},
    "batchFormTotalToClassify": "Total a clasificar",
    "@batchFormTotalToClassify": {},
    "batchFormClassificationSummary": "Resumen de clasificación",
    "@batchFormClassificationSummary": {},
    "batchFormCannotExceedCollected": "No puede exceder los huevos recolectados",
    "@batchFormCannotExceedCollected": {},
    "batchFormExcessEggs": "Exceso de huevos clasificados",
    "@batchFormExcessEggs": {},
    "batchFormMissingEggs": "Faltan huevos por clasificar",
    "@batchFormMissingEggs": {},
    "batchFormSizeClassification": "Clasificación por tamaño",
    "@batchFormSizeClassification": {}
'@

$newKeysEn = @'

    "batchTitle": "Batches",
    "@batchTitle": {},
    "batchDeleteBatch": "Delete Batch",
    "@batchDeleteBatch": {},
    "batchFilterTitle": "Filter Batches",
    "@batchFilterTitle": {},
    "batchFilterClear": "Clear",
    "@batchFilterClear": {},
    "batchFilterStatus": "Status",
    "@batchFilterStatus": {},
    "batchFilterAll": "All",
    "@batchFilterAll": {},
    "batchFilterBirdType": "Bird type",
    "@batchFilterBirdType": {},
    "batchFilterEntryDate": "Entry date",
    "@batchFilterEntryDate": {},
    "batchFilterFrom": "From",
    "@batchFilterFrom": {},
    "batchFilterTo": "To",
    "@batchFilterTo": {},
    "batchFilterAny": "Any",
    "@batchFilterAny": {},
    "batchFilterCancel": "Cancel",
    "@batchFilterCancel": {},
    "batchFilterApply": "Apply",
    "@batchFilterApply": {},
    "batchCloseSummary": "Closure Summary",
    "@batchCloseSummary": {},
    "batchCloseStartDate": "Start date",
    "@batchCloseStartDate": {},
    "batchCloseEndDate": "Close date",
    "@batchCloseEndDate": {},
    "batchCloseDate": "Close date",
    "@batchCloseDate": {},
    "batchCloseDuration": "Duration",
    "@batchCloseDuration": {},
    "batchCloseDays": "days",
    "@batchCloseDays": {},
    "batchCloseCycleDuration": "Cycle duration",
    "@batchCloseCycleDuration": {},
    "batchCloseCycleInfo": "Cycle information",
    "@batchCloseCycleInfo": {},
    "batchClosePopulation": "Population",
    "@batchClosePopulation": {},
    "batchCloseTotalMortality": "Total mortality",
    "@batchCloseTotalMortality": {},
    "batchCloseMortality": "Mortality",
    "@batchCloseMortality": {},
    "batchCloseMortalityPercent": "Mortality %",
    "@batchCloseMortalityPercent": {},
    "batchCloseFinalMetrics": "Final Metrics",
    "@batchCloseFinalMetrics": {},
    "batchCloseFinalWeight": "Final weight",
    "@batchCloseFinalWeight": {},
    "batchCloseFinalWeightLabel": "Final weight (kg)",
    "@batchCloseFinalWeightLabel": {},
    "batchCloseWeightGain": "Weight gain",
    "@batchCloseWeightGain": {},
    "batchCloseEstimatedWeight": "Estimated weight",
    "@batchCloseEstimatedWeight": {},
    "batchCloseFeedConversion": "Feed conversion",
    "@batchCloseFeedConversion": {},
    "batchCloseGrams": "grams",
    "@batchCloseGrams": {},
    "batchCloseWeightRequired": "Weight is required",
    "@batchCloseWeightRequired": {},
    "batchCloseWeightMustBePositive": "Weight must be positive",
    "@batchCloseWeightMustBePositive": {},
    "batchCloseWeightTooHigh": "Weight seems too high",
    "@batchCloseWeightTooHigh": {},
    "batchCloseWeightHelper": "Average weight per bird in kg",
    "@batchCloseWeightHelper": {},
    "batchCloseFinalObservations": "Final Observations",
    "@batchCloseFinalObservations": {},
    "batchCloseObservationsHint": "Write your observations here...",
    "@batchCloseObservationsHint": {},
    "batchCloseIrreversible": "Irreversible action",
    "@batchCloseIrreversible": {},
    "batchCloseIrreversibleMessage": "Once closed, the batch cannot be reopened",
    "@batchCloseIrreversibleMessage": {},
    "batchCloseConfirm": "Confirm closure",
    "@batchCloseConfirm": {},
    "batchCloseSaleInfo": "Sale Information",
    "@batchCloseSaleInfo": {},
    "batchCloseBirdsToSell": "Birds to sell",
    "@batchCloseBirdsToSell": {},
    "batchCloseBirdsUnit": "birds",
    "@batchCloseBirdsUnit": {},
    "batchCloseSalePriceLabel": "Sale price per kg",
    "@batchCloseSalePriceLabel": {},
    "batchCloseSalePriceHelper": "Price in local currency",
    "@batchCloseSalePriceHelper": {},
    "batchClosePricePerKg": "Price per kg",
    "@batchClosePricePerKg": {},
    "batchCloseEstimatedValue": "Estimated value",
    "@batchCloseEstimatedValue": {},
    "batchCloseBuyerLabel": "Buyer",
    "@batchCloseBuyerLabel": {},
    "batchCloseBuyerHint": "Buyer name (optional)",
    "@batchCloseBuyerHint": {},
    "batchCloseFinancialBalance": "Financial balance",
    "@batchCloseFinancialBalance": {},
    "batchCloseTotalIncome": "Total income",
    "@batchCloseTotalIncome": {},
    "batchCloseTotalExpenses": "Total expenses",
    "@batchCloseTotalExpenses": {},
    "batchCloseProfitability": "Profitability",
    "@batchCloseProfitability": {},
    "batchCloseEnterValidNumber": "Enter a valid number",
    "@batchCloseEnterValidNumber": {},
    "batchFormName": "Batch name",
    "@batchFormName": {},
    "batchFormBasicInfoSubtitle": "Basic batch information",
    "@batchFormBasicInfoSubtitle": {},
    "batchFormBasicInfoNote": "Complete the basic batch information",
    "@batchFormBasicInfoNote": {},
    "batchFormDetailsSubtitle": "Additional batch details",
    "@batchFormDetailsSubtitle": {},
    "batchFormReviewSubtitle": "Review information before creating",
    "@batchFormReviewSubtitle": {},
    "batchFormFarm": "Farm",
    "@batchFormFarm": {},
    "batchFormLocation": "Location",
    "@batchFormLocation": {},
    "batchFormShedInfo": "Shed information",
    "@batchFormShedInfo": {},
    "batchFormShedLocationInfo": "Shed location",
    "@batchFormShedLocationInfo": {},
    "batchFormCapacity": "Capacity",
    "@batchFormCapacity": {},
    "batchFormMaxCapacity": "Maximum capacity",
    "@batchFormMaxCapacity": {},
    "batchFormArea": "Area",
    "@batchFormArea": {},
    "batchFormAvailable": "Available",
    "@batchFormAvailable": {},
    "batchFormShedCapacity": "Shed capacity",
    "@batchFormShedCapacity": {},
    "batchFormShedCapacityNote": "Quantity cannot exceed capacity",
    "@batchFormShedCapacityNote": {},
    "batchFormExceedsCapacity": "Exceeds shed capacity",
    "@batchFormExceedsCapacity": {},
    "batchFormUtilization": "Utilization",
    "@batchFormUtilization": {},
    "batchFormCreateShedFirst": "Create a shed first",
    "@batchFormCreateShedFirst": {},
    "batchFormAgeAtEntry": "Age at entry",
    "@batchFormAgeAtEntry": {},
    "batchFormAgeHint": "Age in days (optional)",
    "@batchFormAgeHint": {},
    "batchFormAgeInfoNote": "Age is calculated automatically",
    "@batchFormAgeInfoNote": {},
    "batchFormOptional": "Optional",
    "@batchFormOptional": {},
    "batchFormNotSelected": "Not selected",
    "@batchFormNotSelected": {},
    "batchFormNotSpecified": "Not specified",
    "@batchFormNotSpecified": {},
    "batchFormNotFound": "Not found",
    "@batchFormNotFound": {},
    "batchFormUnits": "units",
    "@batchFormUnits": {},
    "batchFormDirty": "Dirty",
    "@batchFormDirty": {},
    "batchFormCurrentBirds": "Current birds",
    "@batchFormCurrentBirds": {},
    "batchFormInvalidNumber": "Invalid number",
    "@batchFormInvalidNumber": {},
    "batchFormInvalidValue": "Invalid value",
    "@batchFormInvalidValue": {},
    "batchFormMortalityEventInfo": "Mortality event information",
    "@batchFormMortalityEventInfo": {},
    "batchFormMortalityEventSubtitle": "Record event details",
    "@batchFormMortalityEventSubtitle": {},
    "batchFormMortalityDetailsTitle": "Mortality Details",
    "@batchFormMortalityDetailsTitle": {},
    "batchFormMortalityDetailsSubtitle": "Describe additional details",
    "@batchFormMortalityDetailsSubtitle": {},
    "batchFormMortalityDescription": "Mortality description",
    "@batchFormMortalityDescription": {},
    "batchFormMortalityDescriptionHint": "Describe the circumstances...",
    "@batchFormMortalityDescriptionHint": {},
    "batchFormRecommendation": "Recommendation",
    "@batchFormRecommendation": {},
    "batchFormRecommendedActions": "Recommended actions",
    "@batchFormRecommendedActions": {},
    "batchFormPhotoEvidence": "Photo evidence",
    "@batchFormPhotoEvidence": {},
    "batchFormPhotoOptional": "Optional photos",
    "@batchFormPhotoOptional": {},
    "batchFormPhotoHelpText": "Take or select photos as evidence",
    "@batchFormPhotoHelpText": {},
    "batchFormNoPhotos": "No photos",
    "@batchFormNoPhotos": {},
    "batchFormMaxPhotos": "Maximum photos reached",
    "@batchFormMaxPhotos": {},
    "batchFormSelectedPhotos": "Selected photos",
    "@batchFormSelectedPhotos": {},
    "batchFormTakePhoto": "Take photo",
    "@batchFormTakePhoto": {},
    "batchFormGallery": "Gallery",
    "@batchFormGallery": {},
    "batchFormObservationsAndEvidence": "Observations and Evidence",
    "@batchFormObservationsAndEvidence": {},
    "batchFormObservationsSubtitle": "Add additional observations",
    "@batchFormObservationsSubtitle": {},
    "batchFormWeightInfo": "Weight Information",
    "@batchFormWeightInfo": {},
    "batchFormWeightSubtitle": "Record batch weight",
    "@batchFormWeightSubtitle": {},
    "batchFormWeightMethod": "Weighing method",
    "@batchFormWeightMethod": {},
    "batchFormWeightRanges": "Weight Ranges",
    "@batchFormWeightRanges": {},
    "batchFormWeightRangesSubtitle": "Classify by weight ranges",
    "@batchFormWeightRangesSubtitle": {},
    "batchFormWeightMin": "Minimum weight",
    "@batchFormWeightMin": {},
    "batchFormWeightMax": "Maximum weight",
    "@batchFormWeightMax": {},
    "batchFormWeightSummary": "Weight Summary",
    "@batchFormWeightSummary": {},
    "batchFormWeightSummarySubtitle": "Summary of recorded data",
    "@batchFormWeightSummarySubtitle": {},
    "batchFormAutoCalculatedWeight": "Automatically calculated weight",
    "@batchFormAutoCalculatedWeight": {},
    "batchFormCalculatedAvgWeight": "Calculated average weight",
    "@batchFormCalculatedAvgWeight": {},
    "batchFormCalculatedMetrics": "Calculated metrics",
    "@batchFormCalculatedMetrics": {},
    "batchFormMetricsAutoCalculated": "Metrics are automatically calculated",
    "@batchFormMetricsAutoCalculated": {},
    "batchFormConsumptionInfo": "Consumption Information",
    "@batchFormConsumptionInfo": {},
    "batchFormConsumptionSubtitle": "Record food consumption",
    "@batchFormConsumptionSubtitle": {},
    "batchFormConsumptionSaveNote": "Data will be saved when continuing",
    "@batchFormConsumptionSaveNote": {},
    "batchFormFoodFromInventory": "Food from inventory",
    "@batchFormFoodFromInventory": {},
    "batchFormSelectFoodHint": "Select a food item",
    "@batchFormSelectFoodHint": {},
    "batchFormNoFoodInInventory": "No food items in inventory",
    "@batchFormNoFoodInInventory": {},
    "batchFormFoodBatch": "Food batch",
    "@batchFormFoodBatch": {},
    "batchFormLowStock": "Low stock",
    "@batchFormLowStock": {},
    "batchFormDetailsCosts": "Details and Costs",
    "@batchFormDetailsCosts": {},
    "batchFormDetailsCostsSubtitle": "Enter details and costs",
    "@batchFormDetailsCostsSubtitle": {},
    "batchFormCostPerBird": "Cost per bird",
    "@batchFormCostPerBird": {},
    "batchFormCostThisRecord": "Cost of this record",
    "@batchFormCostThisRecord": {},
    "batchFormProductionInfo": "Production Information",
    "@batchFormProductionInfo": {},
    "batchFormProductionInfoSubtitle": "Record egg production",
    "@batchFormProductionInfoSubtitle": {},
    "batchFormEggsCollected": "Eggs collected",
    "@batchFormEggsCollected": {},
    "batchFormDefectiveEggs": "Defective eggs",
    "@batchFormDefectiveEggs": {},
    "batchFormLayingPercentage": "Laying percentage",
    "@batchFormLayingPercentage": {},
    "batchFormLayingIndicator": "Laying indicator",
    "@batchFormLayingIndicator": {},
    "batchFormExcellentPerformance": "Excellent performance",
    "@batchFormExcellentPerformance": {},
    "batchFormAcceptablePerformance": "Acceptable performance",
    "@batchFormAcceptablePerformance": {},
    "batchFormBelowExpectedPerformance": "Below expected performance",
    "@batchFormBelowExpectedPerformance": {},
    "batchFormProductionSummary": "Production summary",
    "@batchFormProductionSummary": {},
    "batchFormCompleteAmountToSeeMetrics": "Complete amount to see metrics",
    "@batchFormCompleteAmountToSeeMetrics": {},
    "batchFormEggClassification": "Egg Classification",
    "@batchFormEggClassification": {},
    "batchFormEggClassificationSubtitle": "Classify collected eggs",
    "@batchFormEggClassificationSubtitle": {},
    "batchFormClassifyForWeight": "Classify by weight",
    "@batchFormClassifyForWeight": {},
    "batchFormSmallEggs": "Small eggs",
    "@batchFormSmallEggs": {},
    "batchFormMediumEggs": "Medium eggs",
    "@batchFormMediumEggs": {},
    "batchFormLargeEggs": "Large eggs",
    "@batchFormLargeEggs": {},
    "batchFormExtraLargeEggs": "Extra large eggs",
    "@batchFormExtraLargeEggs": {},
    "batchFormBroken": "Broken",
    "@batchFormBroken": {},
    "batchFormGoodEggs": "Good eggs",
    "@batchFormGoodEggs": {},
    "batchFormTotalClassified": "Total classified",
    "@batchFormTotalClassified": {},
    "batchFormTotalToClassify": "Total to classify",
    "@batchFormTotalToClassify": {},
    "batchFormClassificationSummary": "Classification summary",
    "@batchFormClassificationSummary": {},
    "batchFormCannotExceedCollected": "Cannot exceed collected eggs",
    "@batchFormCannotExceedCollected": {},
    "batchFormExcessEggs": "Excess classified eggs",
    "@batchFormExcessEggs": {},
    "batchFormMissingEggs": "Missing eggs to classify",
    "@batchFormMissingEggs": {},
    "batchFormSizeClassification": "Size classification",
    "@batchFormSizeClassification": {}
'@

$esContent = $esContent -replace '(\r?\n)\}$', (',{0}{1}{0}}}' -f "`n", $newKeysEs)
$enContent = $enContent -replace '(\r?\n)\}$', (',{0}{1}{0}}}' -f "`n", $newKeysEn)

[System.IO.File]::WriteAllText($esFile, $esContent)
[System.IO.File]::WriteAllText($enFile, $enContent)

Write-Output "Added 155 missing keys"
