#!/usr/bin/env python3
"""
Script para generar app_pt.arb (Portugués brasileño) a partir de app_es.arb y app_en.arb.
Usa un mapeo español→portugués con fallback a inglés→portugués.
"""
import json
import re
import sys
import os

# Directorio base
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
L10N_DIR = os.path.join(BASE_DIR, 'lib', 'l10n')

# Cargar archivos fuente
with open(os.path.join(L10N_DIR, 'app_es.arb'), 'r', encoding='utf-8') as f:
    es_data = json.load(f)

with open(os.path.join(L10N_DIR, 'app_en.arb'), 'r', encoding='utf-8') as f:
    en_data = json.load(f)

# ============================================================
# DICCIONARIO MAESTRO DE TRADUCCIONES ESPAÑOL → PORTUGUÉS
# ============================================================
# Palabras y frases comunes ordenadas de mayor a menor longitud 
# para evitar reemplazos parciales

ES_TO_PT = {
    # --- Frases largas primero ---
    "No tienes permiso para realizar esta acción": "Você não tem permissão para realizar esta ação",
    "No tienes permiso para crear registros": "Você não tem permissão para criar registros",
    "No tienes permiso para editar registros": "Você não tem permissão para editar registros",
    "No tienes permiso para eliminar registros": "Você não tem permissão para excluir registros",
    "No tienes permiso para crear lotes": "Você não tem permissão para criar lotes",
    "No tienes permiso para editar lotes": "Você não tem permissão para editar lotes",
    "No tienes permiso para eliminar lotes": "Você não tem permissão para excluir lotes",
    "No tienes permiso para crear galpones": "Você não tem permissão para criar galpões",
    "No tienes permiso para editar galpones": "Você não tem permissão para editar galpões",
    "No tienes permiso para eliminar galpones": "Você não tem permissão para excluir galpões",
    "No tienes permiso para invitar usuarios": "Você não tem permissão para convidar usuários",
    "No tienes permiso para cambiar roles": "Você não tem permissão para alterar funções",
    "No tienes permiso para remover usuarios": "Você não tem permissão para remover usuários",
    "No tienes permiso para ver colaboradores": "Você não tem permissão para ver colaboradores",
    "No tienes permiso para editar la granja": "Você não tem permissão para editar a granja",
    "No tienes permiso para eliminar la granja": "Você não tem permissão para excluir a granja",
    "No tienes permiso para ver reportes": "Você não tem permissão para ver relatórios",
    "No tienes permiso para exportar datos": "Você não tem permissão para exportar dados",
    "No tienes permiso para gestionar inventario": "Você não tem permissão para gerenciar inventário",
    "No tienes permiso para registrar ventas": "Você não tem permissão para registrar vendas",
    "No tienes permiso para ver la configuración": "Você não tem permissão para ver a configuração",
    "Sin conexión - Los cambios se guardarán localmente": "Sem conexão - As alterações serão salvas localmente",
    "No hay conexión a internet. Los datos pueden no estar actualizados": "Sem conexão com a internet. Os dados podem não estar atualizados",
    "Prueba modificando los filtros de búsqueda": "Tente modificar os filtros de busca",
    "No se encontraron resultados": "Nenhum resultado encontrado",
    "¿Deseas salir sin guardar los cambios?": "Deseja sair sem salvar as alterações?",
    "No te preocupes, tus datos están seguros.": "Não se preocupe, seus dados estão seguros.",
    "Gestiona tu granja de forma inteligente": "Gerencie sua granja de forma inteligente",
    "Únete para gestionar tu granja de forma inteligente": "Junte-se para gerenciar sua granja de forma inteligente",
    "Ingresa tus credenciales para continuar": "Insira suas credenciais para continuar",
    "Debes aceptar los términos y condiciones": "Você deve aceitar os termos e condições",
    "Te hemos enviado un enlace para restablecer tu contraseña": "Enviamos um link para redefinir sua senha",
    "Ingresa tu correo y te enviaremos instrucciones": "Insira seu e-mail e enviaremos instruções",
    "La contraseña debe tener al menos 8 caracteres": "A senha deve ter pelo menos 8 caracteres",
    "Ingresa un correo electrónico válido": "Insira um e-mail válido",
    "El correo electrónico es requerido": "O e-mail é obrigatório",
    "La contraseña es requerida": "A senha é obrigatória",
    "Las contraseñas no coinciden": "As senhas não coincidem",
    "Debe contener al menos una mayúscula": "Deve conter pelo menos uma maiúscula",
    "Debe contener al menos una minúscula": "Deve conter pelo menos uma minúscula",
    "Debe contener al menos un número": "Deve conter pelo menos um número",
    "Comparte acceso con otros usuarios": "Compartilhe acesso com outros usuários",
    "Únete a la granja de alguien más": "Junte-se à granja de outra pessoa",
    "Ver y administrar accesos": "Ver e gerenciar acessos",
    "Configura alertas y recordatorios": "Configure alertas e lembretes",
    "Preferencias de la aplicación": "Preferências do aplicativo",
    "Preguntas frecuentes y guías": "Perguntas frequentes e guias",
    "Comparte tus ideas con nosotros": "Compartilhe suas ideias conosco",
    "Información de la aplicación": "Informações do aplicativo",
    "Selecciona la granja donde invitar": "Selecione a granja para convidar",
    "Cambia el idioma de la aplicación": "Altere o idioma do aplicativo",
    "Si no ves el correo, revisa tu carpeta de spam": "Se não encontrar o e-mail, verifique sua pasta de spam",
    "Tendrás que volver a iniciar sesión para acceder a tu cuenta.": "Você precisará fazer login novamente para acessar sua conta.",
    "No tienes granjas. Crea una primero.": "Você não tem granjas. Crie uma primeiro.",
    "¿En qué podemos ayudarte?": "Como podemos ajudá-lo?",
    "Consulta las dudas más comunes": "Consulte as dúvidas mais comuns",
    "Guía completa de uso": "Guia completo de uso",
    "¿Tienes alguna idea para mejorar la app? Nos encantaría escucharte.": "Tem alguma ideia para melhorar o app? Adoraríamos ouvir você.",
    "Escribe tu sugerencia aquí...": "Escreva sua sugestão aqui...",
    "¡Gracias por tu sugerencia!": "Obrigado pela sua sugestão!",
    "Eliminar tu cuenta borrará permanentemente todos tus datos, incluyendo granjas, lotes y registros.": "Excluir sua conta apagará permanentemente todos os seus dados, incluindo granjas, lotes e registros.",
    "Se eliminarán los datos temporales. Esto no afectará tus registros.": "Os dados temporários serão removidos. Isso não afetará seus registros.",
    "Te enviaremos un enlace para restablecer tu contraseña.": "Enviaremos um link para redefinir sua senha.",
    "Se ha enviado un enlace a tu correo": "Um link foi enviado para seu e-mail",
    "Se ha enviado un correo de verificación": "Um e-mail de verificação foi enviado",
    "Esta acción es irreversible y perderás todos tus datos.": "Esta ação é irreversível e você perderá todos os seus dados.",
    "Tienes cambios sin guardar. ¿Estás seguro de que quieres salir?": "Você tem alterações não salvas. Tem certeza de que deseja sair?",
    "Error al actualizar la foto. Intenta de nuevo.": "Erro ao atualizar a foto. Tente novamente.",
    "La imagen excede el tamaño máximo (5MB)": "A imagem excede o tamanho máximo (5MB)",
    "Recibe un resumen cada día a las 8:00 PM": "Receba um resumo todo dia às 20:00",
    "Recibe un resumen cada lunes": "Receba um resumo toda segunda-feira",
    "Alerta cuando la mortalidad supera el": "Alerta quando a mortalidade supera",
    "Alerta cuando la producción cae bajo el": "Alerta quando a produção cai abaixo de",
    "Alerta cuando el consumo varía significativamente": "Alerta quando o consumo varia significativamente",
    "Alerta cuando el alimento está por agotarse": "Alerta quando a ração está acabando",
    "Recuerda vacunaciones programadas": "Lembre de vacinações programadas",
    "Cambia el tema de la aplicación": "Altere o tema do aplicativo",
    "Recibe alertas importantes": "Receba alertas importantes",
    "Libera espacio en el dispositivo": "Libere espaço no dispositivo",
    "Actualiza tu contraseña de acceso": "Atualize sua senha de acesso",
    "Confirma tu dirección de correo": "Confirme seu endereço de e-mail",
    "Personaliza qué alertas recibir": "Personalize quais alertas receber",
    "Reproduce sonidos de notificación": "Reproduza sons de notificação",
    "Vibrar al recibir notificaciones": "Vibrar ao receber notificações",
    "Crea un lote para comenzar a registrar": "Crie um lote para começar a registrar",
}

# Diccionario de traducción inglés → portugués para las claves que no se mapean bien del español
EN_TO_PT = {
    # App title
    "Smart Poultry Farm Pro": "Smart Granja Aves Pro",
    # Navigation
    "Home": "Início",
    "Management": "Gestão",
    "Batches": "Lotes",
    "Profile": "Perfil",
    # Common
    "Cancel": "Cancelar",
    "Delete": "Excluir",
    "Continue": "Continuar",
    "Confirm": "Confirmar",
    "Accept": "Aceitar",
    "Save": "Salvar",
    "Edit": "Editar",
    "Close": "Fechar",
    "Retry": "Tentar novamente",
    "Search...": "Buscar...",
    "Go to home": "Ir ao início",
    "Loading...": "Carregando...",
    "Apply filters": "Aplicar filtros",
    "Clear filters": "Limpar filtros",
    "Clear": "Limpar",
    "No results found": "Nenhum resultado encontrado",
    "Try modifying the search filters": "Tente modificar os filtros de busca",
    "Something went wrong": "Algo deu errado",
    "An error has occurred": "Ocorreu um erro",
    "Yes": "Sim",
    "No": "Não",
    "or": "ou",
    "Back": "Voltar",
    "Details": "Detalhes",
    "Filter": "Filtrar",
    "More options": "Mais opções",
    "Clear search": "Limpar busca",
    "All": "Todos",
    "All types": "Todos os tipos",
    "All statuses": "Todos os estados",
    "Discard": "Descartar",
    "Coming soon": "Em breve",
    "Unsaved changes": "Alterações não salvas",
    "Do you want to leave without saving?": "Deseja sair sem salvar as alterações?",
    "Exit": "Sair",
    "Don't worry, your data is safe.": "Não se preocupe, seus dados estão seguros.",
    "Observations": "Observações",
    "Description": "Descrição",
    "Date": "Data",
    "Name": "Nome",
    "Phone": "Telefone",
    "Provider": "Fornecedor",
    "Location": "Localização",
    "Active": "Ativo",
    "Inactive": "Inativo",
    "Pending": "Pendentes",
    "Approved": "Aprovados",
    "Total:": "Total:",
    "Information": "Informações",
    "Summary": "Resumo",
    "Basic Information": "Informações Básicas",
    "Additional Information": "Informações Adicionais",
    "Not found": "Não encontrado",
    "Error": "Erro",
    "Success": "Sucesso",
    "Registered by": "Registrado por",
    "Role": "Função",
    "Registration date": "Data de registro",
    "Loading farms...": "Carregando granjas...",
    # Connectivity
    "No internet connection": "Sem conexão com a internet",
    "Offline": "Offline",
    "Offline • Data saved locally": "Offline - Dados salvos localmente",
    "Offline mode": "Modo offline",
    "No internet connection. Displayed data may be outdated": "Sem conexão com a internet. Os dados podem não estar atualizados",
    # Errors
    "Server error": "Erro do servidor",
    "Data not found in cache": "Dados não encontrados no cache",
    "Request timed out": "Tempo de solicitação esgotado",
    "Invalid credentials": "Credenciais inválidas",
    "Your session has expired": "Sua sessão expirou",
    "You don't have permission for this action": "Você não tem permissão para esta ação",
    "Error writing to cache": "Erro ao gravar no cache",
    "No active session": "Nenhuma sessão ativa",
    "Invalid email address": "Endereço de e-mail inválido",
    "Error reading file": "Erro ao ler arquivo",
    "Error writing file": "Erro ao gravar arquivo",
    "Error deleting file": "Erro ao excluir arquivo",
    "Error verifying permissions": "Erro ao verificar permissões",
    "Error loading activities": "Erro ao carregar atividades",
    # Permissions
    "You don't have permission to create records": "Você não tem permissão para criar registros",
    "You don't have permission to edit records": "Você não tem permissão para editar registros",
    "You don't have permission to delete records": "Você não tem permissão para excluir registros",
    "You don't have permission to create batches": "Você não tem permissão para criar lotes",
    "You don't have permission to edit batches": "Você não tem permissão para editar lotes",
    "You don't have permission to delete batches": "Você não tem permissão para excluir lotes",
    "You don't have permission to create sheds": "Você não tem permissão para criar galpões",
    "You don't have permission to edit sheds": "Você não tem permissão para editar galpões",
    "You don't have permission to delete sheds": "Você não tem permissão para excluir galpões",
    "You don't have permission to invite users": "Você não tem permissão para convidar usuários",
    "You don't have permission to change roles": "Você não tem permissão para alterar funções",
    "You don't have permission to remove users": "Você não tem permissão para remover usuários",
    "You don't have permission to view collaborators": "Você não tem permissão para ver colaboradores",
    "You don't have permission to edit the farm": "Você não tem permissão para editar a granja",
    "You don't have permission to delete the farm": "Você não tem permissão para excluir a granja",
    "You don't have permission to view reports": "Você não tem permissão para ver relatórios",
    "You don't have permission to export data": "Você não tem permissão para exportar dados",
    "You don't have permission to manage inventory": "Você não tem permissão para gerenciar inventário",
    "You don't have permission to register sales": "Você não tem permissão para registrar vendas",
    "You don't have permission to view settings": "Você não tem permissão para ver a configuração",
    # Auth
    "Manage your farm intelligently": "Gerencie sua granja de forma inteligente",
    "Create account": "Criar conta",
    "I already have an account": "Já tenho conta",
    "or continue with": "ou continue com",
    "Welcome back": "Bem-vindo de volta",
    "Enter your credentials to continue": "Insira suas credenciais para continuar",
    "or sign in with email": "ou entre com e-mail",
    "Email": "E-mail",
    "Sign In": "Entrar",
    "Forgot your password?": "Esqueceu sua senha?",
    "Don't have an account?": "Não tem conta?",
    "Sign Up": "Cadastrar-se",
    "Email is required": "O e-mail é obrigatório",
    "Enter a valid email address": "Insira um endereço de e-mail válido",
    "Password is required": "A senha é obrigatória",
    "Password must be at least 8 characters": "A senha deve ter pelo menos 8 caracteres",
    "Join to manage your farm intelligently": "Junte-se para gerenciar sua granja de forma inteligente",
    "Sign up with Google": "Cadastrar-se com Google",
    "or sign up with email": "ou cadastre-se com e-mail",
    "First name": "Nome",
    "Last name": "Sobrenome",
    "Password": "Senha",
    "Confirm password": "Confirmar senha",
    "You must accept the terms and conditions": "Você deve aceitar os termos e condições",
    "Terms and Conditions": "Termos e Condições",
    "Check your email!": "Verifique seu e-mail!",
    "We sent you a link to reset your password": "Enviamos um link para redefinir sua senha",
    "Enter your email and we'll send instructions": "Insira seu e-mail e enviaremos instruções",
    "Send instructions": "Enviar instruções",
    "Remember your password?": "Lembrou sua senha?",
    "Continue with Google": "Continuar com Google",
    "Continue with Apple": "Continuar com Apple",
    "Continue with Facebook": "Continuar com Facebook",
    "Enter your password": "Insira sua senha",
    "Current password": "Senha atual",
    "Sign Out": "Sair",
    "example@email.com": "exemplo@email.com",
    "John": "João",
    "Smith": "Silva",
    "Remember email": "Lembrar e-mail",
    "Already have an account?": "Já tem conta?",
    "Sign in": "Entrar",
    "I accept the ": "Eu aceito os ",
    "Privacy Policy": "Política de Privacidade",
    " and the ": " e a ",
    "Minimum 8 characters": "Mínimo 8 caracteres",
    "One uppercase letter": "Uma letra maiúscula",
    "One lowercase letter": "Uma letra minúscula",
    "One number": "Um número",
    "One special character": "Um caractere especial",
    "Weak": "Fraca",
    "Medium": "Média",
    "Strong": "Forte",
    "Confirm your password": "Confirme sua senha",
    "Passwords do not match": "As senhas não coincidem",
    "Must contain at least one uppercase letter": "Deve conter pelo menos uma letra maiúscula",
    "Must contain at least one lowercase letter": "Deve conter pelo menos uma letra minúscula",
    "Must contain at least one number": "Deve conter pelo menos um número",
    "Link Accounts": "Vincular Contas",
    "Link": "Vincular",
    "Sent to:": "Enviado para:",
    "If you don't see the email, check your spam folder": "Se não encontrar o e-mail, verifique sua pasta de spam",
    "Resend email": "Reenviar e-mail",
    "Back to sign in": "Voltar ao login",
    "Email and Password": "E-mail e Senha",
    "Password must be at least 6 characters": "A senha deve ter pelo menos 6 caracteres",
    # Home
    "Quick Actions": "Ações Rápidas",
    "Vaccination": "Vacinação",
    "Diseases": "Doenças",
    "Biosecurity": "Biossegurança",
    "Sales": "Vendas",
    "Costs": "Custos",
    "Inventory": "Inventário",
    "Select a farm first": "Selecione uma granja primeiro",
    "General Statistics": "Estatísticas Gerais",
    "Available Sheds": "Galpões Disponíveis",
    "Active Batches": "Lotes Ativos",
    "Total Birds": "Aves Totais",
    "Occupancy": "Ocupação",
    "No sheds": "Sem galpões",
    "No batches": "Sem lotes",
    "Across the farm": "Em toda a granja",
    "Expiring soon": "Próximo a vencer",
    "High mortality": "Mortalidade elevada",
    "No active batches": "Sem lotes ativos",
    "Create a batch to start recording": "Crie um lote para começar a registrar",
    "Good morning": "Bom dia",
    "Good afternoon": "Boa tarde",
    "Good evening": "Boa noite",
    "Hello": "Olá",
    # Profile
    "My Account": "Minha Conta",
    "User": "Usuário",
    "Collaboration": "Colaboração",
    "Invite to my Farm": "Convidar para minha Granja",
    "Share access with other users": "Compartilhe acesso com outros usuários",
    "Accept Invitation": "Aceitar Convite",
    "Join someone else's farm": "Junte-se à granja de outra pessoa",
    "Manage Collaborators": "Gerenciar Colaboradores",
    "View and manage access": "Ver e gerenciar acessos",
    "Settings": "Configurações",
    "Notifications": "Notificações",
    "Configure alerts and reminders": "Configure alertas e lembretes",
    "General Settings": "Configurações Gerais",
    "App preferences": "Preferências do aplicativo",
    "Help & Support": "Ajuda e Suporte",
    "Help Center": "Central de Ajuda",
    "FAQ and guides": "Perguntas frequentes e guias",
    "Send Feedback": "Enviar Sugestão",
    "Share your ideas with us": "Compartilhe suas ideias conosco",
    "About": "Sobre",
    "App information": "Informações do aplicativo",
    "Select the farm to invite to": "Selecione a granja para convidar",
    "Select a farm": "Selecione uma granja",
    "Language": "Idioma",
    "Change the app language": "Altere o idioma do aplicativo",
    "Sign out?": "Sair?",
    "You'll need to sign in again to access your account.": "Você precisará fazer login novamente para acessar sua conta.",
    "You have no farms. Create one first.": "Você não tem granjas. Crie uma primeiro.",
    "Create": "Criar",
    "How can we help you?": "Como podemos ajudá-lo?",
    "Email Support": "Suporte por E-mail",
    "FAQ": "Perguntas Frequentes",
    "Check common questions": "Consulte as dúvidas mais comuns",
    "User Manual": "Manual do Usuário",
    "Complete usage guide": "Guia completo de uso",
    "Do you have any ideas to improve the app? We'd love to hear from you.": "Tem alguma ideia para melhorar o app? Adoraríamos ouvir você.",
    "Write your suggestion here...": "Escreva sua sugestão aqui...",
    "Thanks for your feedback!": "Obrigado pela sua sugestão!",
    "Your smart poultry farm management partner. Control batches, monitor performance, track vaccinations, and optimize your farm's production easily and efficiently.": "Seu parceiro inteligente para gestão avícola. Controle lotes, monitore o desempenho, acompanhe vacinações e otimize a produção da sua granja de forma simples e eficiente.",
    "© 2024 Smart Granja. All rights reserved.": "© 2024 Smart Granja. Todos os direitos reservados.",
    # Edit Profile
    "Edit Profile": "Editar Perfil",
    "Personal Information": "Informações Pessoais",
    "Account Information": "Informações da Conta",
    "Member since": "Membro desde",
    "Change profile photo": "Alterar foto de perfil",
    "Take photo": "Tirar foto",
    "Choose from gallery": "Escolher da galeria",
    "Photo updated successfully": "Foto atualizada com sucesso",
    "Error updating photo. Try again.": "Erro ao atualizar a foto. Tente novamente.",
    "Image exceeds maximum size (5MB)": "A imagem excede o tamanho máximo (5MB)",
    "Discard changes?": "Descartar alterações?",
    "You have unsaved changes. Are you sure you want to leave?": "Você tem alterações não salvas. Tem certeza de que deseja sair?",
    "Unknown": "Desconhecido",
    "Profile updated successfully": "Perfil atualizado com sucesso",
    # Settings
    "Appearance": "Aparência",
    "Dark mode": "Modo escuro",
    "Change the app theme": "Altere o tema do aplicativo",
    "Push notifications": "Notificações push",
    "Receive important alerts": "Receba alertas importantes",
    "Sounds": "Sons",
    "Play notification sounds": "Reproduza sons de notificação",
    "Vibration": "Vibração",
    "Vibrate on notifications": "Vibrar ao receber notificações",
    "Configure alerts": "Configurar alertas",
    "Customize which alerts to receive": "Personalize quais alertas receber",
    "Data & Storage": "Dados e Armazenamento",
    "Clear cache": "Limpar cache",
    "Free up device storage": "Libere espaço no dispositivo",
    "Security": "Segurança",
    "Change password": "Alterar senha",
    "Update your access password": "Atualize sua senha de acesso",
    "Verify email": "Verificar e-mail",
    "Confirm your email address": "Confirme seu endereço de e-mail",
    "Danger zone": "Zona de perigo",
    "Deleting your account will permanently erase all your data, including farms, batches, and records.": "Excluir sua conta apagará permanentemente todos os seus dados, incluindo granjas, lotes e registros.",
    "Delete account": "Excluir conta",
    "Clear cache?": "Limpar cache?",
    "Temporary data will be removed. This won't affect your records.": "Os dados temporários serão removidos. Isso não afetará seus registros.",
    "Cache cleared successfully": "Cache limpo com sucesso",
    "We'll send you a link to reset your password.": "Enviaremos um link para redefinir sua senha.",
    "Your email": "Seu e-mail",
    "Send link": "Enviar link",
    "A link has been sent to your email": "Um link foi enviado para seu e-mail",
    "A verification email has been sent": "Um e-mail de verificação foi enviado",
    "Delete account?": "Excluir conta?",
    "This action is irreversible and you'll lose all your data.": "Esta ação é irreversível e você perderá todos os seus dados.",
    # Notifications config
    "Production Alerts": "Alertas de Produção",
    "Mortality threshold": "Limite de mortalidade",
    "Low production": "Baixa produção",
    "Production threshold": "Limite de produção",
    "Abnormal consumption": "Consumo anormal",
    "Alert when consumption varies significantly": "Alerta quando o consumo varia significativamente",
    "Reminders": "Lembretes",
    "Pending vaccinations": "Vacinações pendentes",
    "Remind scheduled vaccinations": "Lembre de vacinações programadas",
    "Low inventory": "Inventário baixo",
    "Alert when feed is running low": "Alerta quando a ração está acabando",
    "Summaries": "Resumos",
    "Daily summary": "Resumo diário",
    "Weekly summary": "Resumo semanal",
    "Receive a summary every Monday": "Receba um resumo toda segunda-feira",
    "Configuration saved": "Configuração salva",
    "Save configuration": "Salvar configuração",
    # Farm
    "Farm": "Granja",
    "Farms": "Granjas",
    "New Farm": "Nova Granja",
    "Edit Farm": "Editar Granja",
    "Delete farm?": "Excluir granja?",
    "Farm not found": "Granja não encontrada",
    "Owner": "Proprietário",
    "Capacity": "Capacidade",
    "Area": "Área",
    "Created date": "Data de Criação",
    "Collaborators": "Colaboradores",
    "Invite Collaborator": "Convidar Colaborador",
    "Code copied": "Código copiado",
    # Shed
    "Shed": "Galpão",
    "Sheds": "Galpões",
    "New Shed": "Novo Galpão",
    "Edit Shed": "Editar Galpão",
    "Delete shed?": "Excluir galpão?",
    "Current": "Atuais",
    "Birds": "Aves",
    "This tag already exists": "Esta etiqueta já existe",
    "Add product": "Adicionar produto",
    # Batch
    "Batch": "Lote",
    "New Batch": "Novo Lote",
    "Edit Batch": "Editar Lote",
    "Delete batch?": "Excluir lote?",
    "Finished": "Finalizado",
    "Batch Code": "Código do Lote",
    "Bird Type": "Tipo de Ave",
    "Breed/Genetic Line": "Raça/Linha Genética",
    "Initial Count": "Quantidade Inicial",
    "Current Birds": "Aves Atuais",
    "Entry Date": "Data de Entrada",
    "Entry Age": "Idade de Entrada",
    "Current Age": "Idade Atual",
    "Cost per Bird": "Custo por Ave",
    "Estimated Close": "Fechamento Estimado",
    "Survival Rate": "Taxa de Sobrevivência",
    "Accumulated Mortality": "Mortalidade Acumulada",
    "Accumulated Discards": "Descartes Acumulados",
    "Accumulated Sales": "Vendas Acumuladas",
    "Current average weight": "Peso médio atual",
    "Accumulated Consumption": "Consumo Acumulado",
    "Feed Conversion Ratio (FCR)": "Índice de Conversão Alimentar (ICA)",
    "Eggs Produced": "Ovos Produzidos",
    "Remaining Days": "Dias Restantes",
    "Important information": "Informação importante",
    "Change Status": "Alterar Status",
    "Batch closed successfully": "Lote fechado com sucesso",
    "Entry Age (days)": "Idade de Entrada (dias)",
    "Select batch": "Selecionar lote",
    # Health
    "Symptoms": "Sintomas",
    "Treatment": "Tratamento",
    "Prevention": "Prevenção",
    "Vaccine available": "Vacina disponível",
    "Mandatory notification": "Notificação obrigatória",
    "Preventable by vaccination": "Prevenível por vacinação",
    "Applied": "Aplicada",
    "Expired": "Vencida",
    "Upcoming": "Próxima",
    "Vaccine name": "Nome da vacina",
    "Vaccine batch (optional)": "Lote da vacina (opcional)",
    "Select vaccine from inventory": "Selecionar vacina do inventário",
    "Observations (optional)": "Observações (opcional)",
    "Treatment description": "Descrição do tratamento",
    "Medications": "Medicamentos",
    "Additional medications": "Medicamentos adicionais",
    "Dose": "Dose",
    "Duration (days)": "Duração (dias)",
    "Diagnosis": "Diagnóstico",
    "Observed symptoms": "Sintomas observados",
    "Responsible veterinarian": "Veterinário responsável",
    "Veterinarian name": "Nome do veterinário",
    "General observations": "Observações gerais",
    "Corrective actions": "Ações corretivas",
    "Compliant": "Conforme",
    "Non-compliant": "Não conforme",
    "Partial": "Parcial",
    "N/A": "N/A",
    "Write an observation (optional)": "Escreva uma observação (opcional)",
    "Schedule Vaccination": "Programar Vacinação",
    "Vaccine": "Vacina",
    "Application": "Aplicação",
    "You must select a batch": "Você deve selecionar um lote",
    "Disease Catalog": "Catálogo de Doenças",
    "Medicines": "Medicamentos",
    "Vaccines": "Vacinas",
    "Feed": "Ração",
    # Reports
    "Reports": "Relatórios",
    "Generate report": "Gerar relatório",
    "Generating report...": "Gerando relatório...",
    "Share PDF": "Compartilhar PDF",
    # Notifications
    "No notifications": "Sem notificações",
    # Mortality
    "Mortality": "Mortalidade",
    "Register mortality": "Registrar mortalidade",
    "Mortality rate": "Taxa de mortalidade",
    "Total mortality": "Mortalidade total",
    # Weight
    "Weight": "Peso",
    "Register weight": "Registrar peso",
    "Average weight": "Peso médio",
    # Feed/Water
    "Feeding": "Alimentação",
    "Register feeding": "Registrar alimentação",
    "Daily consumption": "Consumo diário",
    "Water": "Água",
    "Register water": "Registrar água",
    # Sales
    "No sales registered": "Sem vendas registradas",
    "No sales found": "Nenhuma venda encontrada",
    "Register first sale": "Registrar primeira venda",
    "Register new sale": "Registrar nova venda",
    "Delete sale?": "Excluir venda?",
    "Product type": "Tipo de produto",
    "Sale status": "Status da venda",
    "New Sale": "Nova Venda",
    "Edit Sale": "Editar Venda",
    # Costs
    "New Cost": "Novo Custo",
    "Edit Cost": "Editar Custo",
    # Inventory
    "Inventory": "Inventário",
    # Common additional
    "Ex: {value}": "Ex: {value}",
    "Error: {message}": "Erro: {message}",
    "Version {version}": "Versão {version}",
    "Error updating: {error}": "Erro ao atualizar: {error}",
    "Maximum {max} tags": "Máximo {max} etiquetas",
    "Password must be at least {count} characters": "A senha deve ter pelo menos {count} caracteres",
    "Minimum {count} characters": "Mínimo {count} caracteres",
    "Role updated to {role}": "Função atualizada para {role}",
    "Alert when mortality exceeds {threshold}%": "Alerta quando a mortalidade excede {threshold}%",
    "Alert when production falls below {threshold}%": "Alerta quando a produção cai abaixo de {threshold}%",
    "Receive a summary every day at 8:00 PM": "Receba um resumo todo dia às 20:00",
}

# ============================================================
# MAPEO DE PALABRAS INDIVIDUALES ESPAÑOL → PORTUGUÉS
# Para hacer sustitución en valores que no matchean completos
# ============================================================
WORD_MAP_ES_PT = [
    # Frases más largas primero
    ("Información Básica", "Informações Básicas"),
    ("Información Adicional", "Informações Adicionais"),
    ("Información Personal", "Informações Pessoais"),
    ("Información de Cuenta", "Informações da Conta"),
    ("Información de la aplicación", "Informações do aplicativo"),
    ("Correo electrónico", "E-mail"),
    ("correo electrónico", "e-mail"),
    ("Términos y Condiciones", "Termos e Condições"),
    ("términos y condiciones", "termos e condições"),
    ("Política de Privacidad", "Política de Privacidade"),
    ("Acciones Rápidas", "Ações Rápidas"),
    ("Estadísticas Generales", "Estatísticas Gerais"),
    ("Galpones Libres", "Galpões Disponíveis"),
    ("Lotes Activos", "Lotes Ativos"),
    ("Aves Totales", "Aves Totais"),
    ("Próximos a vencer", "Próximos a vencer"),
    ("Mortalidad elevada", "Mortalidade elevada"),
    ("Sin lotes activos", "Sem lotes ativos"),
    ("Sin galpones", "Sem galpões"),
    ("Sin lotes", "Sem lotes"),
    ("Sin conexión a internet", "Sem conexão com a internet"),
    ("Sin conexión", "Sem conexão"),
    ("Modo sin conexión", "Modo offline"),
    ("Cerrar Sesión", "Sair"),
    ("Iniciar Sesión", "Entrar"),
    ("inicio de sesión", "login"),
    ("sesión activa", "sessão ativa"),
    ("sesión ha expirado", "sessão expirou"),
    ("Buenos días", "Bom dia"),
    ("Buenas tardes", "Boa tarde"),
    ("Buenas noches", "Boa noite"),
    ("Tasa de mortalidad", "Taxa de mortalidade"),
    ("Tasa de Supervivencia", "Taxa de Sobrevivência"),
    ("Mortalidad total", "Mortalidade total"),
    ("Mortalidad Acumulada", "Mortalidade Acumulada"),
    ("Mortalidad", "Mortalidade"),
    ("Peso promedio", "Peso médio"),
    ("Consumo diario", "Consumo diário"),
    ("Consumo Acumulado", "Consumo Acumulado"),
    ("Índice Conversión", "Índice de Conversão"),
    ("Huevos Producidos", "Ovos Produzidos"),
    ("Días Restantes", "Dias Restantes"),
    ("Tipo de Ave", "Tipo de Ave"),
    ("Raza/Línea Genética", "Raça/Linha Genética"),
    ("Cantidad Inicial", "Quantidade Inicial"),
    ("Aves Actuales", "Aves Atuais"),
    ("Fecha de Ingreso", "Data de Entrada"),
    ("Fecha de Creación", "Data de Criação"),
    ("Fecha de registro", "Data de registro"),
    ("Edad al Ingreso", "Idade de Entrada"),
    ("Edad de Ingreso", "Idade de Entrada"),
    ("Edad Actual", "Idade Atual"),
    ("Costo por Ave", "Custo por Ave"),
    ("Cierre Estimado", "Fechamento Estimado"),
    ("Descartes Acumulados", "Descartes Acumulados"),
    ("Ventas Acumuladas", "Vendas Acumuladas"),
    ("Cambiar Estado", "Alterar Status"),
    ("Código del Lote", "Código do Lote"),
    ("Lote cerrado exitosamente", "Lote fechado com sucesso"),
    ("Seleccionar lote", "Selecionar lote"),
    ("Nuevo Lote", "Novo Lote"),
    ("Editar Lote", "Editar Lote"),
    ("Nuevo Galpón", "Novo Galpão"),
    ("Editar Galpón", "Editar Galpão"),
    ("Nueva Granja", "Nova Granja"),
    ("Editar Granja", "Editar Granja"),
    ("Nueva Venta", "Nova Venda"),
    ("Editar Venta", "Editar Venda"),
    ("Nuevo Costo", "Novo Custo"),
    ("Editar Costo", "Editar Custo"),
    ("Editar Perfil", "Editar Perfil"),
    ("Registrar mortalidad", "Registrar mortalidade"),
    ("Registrar peso", "Registrar peso"),
    ("Registrar alimentación", "Registrar alimentação"),
    ("Registrar agua", "Registrar água"),
    ("Registrar primera venta", "Registrar primeira venda"),
    ("Registrar nueva venta", "Registrar nova venda"),
    ("Registrado por", "Registrado por"),
    ("Generar reporte", "Gerar relatório"),
    ("Generando reporte...", "Gerando relatório..."),
    ("Compartir PDF", "Compartilhar PDF"),
    ("Sin notificaciones", "Sem notificações"),
    ("Sin ventas registradas", "Sem vendas registradas"),
    ("Aplicar filtros", "Aplicar filtros"),
    ("Limpiar filtros", "Limpar filtros"),
    ("Limpiar búsqueda", "Limpar busca"),
    ("Más opciones", "Mais opções"),
    ("Todos los tipos", "Todos os tipos"),
    ("Todos los estados", "Todos os estados"),
    ("Cambios sin guardar", "Alterações não salvas"),
    ("Algo salió mal", "Algo deu errado"),
    ("Ha ocurrido un error", "Ocorreu um erro"),
    ("Error del servidor", "Erro do servidor"),
    ("Datos no encontrados en cache", "Dados não encontrados no cache"),
    ("Tiempo de espera agotado", "Tempo de espera esgotado"),
    ("Credenciales inválidas", "Credenciais inválidas"),
    ("Próximamente", "Em breve"),
    ("Ir al inicio", "Ir ao início"),
    ("Cargando...", "Carregando..."),
    ("Cargando", "Carregando"),
    ("Información importante", "Informação importante"),
    ("Información", "Informações"),
    ("información", "informações"),
    ("Configuración guardada", "Configuração salva"),
    ("Configuración", "Configuração"),
    ("Guardar configuración", "Salvar configuração"),
    ("Zona de peligro", "Zona de perigo"),
    ("Seguridad", "Segurança"),
    ("Apariencia", "Aparência"),
    ("Modo oscuro", "Modo escuro"),
    ("Notificaciones push", "Notificações push"),
    ("Notificaciones", "Notificações"),
    ("Sonidos", "Sons"),
    ("Vibración", "Vibração"),
    ("Datos y Almacenamiento", "Dados e Armazenamento"),
    ("Limpiar caché", "Limpar cache"),
    ("Cambiar contraseña", "Alterar senha"),
    ("Verificar email", "Verificar e-mail"),
    ("Eliminar cuenta", "Excluir conta"),
    ("Enfermedades", "Doenças"),
    ("Enfermedad", "Doença"),
    ("enfermedad", "doença"),
    ("Síntomas observados", "Sintomas observados"),
    ("Síntomas", "Sintomas"),
    ("síntomas", "sintomas"),
    ("Tratamiento", "Tratamento"),
    ("tratamiento", "tratamento"),
    ("Prevención", "Prevenção"),
    ("prevención", "prevenção"),
    ("Vacunación", "Vacinação"),
    ("vacunación", "vacinação"),
    ("Vacunaciones", "Vacinações"),
    ("vacunaciones", "vacinações"),
    ("Bioseguridad", "Biossegurança"),
    ("bioseguridad", "biossegurança"),
    ("Biossegurança", "Biossegurança"),
    ("Observaciones generales", "Observações gerais"),
    ("Observaciones", "Observações"),
    ("observaciones", "observações"),
    ("Observación", "Observação"),
    ("observación", "observação"),
    ("Descripción", "Descrição"),
    ("descripción", "descrição"),
    ("Diagnóstico", "Diagnóstico"),
    ("diagnóstico", "diagnóstico"),
    ("Medicamentos adicionales", "Medicamentos adicionais"),
    ("Medicamentos", "Medicamentos"),
    ("medicamentos", "medicamentos"),
    ("Veterinario responsable", "Veterinário responsável"),
    ("Veterinario", "Veterinário"),
    ("veterinario", "veterinário"),
    ("Acciones correctivas", "Ações corretivas"),
    ("Cumple", "Conforme"),
    ("No cumple", "Não conforme"),
    ("Parcial", "Parcial"),
    ("No aplica", "Não se aplica"),
    ("Programar Vacunación", "Programar Vacinação"),
    ("Vacuna disponible", "Vacina disponível"),
    ("Notificación obligatoria", "Notificação obrigatória"),
    ("Prevenible por vacunación", "Prevenível por vacinação"),
    ("Aplicada", "Aplicada"),
    ("Vencida", "Vencida"),
    ("Próxima", "Próxima"),
    ("Pendiente", "Pendente"),
    ("Pendientes", "Pendentes"),
    ("Aprobados", "Aprovados"),
    ("Vacuna", "Vacina"),
    ("vacuna", "vacina"),
    ("Aplicación", "Aplicação"),
    ("Dosis", "Dose"),
    ("dosis", "dose"),
    ("Duración", "Duração"),
    ("duración", "duração"),
    ("Catálogo de Enfermedades", "Catálogo de Doenças"),
    ("Inventario", "Inventário"),
    ("inventario", "inventário"),
    ("Alimentos", "Ração"),
    ("alimentos", "ração"),
    ("Alimentación", "Alimentação"),
    ("alimentación", "alimentação"),
    ("Reportes", "Relatórios"),
    ("reportes", "relatórios"),
    ("Reporte", "Relatório"),
    ("reporte", "relatório"),
    ("Ventas", "Vendas"),
    ("ventas", "vendas"),
    ("Venta", "Venda"),
    ("venta", "venda"),
    ("Costos", "Custos"),
    ("costos", "custos"),
    ("Costo", "Custo"),
    ("costo", "custo"),
    ("Granja", "Granja"),
    ("granja", "granja"),
    ("Granjas", "Granjas"),
    ("granjas", "granjas"),
    ("Galpones", "Galpões"),
    ("galpones", "galpões"),
    ("Galpón", "Galpão"),
    ("galpón", "galpão"),
    ("Lotes", "Lotes"),
    ("lotes", "lotes"),
    ("Lote", "Lote"),
    ("lote", "lote"),
    ("Aves", "Aves"),
    ("aves", "aves"),
    ("Ave", "Ave"),
    ("ave", "ave"),
    ("Huevos", "Ovos"),
    ("huevos", "ovos"),
    ("Huevo", "Ovo"),
    ("huevo", "ovo"),
    ("Colaboradores", "Colaboradores"),
    ("colaboradores", "colaboradores"),
    ("Colaborador", "Colaborador"),
    ("colaborador", "colaborador"),
    ("Propietario", "Proprietário"),
    ("propietario", "proprietário"),
    ("Capacidad", "Capacidade"),
    ("capacidad", "capacidade"),
    ("Ocupación", "Ocupação"),
    ("ocupación", "ocupação"),
    ("Producción", "Produção"),
    ("producción", "produção"),
    ("Peso", "Peso"),
    ("peso", "peso"),
    ("Agua", "Água"),
    ("agua", "água"),
    ("Perfil", "Perfil"),
    ("perfil", "perfil"),
    ("Fecha", "Data"),
    ("fecha", "data"),
    ("Nombre", "Nome"),
    ("nombre", "nome"),
    ("Teléfono", "Telefone"),
    ("teléfono", "telefone"),
    ("Proveedor", "Fornecedor"),
    ("proveedor", "fornecedor"),
    ("Ubicación", "Localização"),
    ("ubicación", "localização"),
    ("Contraseña", "Senha"),
    ("contraseña", "senha"),
    ("Correo", "E-mail"),
    ("correo", "e-mail"),
    ("Resumen", "Resumo"),
    ("resumen", "resumo"),
    ("Detalles", "Detalhes"),
    ("detalles", "detalhes"),
    ("Inicio", "Início"),
    ("inicio", "início"),
    ("Gestión", "Gestão"),
    ("gestión", "gestão"),
    ("Estado", "Status"),
    ("estado", "status"),
    ("Activo", "Ativo"),
    ("activo", "ativo"),
    ("Activos", "Ativos"),
    ("activos", "ativos"),
    ("Inactivo", "Inativo"),
    ("inactivo", "inativo"),
    ("Finalizado", "Finalizado"),
    ("Cancelar", "Cancelar"),
    ("Eliminar", "Excluir"),
    ("eliminar", "excluir"),
    ("Continuar", "Continuar"),
    ("Confirmar", "Confirmar"),
    ("Aceptar", "Aceitar"),
    ("Guardar", "Salvar"),
    ("guardar", "salvar"),
    ("Editar", "Editar"),
    ("editar", "editar"),
    ("Cerrar", "Fechar"),
    ("cerrar", "fechar"),
    ("Reintentar", "Tentar novamente"),
    ("Buscar...", "Buscar..."),
    ("Buscar", "Buscar"),
    ("buscar", "buscar"),
    ("Volver", "Voltar"),
    ("volver", "voltar"),
    ("Filtrar", "Filtrar"),
    ("filtrar", "filtrar"),
    ("Limpiar", "Limpar"),
    ("limpiar", "limpar"),
    ("Descartar", "Descartar"),
    ("Todos", "Todos"),
    ("todos", "todos"),
    ("Salir", "Sair"),
    ("salir", "sair"),
    ("Éxito", "Sucesso"),
    ("éxito", "sucesso"),
    ("exitosamente", "com sucesso"),
    ("Error", "Erro"),
    ("error", "erro"),
    ("Sí", "Sim"),
    ("Total:", "Total:"),
    ("Total", "Total"),
    ("Rol", "Função"),
    ("Crear", "Criar"),
    ("crear", "criar"),
    ("Creada", "Criada"),
    ("creada", "criada"),
    ("Creado", "Criado"),
    ("creado", "criado"),
    ("Registrar", "Registrar"),
    ("registrar", "registrar"),
    ("Seleccionar", "Selecionar"),
    ("seleccionar", "selecionar"),
    ("Selecciona", "Selecione"),
    ("selecciona", "selecione"),
    ("Actualizar", "Atualizar"),
    ("actualizar", "atualizar"),
    ("actualizada", "atualizada"),
    ("actualizado", "atualizado"),
    ("actualización", "atualização"),
    ("Desconocido", "Desconhecido"),
    ("desconocido", "desconhecido"),
    ("Miembro desde", "Membro desde"),
    ("Foto", "Foto"),
    ("foto", "foto"),
    ("Galería", "Galeria"),
    ("galería", "galeria"),
    ("Idioma", "Idioma"),
    ("idioma", "idioma"),
    ("Soporte", "Suporte"),
    ("soporte", "suporte"),
    ("Ayuda", "Ajuda"),
    ("ayuda", "ajuda"),
    ("Sugerencia", "Sugestão"),
    ("sugerencia", "sugestão"),
    ("Acerca de", "Sobre"),
    ("Versión", "Versão"),
    ("versión", "versão"),
    ("Cuenta", "Conta"),
    ("cuenta", "conta"),
    ("Invitar", "Convidar"),
    ("invitar", "convidar"),
    ("Código", "Código"),
    ("código", "código"),
    ("copiado", "copiado"),
    ("Activar", "Ativar"),
    ("activar", "ativar"),
    ("Suspender", "Suspender"),
    ("suspender", "suspender"),
    ("Mantenimiento", "Manutenção"),
    ("mantenimiento", "manutenção"),
    ("Desinfección", "Desinfecção"),
    ("desinfección", "desinfecção"),
    ("Liberar", "Liberar"),
    ("liberar", "liberar"),
    ("Etiqueta", "Etiqueta"),
    ("etiqueta", "etiqueta"),
    ("Agregar", "Adicionar"),
    ("agregar", "adicionar"),
    ("producto", "produto"),
    ("Producto", "Produto"),
    ("Mínimo", "Mínimo"),
    ("mínimo", "mínimo"),
    ("Máximo", "Máximo"),
    ("máximo", "máximo"),
    ("caracteres", "caracteres"),
    ("mayúscula", "maiúscula"),
    ("minúscula", "minúscula"),
    ("número", "número"),
    ("carácter especial", "caractere especial"),
    ("Débil", "Fraca"),
    ("Media", "Média"),
    ("Fuerte", "Forte"),
    ("Vincular", "Vincular"),
    ("vincular", "vincular"),
    ("Reenviar", "Reenviar"),
    ("reenviar", "reenviar"),
    ("Enviar", "Enviar"),
    ("enviar", "enviar"),
    ("Enviado", "Enviado"),
    ("enviado", "enviado"),
    ("instrucciones", "instruções"),
    ("Alertas", "Alertas"),
    ("alertas", "alertas"),
    ("Alerta", "Alerta"),
    ("alerta", "alerta"),
    ("Umbral", "Limite"),
    ("umbral", "limite"),
    ("Recordatorios", "Lembretes"),
    ("recordatorios", "lembretes"),
    ("Resúmenes", "Resumos"),
    ("Diario", "Diário"),
    ("diario", "diário"),
    ("Semanal", "Semanal"),
    ("semanal", "semanal"),
    ("lunes", "segunda-feira"),
    ("días", "dias"),
    ("Días", "Dias"),
    ("horas", "horas"),
    ("semanas", "semanas"),
    ("Semana", "Semana"),
    ("semana", "semana"),
    ("Mes", "Mês"),
    ("mes", "mês"),
    ("Año", "Ano"),
    ("año", "ano"),
    ("Años", "Anos"),
    ("años", "anos"),
    ("Hoy", "Hoje"),
    ("hoy", "hoje"),
    ("Ayer", "Ontem"),
    ("ayer", "ontem"),
    ("Mañana", "Amanhã"),
    ("mañana", "amanhã"),
    ("Opcional", "Opcional"),
    ("opcional", "opcional"),
    ("Obligatorio", "Obrigatório"),
    ("obligatorio", "obrigatório"),
    ("obligatoria", "obrigatória"),
    ("Requerido", "Obrigatório"),
    ("requerido", "obrigatório"),
    ("requerida", "obrigatória"),
    ("Disponible", "Disponível"),
    ("disponible", "disponível"),
    ("Agotado", "Esgotado"),
    ("agotado", "esgotado"),
    ("Exportar", "Exportar"),
    ("exportar", "exportar"),
    ("Importar", "Importar"),
    ("importar", "importar"),
    ("Compartir", "Compartilhar"),
    ("compartir", "compartilhar"),
    ("Copiar", "Copiar"),
    ("copiar", "copiar"),
    ("Imprimir", "Imprimir"),
    ("imprimir", "imprimir"),
    ("Descargar", "Baixar"),
    ("descargar", "baixar"),
    ("Cargar", "Carregar"),
    ("cargar", "carregar"),
    ("Subir", "Enviar"),
    ("General", "Geral"),
    ("general", "geral"),
    ("Especial", "Especial"),
    ("especial", "especial"),
    ("Avanzado", "Avançado"),
    ("avanzado", "avançado"),
    ("Básico", "Básico"),
    ("básico", "básico"),
    ("Completo", "Completo"),
    ("completo", "completo"),
    ("Parcial", "Parcial"),
    ("parcial", "parcial"),
    ("Normal", "Normal"),
    ("normal", "normal"),
    ("Alto", "Alto"),
    ("alto", "alto"),
    ("Bajo", "Baixo"),
    ("bajo", "baixo"),
    ("Medio", "Médio"),
    ("medio", "médio"),
    ("Bueno", "Bom"),
    ("bueno", "bom"),
    ("Malo", "Ruim"),
    ("malo", "ruim"),
    ("Excelente", "Excelente"),
    ("excelente", "excelente"),
    ("Crítico", "Crítico"),
    ("crítico", "crítico"),
    ("Urgente", "Urgente"),
    ("urgente", "urgente"),
    ("Importante", "Importante"),
    ("importante", "importante"),
    ("Nuevo", "Novo"),
    ("nuevo", "novo"),
    ("Nueva", "Nova"),
    ("nueva", "nova"),
    ("Anterior", "Anterior"),
    ("anterior", "anterior"),
    ("Siguiente", "Seguinte"),
    ("siguiente", "seguinte"),
    ("Primero", "Primeiro"),
    ("primero", "primeiro"),
    ("Primera", "Primeira"),
    ("primera", "primeira"),
    ("Último", "Último"),
    ("último", "último"),
    ("Última", "Última"),
    ("última", "última"),
    ("Ninguno", "Nenhum"),
    ("ninguno", "nenhum"),
    ("Ninguna", "Nenhuma"),
    ("ninguna", "nenhuma"),
    ("Otro", "Outro"),
    ("otro", "outro"),
    ("Otra", "Outra"),
    ("otra", "outra"),
    ("Otros", "Outros"),
    ("otros", "outros"),
    ("Otras", "Outras"),
    ("otras", "outras"),
    ("Unidad", "Unidade"),
    ("unidad", "unidade"),
    ("Unidades", "Unidades"),
    ("unidades", "unidades"),
    ("Cantidad", "Quantidade"),
    ("cantidad", "quantidade"),
    ("Precio", "Preço"),
    ("precio", "preço"),
    ("Valor", "Valor"),
    ("valor", "valor"),
    ("Promedio", "Médio"),
    ("promedio", "médio"),
    ("Porcentaje", "Porcentagem"),
    ("porcentaje", "porcentagem"),
    ("Temperatura", "Temperatura"),
    ("Humedad", "Umidade"),
    ("humedad", "umidade"),
    ("Ventilación", "Ventilação"),
    ("ventilación", "ventilação"),
    ("Iluminación", "Iluminação"),
    ("iluminación", "iluminação"),
    ("Macho", "Macho"),
    ("Hembra", "Fêmea"),
    ("hembra", "fêmea"),
    ("Mixto", "Misto"),
    ("mixto", "misto"),
    ("Sano", "Saudável"),
    ("sano", "saudável"),
    ("Enfermo", "Doente"),
    ("enfermo", "doente"),
    ("Muerto", "Morto"),
    ("muerto", "morto"),
    ("Vivo", "Vivo"),
    ("vivo", "vivo"),
    ("Gramos", "Gramas"),
    ("gramos", "gramas"),
    ("Kilogramos", "Quilogramas"),
    ("kilogramos", "quilogramas"),
    ("Litros", "Litros"),
    ("litros", "litros"),
    ("Toneladas", "Toneladas"),
    ("toneladas", "toneladas"),
    ("Sacos", "Sacos"),
    ("sacos", "sacos"),
    ("Bandeja", "Bandeja"),
    ("bandeja", "bandeja"),
    ("Cartón", "Caixa"),
    ("cartón", "caixa"),
    ("Docena", "Dúzia"),
    ("docena", "dúzia"),
    ("Galón", "Galão"),
    ("galón", "galão"),
    # Más traducciones generales
    ("Ej:", "Ex:"),
    ("ej:", "ex:"),
    ("Borrador encontrado", "Rascunho encontrado"),
    ("Borrador restaurado", "Rascunho restaurado"),
    ("Borrador", "Rascunho"),
    ("borrador", "rascunho"),
    ("Factura", "Fatura"),
    ("factura", "fatura"),
    ("Recibo", "Recibo"),
    ("recibo", "recibo"),
    ("Concepto", "Conceito"),
    ("concepto", "conceito"),
    ("Descuento", "Desconto"),
    ("descuento", "desconto"),
    ("Subtotal", "Subtotal"),
    ("Rendimiento", "Rendimento"),
    ("rendimiento", "rendimento"),
    ("Cliente", "Cliente"),
    ("cliente", "cliente"),
    ("Documento", "Documento"),
    ("documento", "documento"),
    ("Mano de Obra", "Mão de Obra"),
    ("Energía", "Energia"),
    ("energía", "energia"),
    ("Transporte", "Transporte"),
    ("Administrativo", "Administrativo"),
    ("Depreciación", "Depreciação"),
    ("depreciación", "depreciação"),
    ("Financiero", "Financeiro"),
    ("financiero", "financeiro"),
    ("Stock Actual", "Estoque Atual"),
    ("Stock Mínimo", "Estoque Mínimo"),
    ("Stock Máximo", "Estoque Máximo"),
    ("Ajustar Stock", "Ajustar Estoque"),
    ("Stock", "Estoque"),
    ("stock", "estoque"),
    ("Vencimiento", "Vencimento"),
    ("vencimiento", "vencimento"),
    ("Bodega", "Depósito"),
    ("bodega", "depósito"),
    ("Estante", "Prateleira"),
    ("estante", "prateleira"),
    ("Balanza", "Balança"),
    ("balanza", "balança"),
    ("Amoníaco", "Amônia"),
    ("amoníaco", "amônia"),
    ("Cuarentena", "Quarentena"),
    ("cuarentena", "quarentena"),
    ("Clasificación", "Classificação"),
    ("clasificación", "classificação"),
    ("Postura", "Postura"),
    ("postura", "postura"),
    ("Aprovechamiento", "Aproveitamento"),
    ("aprovechamiento", "aproveitamento"),
    ("Sucios", "Sujos"),
    ("sucios", "sujos"),
    ("Pequeños", "Pequenos"),
    ("pequeños", "pequenos"),
    ("Medianos", "Médios"),
    ("medianos", "médios"),
    ("Grandes", "Grandes"),
    ("grandes", "grandes"),
    ("Extra grandes", "Extra grandes"),
    ("Jumbo", "Jumbo"),
    ("Rotos", "Quebrados"),
    ("rotos", "quebrados"),
    ("Roto", "Quebrado"),
    ("roto", "quebrado"),
    ("Agrietados", "Trincados"),
    ("agrietados", "trincados"),
    ("Método de pesaje", "Método de pesagem"),
    ("Método", "Método"),
    ("método", "método"),
    ("Coeficiente de variación", "Coeficiente de variação"),
    ("variación", "variação"),
    ("Pesaje", "Pesagem"),
    ("pesaje", "pesagem"),
    ("Detalle del Registro", "Detalhe do Registro"),
    ("Detalle del Item", "Detalhe do Item"),
    ("Detalle", "Detalhe"),
    ("detalle", "detalhe"),
    ("Motivo del ajuste", "Motivo do ajuste"),
    ("Motivo del rechazo", "Motivo da rejeição"),
    ("Motivo", "Motivo"),
    ("motivo", "motivo"),
    ("Rechazar", "Rejeitar"),
    ("rechazar", "rejeitar"),
    ("Rechazo", "Rejeição"),
    ("rechazo", "rejeição"),
    ("Restaurar", "Restaurar"),
    ("restaurar", "restaurar"),
    ("Ingrese", "Insira"),
    ("Ingresa", "Insira"),
    ("ingrese", "insira"),
    ("ingresa", "insira"),
    ("Ingrese el motivo", "Insira o motivo"),
    ("Debe ser un número válido", "Deve ser um número válido"),
    ("Debe estar entre", "Deve estar entre"),
    ("un número válido", "um número válido"),
    ("número válido", "número válido"),
    ("Valor inválido", "Valor inválido"),
    ("inválido", "inválido"),
    ("inválida", "inválida"),
    ("No hay registros", "Não há registros"),
    ("Sin datos", "Sem dados"),
    ("No definido", "Não definido"),
    ("Verificando...", "Verificando..."),
    ("Guardando...", "Salvando..."),
    ("Uniéndose...", "Ingressando..."),
    ("Tú", "Você"),
    ("Desde:", "Desde:"),
    ("Permisos", "Permissões"),
    ("permisos", "permissões"),
    ("Válido hasta", "Válido até"),
    ("válido hasta", "válido até"),
    ("Notas adicionales", "Notas adicionais"),
    ("notas adicionales", "notas adicionais"),
    ("notas especiales", "notas especiais"),
    ("evolución esperada", "evolução esperada"),
    ("Reacciones observadas", "Reações observadas"),
    ("reacciones observadas", "reações observadas"),
    ("Describe las acciones", "Descreva as ações"),
    ("Describe", "Descreva"),
    ("describe", "descreva"),
    ("acciones a implementar", "ações a implementar"),
    ("acciones", "ações"),
    ("Las operaciones serán limitadas", "As operações serão limitadas"),
    ("operaciones", "operações"),
    ("Operando normalmente", "Operando normalmente"),
    ("Operaciones suspendidas", "Operações suspensas"),
    ("Podrás operar normalmente", "Você poderá operar normalmente"),
    ("Esta acción es irreversible", "Esta ação é irreversível"),
    ("Debe especificar", "Deve especificar"),
    ("debe especificar", "deve especificar"),
    ("Ingrese un número válido", "Insira um número válido"),
    ("No hay items", "Não há itens"),
    ("items", "itens"),
    ("Item", "Item"),
    ("item", "item"),
    ("Editar Item", "Editar Item"),
    ("Lista", "Lista"),
    ("lista", "lista"),
    ("Por Vencer", "Próximo a Vencer"),
    ("número de documento", "número do documento"),
    ("9 dígitos", "9 dígitos"),
    ("Carnet de Extranjería", "RNE"),
    ("DNI", "CPF"),
    ("RUC", "CNPJ"),
    ("Bronquitis", "Bronquite"),
    ("bronquitis", "bronquite"),
    ("Ene", "Jan"),
    ("Feb", "Fev"),
    ("Abr", "Abr"),
    ("May", "Mai"),
    ("Ago", "Ago"),
    ("Sep", "Set"),
    ("Oct", "Out"),
    ("Nov", "Nov"),
    ("Dic", "Dez"),
]

# Mapeo de inglés a portugués para palabras individuales (fallback)
WORD_MAP_EN_PT = [
    ("mortality", "mortalidade"),
    ("Mortality", "Mortalidade"),
    ("production", "produção"),
    ("Production", "Produção"),
    ("vaccination", "vacinação"),
    ("Vaccination", "Vacinação"),
    ("biosecurity", "biossegurança"),
    ("Biosecurity", "Biossegurança"),
    ("disease", "doença"),
    ("Disease", "Doença"),
    ("symptom", "sintoma"),
    ("Symptom", "Sintoma"),
    ("treatment", "tratamento"),
    ("Treatment", "Tratamento"),
    ("prevention", "prevenção"),
    ("Prevention", "Prevenção"),
    ("vaccine", "vacina"),
    ("Vaccine", "Vacina"),
    ("inventory", "inventário"),
    ("Inventory", "Inventário"),
    ("report", "relatório"),
    ("Report", "Relatório"),
    ("batch", "lote"),
    ("Batch", "Lote"),
    ("shed", "galpão"),
    ("Shed", "Galpão"),
    ("farm", "granja"),
    ("Farm", "Granja"),
    ("bird", "ave"),
    ("Bird", "Ave"),
    ("egg", "ovo"),
    ("Egg", "Ovo"),
    ("weight", "peso"),
    ("Weight", "Peso"),
    ("feed", "ração"),
    ("Feed", "Ração"),
    ("water", "água"),
    ("Water", "Água"),
    ("sale", "venda"),
    ("Sale", "Venda"),
    ("cost", "custo"),
    ("Cost", "Custo"),
    ("register", "registrar"),
    ("Register", "Registrar"),
    ("select", "selecionar"),
    ("Select", "Selecionar"),
    ("search", "buscar"),
    ("Search", "Buscar"),
    ("create", "criar"),
    ("Create", "Criar"),
    ("delete", "excluir"),
    ("Delete", "Excluir"),
    ("update", "atualizar"),
    ("Update", "Atualizar"),
    ("save", "salvar"),
    ("Save", "Salvar"),
    ("cancel", "cancelar"),
    ("Cancel", "Cancelar"),
    ("confirm", "confirmar"),
    ("Confirm", "Confirmar"),
    ("accept", "aceitar"),
    ("Accept", "Aceitar"),
    ("edit", "editar"),
    ("close", "fechar"),
    ("Close", "Fechar"),
    ("loading", "carregando"),
    ("Loading", "Carregando"),
    ("error", "erro"),
    ("success", "sucesso"),
    ("required", "obrigatório"),
    ("Required", "Obrigatório"),
    ("optional", "opcional"),
    ("Optional", "Opcional"),
    ("total", "total"),
    ("Total", "Total"),
    ("available", "disponível"),
    ("Available", "Disponível"),
    ("active", "ativo"),
    ("Active", "Ativo"),
    ("inactive", "inativo"),
    ("Inactive", "Inativo"),
    ("pending", "pendente"),
    ("Pending", "Pendente"),
    ("approved", "aprovado"),
    ("Approved", "Aprovado"),
    ("expired", "vencido"),
    ("Expired", "Vencido"),
    ("applied", "aplicado"),
    ("Applied", "Aplicado"),
    ("completed", "concluído"),
    ("Completed", "Concluído"),
    ("cancelled", "cancelado"),
    ("Cancelled", "Cancelado"),
    ("scheduled", "programado"),
    ("Scheduled", "Programado"),
    ("daily", "diário"),
    ("Daily", "Diário"),
    ("weekly", "semanal"),
    ("Weekly", "Semanal"),
    ("monthly", "mensal"),
    ("Monthly", "Mensal"),
    ("yearly", "anual"),
    ("Yearly", "Anual"),
    ("today", "hoje"),
    ("Today", "Hoje"),
    ("yesterday", "ontem"),
    ("Yesterday", "Ontem"),
    ("tomorrow", "amanhã"),
    ("Tomorrow", "Amanhã"),
    ("days", "dias"),
    ("hours", "horas"),
    ("weeks", "semanas"),
    ("months", "meses"),
    ("years", "anos"),
    ("observations", "observações"),
    ("Observations", "Observações"),
    ("description", "descrição"),
    ("Description", "Descrição"),
    ("diagnosis", "diagnóstico"),
    ("Diagnosis", "Diagnóstico"),
    ("medications", "medicamentos"),
    ("Medications", "Medicamentos"),
    ("dose", "dose"),
    ("Dose", "Dose"),
    ("duration", "duração"),
    ("Duration", "Duração"),
    ("veterinarian", "veterinário"),
    ("Veterinarian", "Veterinário"),
    ("collaborator", "colaborador"),
    ("Collaborator", "Colaborador"),
    ("notification", "notificação"),
    ("Notification", "Notificação"),
    ("configuration", "configuração"),
    ("Configuration", "Configuração"),
    ("settings", "configurações"),
    ("Settings", "Configurações"),
    ("preferences", "preferências"),
    ("Preferences", "Preferências"),
    ("appearance", "aparência"),
    ("Appearance", "Aparência"),
    ("security", "segurança"),
    ("Security", "Segurança"),
    ("password", "senha"),
    ("Password", "Senha"),
    ("email", "e-mail"),
    ("account", "conta"),
    ("Account", "Conta"),
    ("profile", "perfil"),
    ("Profile", "Perfil"),
    ("user", "usuário"),
    ("User", "Usuário"),
    ("name", "nome"),
    ("Name", "Nome"),
    ("phone", "telefone"),
    ("Phone", "Telefone"),
    ("address", "endereço"),
    ("Address", "Endereço"),
    ("photo", "foto"),
    ("Photo", "Foto"),
    ("image", "imagem"),
    ("Image", "Imagem"),
    ("gallery", "galeria"),
    ("Gallery", "Galeria"),
    ("camera", "câmera"),
    ("Camera", "Câmera"),
    ("help", "ajuda"),
    ("Help", "Ajuda"),
    ("support", "suporte"),
    ("Support", "Suporte"),
    ("about", "sobre"),
    ("About", "Sobre"),
    ("version", "versão"),
    ("Version", "Versão"),
    ("manual", "manual"),
    ("Manual", "Manual"),
    ("guide", "guia"),
    ("Guide", "Guia"),
    ("questions", "perguntas"),
    ("Questions", "Perguntas"),
    ("feedback", "sugestão"),
    ("Feedback", "Sugestão"),
    ("suggestion", "sugestão"),
    ("Suggestion", "Sugestão"),
    ("invite", "convidar"),
    ("Invite", "Convidar"),
    ("code", "código"),
    ("Code", "Código"),
    ("role", "função"),
    ("Role", "Função"),
    ("status", "status"),
    ("Status", "Status"),
    ("type", "tipo"),
    ("Type", "Tipo"),
    ("category", "categoria"),
    ("Category", "Categoria"),
    ("quantity", "quantidade"),
    ("Quantity", "Quantidade"),
    ("price", "preço"),
    ("Price", "Preço"),
    ("amount", "valor"),
    ("Amount", "Valor"),
    ("unit", "unidade"),
    ("Unit", "Unidade"),
    ("temperature", "temperatura"),
    ("Temperature", "Temperatura"),
    ("humidity", "umidade"),
    ("Humidity", "Umidade"),
    ("ventilation", "ventilação"),
    ("Ventilation", "Ventilação"),
    ("lighting", "iluminação"),
    ("Lighting", "Iluminação"),
    ("male", "macho"),
    ("Male", "Macho"),
    ("female", "fêmea"),
    ("Female", "Fêmea"),
    ("mixed", "misto"),
    ("Mixed", "Misto"),
    ("healthy", "saudável"),
    ("Healthy", "Saudável"),
    ("sick", "doente"),
    ("Sick", "Doente"),
    ("dead", "morto"),
    ("Dead", "Morto"),
    ("alive", "vivo"),
    ("Alive", "Vivo"),
    ("grams", "gramas"),
    ("kilograms", "quilogramas"),
    ("liters", "litros"),
    ("tons", "toneladas"),
    ("bags", "sacos"),
    ("tray", "bandeja"),
    ("dozen", "dúzia"),
    ("gallon", "galão"),
]

# ============================================================
# TRADUCCIONES DIRECTAS POR CLAVE (key → pt_value)
# Para casos que no se pueden resolver con mapeo de palabras
# ============================================================
DIRECT_KEY_TRANSLATIONS = {
    "appTitle": "Smart Granja Aves Pro",
    "commonSearch": "Buscar...",
    "commonApplyFilters": "Aplicar filtros",
    "commonApplyFiltersBtn": "Aplicar filtros",
    "commonFilter": "Filtrar",
    "commonAll": "Todos",
    "commonDiscard": "Descartar",
    "commonTotal": "Total:",
    "commonRegisteredBy": "Registrado por",
    "commonRegister": "Registrar",
    "commonPrevious": "Anterior",
    "commonSaving": "Salvando...",
    "commonVerifyConnection": "Verifique sua conexão com a internet",
    "commonViewAll": "Ver Todos",
    "commonMaintShort": "Manut.",
    "commonNotDefined": "Não definido",
    "commonMustBeValidNumber": "Deve ser um número válido",
    "commonMustBeBetween": "Deve estar entre {min} e {max}",
    "commonEnterValidNumber": "Insira um número válido",
    "commonVerifying": "Verificando...",
    "commonJoining": "Ingressando...",
    "commonYouTag": "Você",
    "commonSince": "Desde: {date}",
    "commonPermissions": "Permissões",
    "commonValidUntil": "Válido até {date}",
    "commonEnterReason": "Insira o motivo",
    "commonType": "Tipo",
    "commonInvalidValue": "Valor inválido",
    "commonNoRecordsWithFilters": "Não há registros com estes filtros",
    "commonNoData": "Sem dados",
    "commonRestoreBtn": "Restaurar",
    "commonDiscardBtn": "Descartar",
    "authMinChars": "Mínimo 8 caracteres",
    "authLinkButton": "Vincular",
    "authPasswordMinLengthValidator": "Mínimo {count} caracteres",
    "settingsConfigureAlerts": "Configurar alertas",
    "editProfileTitle": "Editar Perfil",
    "notifAbnormalConsumption": "Consumo anormal",
    "farmArea": "Área",
    "farmCollaborators": "Colaboradores",
    "farmCodeCopied": "Código copiado",
    "farmNotes": "Notas",
    "farmActivateInfo": "Você poderá operar normalmente.",
    "farmSuspend": "Suspender",
    "farmMaintenanceInfo": "As operações serão limitadas.",
    "farmDeleteIrreversible": "Esta ação é irreversível:",
    "farmDraftFound": "Rascunho encontrado",
    "farmStatusActiveDesc": "Operando normalmente",
    "farmStatusInactiveDesc": "Operações suspensas",
    "farmBirds": "aves",
    "farmOfTotal": "de {total}",
    "farmTemperature": "Temperatura",
    "shedBirds": "Aves",
    "shedMaxTags": "Máximo {max} etiquetas",
    "shedScale": "Balança",
    "shedTemperatureSensor": "Temperatura",
    "shedCO2Sensor": "CO2",
    "shedAmmoniaSensor": "Amônia",
    "shedDisinfectionInfo": "As operações serão limitadas.",
    "shedMustSpecifyQuarantine": "Deve especificar o motivo da quarentena",
    "shedBirdsCount": "{current} / {max} aves",
    "batchBirdType": "Tipo de Ave",
    "batchAccumulatedDiscards": "Descartes Acumulados",
    "batchAccumulatedConsumption": "Consumo Acumulado",
    "batchEnterValidNumber": "Insira um número válido",
    "healthApplied": "Aplicada",
    "healthExpired": "Vencida",
    "healthUpcoming": "Próxima",
    "healthVaccineNameHint": "Ex: Newcastle + Bronquite",
    "healthVaccineBatchHint": "Ex: LOT123456",
    "healthObservationsHint": "Reações observadas, notas especiais, etc.",
    "healthMedications": "Medicamentos",
    "healthMedicationsHint": "Ex: Enrofloxacina + Vitaminas A, D, E",
    "healthDoseHint": "Ex: 1ml/L",
    "healthDurationHint": "Ex: 5",
    "healthDiagnosis": "Diagnóstico",
    "healthGeneralObservationsHint": "Notas adicionais, evolução esperada, etc.",
    "healthCorrectiveActionsHint": "Descreva as ações a implementar…",
    "healthPartial": "Parcial",
    "healthCritical": "Crítica",
    "healthSevere": "Grave",
    "healthModerate": "Moderada",
    "healthMild": "Leve",
    "healthChecklist": "Checklist",
    "healthRecordDetail": "Detalhe do Registro",
    "salesClient": "Cliente",
    "salesDocument": "Documento",
    "salesSubtotal": "Subtotal",
    "salesCarcassYield": "Rendimento de carcaça",
    "salesDiscount": "Desconto",
    "salesTotalAmount": "TOTAL",
    "salesSold": "Vendida",
    "salesClientNameHint": "Ex: João Silva",
    "salesDni": "CPF",
    "salesRuc": "CNPJ",
    "salesForeignCard": "RNE",
    "salesDocNumber": "Número do documento",
    "salesPhoneHint": "9 dígitos",
    "salesDraftFound": "Rascunho encontrado",
    "salesDraftRestored": "Rascunho restaurado",
    "salesEditLabel": "Editar",
    "salesBirdCountHint": "Ex: 100",
    "salesYield": "Rendimento",
    "costConcept": "Conceito",
    "costInvoiceNumber": "Nº Fatura",
    "costTypeLabor": "Mão de Obra",
    "costTypeEnergy": "Energia",
    "costTypeMedicine": "Medicamento",
    "costTypeTransport": "Transporte",
    "costTypeAdmin": "Administrativo",
    "costTypeDepreciation": "Depreciação",
    "costTypeFinancial": "Financeiro",
    "costDraftFound": "Rascunho encontrado",
    "costInvoiceNumberLabel": "Número da Fatura/Recibo",
    "costInvoiceHint": "F001-00001234",
    "costFormStepType": "Tipo",
    "costConceptLabel": "Conceito do gasto",
    "costEnterConcept": "Insira o conceito do gasto",
    "costRejectReasonLabel": "Motivo da rejeição",
    "costEnterRejectReason": "Insira um motivo de rejeição",
    "costRejectBtn": "Rejeitar",
    "costTotalCount": "Total",
    "costRegisteredBy": "Registrado por",
    "inventoryItemDetail": "Detalhe do Item",
    "inventoryAdjustStock": "Ajustar Estoque",
    "inventoryItemNotFound": "Item não encontrado",
    "inventoryBasic": "Básico",
    "inventoryCodeSku": "Código/SKU (opcional)",
    "inventoryCodeHint": "Ex: ALI-001",
    "inventoryCurrentStock": "Estoque Atual",
    "inventoryMinStock": "Estoque Mínimo",
    "inventoryMaxStock": "Estoque Máximo",
    "inventoryOptional": "Opcional",
    "inventoryStorageHint": "Ex: Depósito A, Prateleira 3",
    "inventoryExpiration": "Vencimento",
    "inventoryAdjustReason": "Motivo do ajuste",
    "inventoryStockAdjusted": "Estoque ajustado corretamente",
    "inventoryConfirmDefault": "Confirmar",
    "inventoryCancelDefault": "Cancelar",
    "inventoryEnterValidNumber": "Insira um número válido maior que 0",
    "inventoryNoItems": "Não há itens que correspondam aos filtros",
    "inventoryEditItem": "Editar Item",
    "inventoryList": "Lista",
    "inventoryStockSummary": "Estoque",
    "inventoryTotalItems": "Total de Itens",
    "inventoryExpiringSoon": "Próximo a Vencer",
    "inventoryRegisteredBy": "Registrado por",
    "inventoryItemFormType": "Tipo",
    "inventoryItemFormBasic": "Básico",
    "inventoryItemFormStock": "Estoque",
    "weightMinHint": "Ex: 2200",
    "weightMethod": "Método de pesagem",
    "weightMethodLabel": "Método de pesagem",
    "weightCoefficientVariation": "Coeficiente de variação",
    "productionClassification": "Classificação",
    "productionEggsHint": "Ex: 850",
    "productionSmallEggs": "Pequenos (S) - 43-53g",
    "productionLayingIndicator": "Indicador de Postura",
    "productionDirty": "Sujos",
    "productionTotalClassified": "Total classificados",
    "productionUtilization": "Aproveitamento",
    "monthJan": "Jan",
    "monthFeb": "Fev",
    "monthMar": "Mar",
    "monthApr": "Abr",
    "monthMay": "Mai",
    "monthJun": "Jun",
    "monthJul": "Jul",
    "monthAug": "Ago",
    "monthSep": "Set",
    "monthOct": "Out",
    "monthNov": "Nov",
    "monthDec": "Dez",
    # === BATCH 2: 230 claves restantes ===
    "batchApplyFiltersOrClose": "{hasFilters, select, true{Aplicar filtros} other{Fechar}}",
    "batchAttention": "Atenção",
    "batchBirdType": "Tipo de Ave",
    "batchCannotBeNegative": "Não pode ser negativo",
    "batchChartsConsumption": "Gráficos de Consumo",
    "batchCloseIrreversible": "Ação irreversível",
    "batchClosePopulation": "População",
    "batchClosureData": "Dados do Encerramento",
    "batchClosureNotes": "Notas do Encerramento",
    "batchClosureReason": "Motivo do Encerramento",
    "batchConfirmExitDesc": "Os dados do formulário serão perdidos",
    "batchConsumptionHistory": "Histórico de consumo",
    "batchCreateSuccessDetail": '"{code}" está pronto para gerenciar',
    "batchCycleProgress": "Progresso do ciclo",
    "batchDayOfCycle": "Dia {day} de {total}",
    "batchDeleteWarning": "Esta ação não pode ser desfeita",
    "batchFoodConsumption": "Consumo de Alimento",
    "batchFormAgeAtEntry": "Idade na entrada",
    "batchFormConsumptionSubtitle": "Registre o consumo de alimento",
    "batchFormDiscardReason": "Motivo do descarte",
    "batchFormLayingIndicator": "Indicador de postura",
    "batchFormMortalityDescriptionHint": "Descreva as circunstâncias...",
    "batchFormRecommendation": "Recomendação",
    "batchFormUtilization": "Utilização",
    "batchHistoryConsumption": "Histórico de Consumo",
    "batchPostureEvolution": "Evolução da % de postura ao longo do tempo",
    "batchReasonForState": "Motivo de {status}",
    "batchRecordingDiscard": "Registrando descarte...",
    "batchRequiresAttention": "Requer Atenção",
    "batchShareBirdsFormat": "{current} de {total}",
    "batchStandardComparison": "Comparação com Padrão",
    "batchStepOf": "Passo {current} de {total}",
    "batchTimePeriod": "Período de tempo",
    "batchTransferReason": "Motivo da transferência",
    "batchTypeDucksDesc": "Patos para carne",
    "batchTypeTurkeysDesc": "Perus para carne",
    "batchWaitForProcess": "Aguarde o término do processo",
    "batchWaitProcess": "Aguarde o término do processo atual",
    "bioChecklistProgress": "{evaluated} de {total} avaliados",
    "bioChecklistTapToEvaluate": "Toque para avaliar",
    "bioExitInProgress": "Você tem uma inspeção em andamento. Se sair agora, perderá as alterações.",
    "bioInspectionExitMessage": "Você tem uma inspeção em andamento. Se sair agora, perderá as alterações.",
    "bioInspectionMinEvaluation": "Avaliação mínima",
    "bioLastInspection": "Última inspeção:",
    "bioStepLocationTitle": "Onde será realizada a inspeção?",
    "bioSummaryCriticalItems": "Itens críticos não cumpridos",
    "bioSummaryRisk": "Risco {level} · {evaluated} de {total} avaliados",
    "birdDescPato": "Patos para carne",
    "birdDescPavo": "Perus para carne",
    "birdTypeBroiler": "Frango de Corte",
    "chartsConsumptionTitle": "Gráficos de Consumo",
    "chartsGraphsAppearWhenData": "Os gráficos aparecerão quando houver registros de consumo",
    "chartsMortalityCausesSubtitle": "Distribuição por motivo principal",
    "chartsMortalityDistributionCauseTitle": "Distribuição por Causa",
    "chartsProductionTooltipPosture": "{emoji} {date}\n{percentage}% de postura",
    "chartsWeightComparisonTitle": "Comparação com Padrão",
    "chartsWeightTooltipComparison": "📊 Real: {real} kg\n📈 Padrão: {standard} kg\n{emoji} Dif: {sign}{diff} kg",
    "chartsWeightTooltipEvolution": "📈 Evolução\n📅 {date}\n⚖️ {weight} kg\n🐣 Dia {age}",
    "chartsWeightUniformityTitle": "Uniformidade do Lote",
    "clientDocHintGeneral": "Número do documento",
    "commonAttention": "Atenção",
    "commonProcessing": "Processando...",
    "commonVerifying": "Verificando...",
    "consumptionRegisteredDetail": "{amount} kg de {type}",
    "costCategoryDistribution": "Gastos de Distribuição",
    "costCategoryPersonnel": "Gastos de Pessoal",
    "costTypeTransportDesc": "Logística e mobilização",
    "costValidateApprovalNotRequired": "Este gasto não requer aprovação",
    "costoAutoFillConcept": "Compra de {name}",
    "costoDeleteWarning": "Esta ação não pode ser desfeita.",
    "costoDetailDeleteWarning": "Esta ação não pode ser desfeita.",
    "dateFormatDayOfMonthYearTime": "{day} de {month} {year} • {time}",
    "detailCvCoefficient": "Coef. Variação (CV)",
    "eggClassSmall": "Pequeno",
    "enumCausaMortDepredacion": "Predação",
    "enumCausaMortDescDepredacion": "Ataques de animais",
    "enumCausaMortDescDesnutricion": "Falta de nutrientes",
    "enumCausaMortDescVejez": "Fim da vida produtiva",
    "enumCausaMortDesnutricion": "Desnutrição",
    "enumMetodoPesajeDescManual": "Manual com balança",
    "enumTipoAlimentoCrecimiento": "Crescimento",
    "enumTipoAvePolloEngorde": "Frango de Corte",
    "farmContactDataTitle": "Dados de contato",
    "farmContactInfoDesc": "Dados de contato para comunicação",
    "farmHaveInvitation": "Tem um convite?",
    "farmInvitationSubject": "Convite para {farmName}",
    "farmLeaveAction": "Sair",
    "farmOverpopulationDetected": "Superpopulação detectada",
    "farmRoleViewOnly": "Somente visualização de dados",
    "farmStatusActiveDesc": "Operando normalmente",
    "farmSuspendConfirm": "Suspender \"{name}\"?",
    "farmSuspendConfirmMsg": "Suspender \"{name}\"?",
    "feedTypeGrower": "Crescimento",
    "granjaStatusOperating": "Operando normalmente",
    "healthAbUseGrowthPromoter": "Promotor de Crescimento",
    "healthActionCheckDrinkers": "Verificar funcionamento dos bebedouros",
    "healthActionCheckFoodAccess": "Verificar acesso ao alimento",
    "healthActionCheckFoodQuality": "Revisar qualidade do alimento",
    "healthActionConsultNutritionist": "Consultar nutricionista",
    "healthActionInstallNets": "Instalar redes de proteção",
    "healthActionPestControl": "Implementar controle de pragas",
    "healthActionRepairEquipment": "Reparar equipamentos danificados",
    "healthActionReviewGrowthProgram": "Revisar programa de crescimento",
    "healthBioCatFeedDesc": "Armazenamento e qualidade",
    "healthBioCatPersonnel": "Acesso de Pessoal",
    "healthBioCatPersonnelDesc": "Controle de entrada e vestimenta",
    "healthBioCatPestControl": "Controle de Pragas",
    "healthBioCatRecordsDesc": "Documentação e rastreabilidade",
    "healthBioCatVehicles": "Acesso de Veículos",
    "healthBioCatVehiclesDesc": "Controle de veículos e equipamentos",
    "healthBioCatWaterDesc": "Potabilidade e cloração",
    "healthBirdTypeBroiler": "Frango de Corte",
    "healthBirdTypeTurkeyMeat": "Peru de Corte",
    "healthDiseaseCatEnvironmentalDesc": "Causadas por fatores ambientais",
    "healthMortalityMalnutrition": "Desnutrição",
    "healthMortalityMalnutritionDesc": "Falta de nutrientes",
    "healthMortalityOldAgeDesc": "Fim da vida produtiva",
    "healthMortalityPredation": "Predação",
    "healthMortalityPredationDesc": "Ataques de animais",
    "healthRouteIntramuscular": "Injeção IM",
    "healthRouteOcularDesc": "Gota no olho",
    "healthRouteOralDesc": "Administração por via oral",
    "healthRouteSubcutaneous": "Injeção SC",
    "healthRouteWingDesc": "Punção na membrana da asa",
    "healthSeveritySevereDesc": "Alto impacto, requer ação imediata",
    "historialAllCauses": "Todas as causas",
    "historialAllMethods": "Todos os métodos",
    "historialAllPostures": "Todas as posturas",
    "historialChartsAppearConsumption": "Os gráficos aparecerão quando houver registros de consumo",
    "historialConsumptionHistory": "Histórico de consumo",
    "historialNoConsumptionRecords": "Sem registros de consumo",
    "historialNoEventsRecords": "Histórico de eventos",
    "historialPostureRange": "Faixa de postura",
    "homeInvAttention": "Atenção: {details}",
    "homeWhatsappCollaboration": "Colaboração ou aliança comercial",
    "homeWhatsappContact": "Fale conosco pelo WhatsApp",
    "homeWhatsappHaveIdea": "Tenho uma ideia para melhorar o app",
    "homeWhatsappSuggestImprovement": "Sugerir uma melhoria",
    "invFilterMovements": "Filtrar movimentos",
    "invItemTypeSupplyDesc": "Material de cama, embalagens, etc.",
    "invLastMovements": "Últimos Movimentos",
    "invMoveDonation": "Doação",
    "invMoveDonationDesc": "Entrada por doação",
    "invMoveGeneralUseDesc": "Saída por uso operacional",
    "invMovePurchaseDesc": "Entrada por aquisição",
    "invMoveReturn": "Devolução",
    "invMoveReturnDesc": "Entrada por devolução de uso",
    "invMoveTreatmentDesc": "Saída por aplicação de medicamento",
    "invMovementsOfItem": "Movimentos: {item}",
    "invMovementsTitle": "Movimentos",
    "invNoMovements": "Sem movimentos",
    "invNoMovementsRegistered": "Sem movimentos registrados",
    "invNoMovementsWithFilters": "Não há movimentos com estes filtros",
    "invNoMovementsYet": "Não há movimentos registrados ainda",
    "invTabMovements": "Movimentos",
    "loteAttention": "Atenção",
    "loteProgressCycle": "Progresso do ciclo",
    "mortalityCauseMalnutrition": "Desnutrição",
    "mortalityCausePredation": "Predação",
    "mortalityImpactMessage": "O evento registrado tem um impacto de {percent}% e requer atenção imediata.",
    "notifAllCaughtUp": "Tudo em dia!",
    "orderStatusInPreparation": "Em Preparação",
    "orderStatusInPreparationDesc": "Pedido sendo preparado",
    "orderStatusReadyToShipDesc": "Preparado para envio",
    "perfilSyncing": "Sincronizando",
    "productionLayingIndicator": "Indicador de Postura",
    "purchaseOf": "Compra de {name}",
    "reportGenerating": "Gerando...",
    "reportPdfHeaderCosts": "RELATÓRIO DE CUSTOS",
    "reportPdfHeaderProduction": "RELATÓRIO DE PRODUÇÃO",
    "reportPdfHeaderSales": "RELATÓRIO DE VENDAS",
    "reportPdfLabelBirdType": "Tipo de Ave",
    "reportPdfSectionBatchInfo": "INFORMAÇÃO DO LOTE",
    "reportPdfSectionProductionIndicators": "INDICADORES DE PRODUÇÃO",
    "reportTypeExecutiveDesc": "Visão consolidada de indicadores chave",
    "reportTypeProfitabilityDesc": "Análise de rentabilidade e margens",
    "reportsPeriodDateRange": "{start} a {end}",
    "reportsPeriodSameMonth": "{dayStart} a {dayEnd} de {month} {year}",
    "reportsPeriodSameYear": "{dayStart} de {monthStart} a {dayEnd} de {monthEnd}, {year}",
    "saleEggClassSmall": "Pequeno",
    "saleStatusInPreparation": "Em Preparação",
    "saleStatusInTransitDesc": "A caminho do cliente",
    "saleStatusReadyToShip": "Pronta para Despacho",
    "saleStatusReadyToShipDesc": "Pronta para entregar",
    "saleStatusReturnedDesc": "Devolvida pelo cliente",
    "saleUnitBagDesc": "Saco de 50 kg",
    "saludBioCompliant": "Cumprimento correto.",
    "saludBioNonCompliant": "Não conformidade detectada.",
    "saludCheckCompliance": "Cumprimento correto.",
    "saludCheckNonCompliance": "Não conformidade detectada.",
    "saludDialogProcessing": "Processando...",
    "saludEmptyTitle": "Sem registros de saúde",
    "saludRecordsTitle": "Registros de Saúde",
    "saludVacTableAppAge": "Idade de aplicação",
    "saludVacTableNextApp": "Próxima aplicação",
    "semanticsHealthRecord": "Registro de saúde, {diagnosis}, {date}, {status}",
    "semanticsInventoryMovement": "Movimento {type}, {direction} de {quantity} {units}",
    "shedEnvironmentalAlertHelp": "Os valores ambientais configurados serão usados para gerar alertas automáticos quando as condições reais estiverem fora da faixa especificada.",
    "shedEventCreation": "Criação",
    "shedHeatingSystem": "Sistema de Aquecimento",
    "shedMustBePositiveNumber": "Deve ser um número positivo",
    "shedReleaseConfirm": "Liberar \"{name}\"?",
    "shedSensorsEquipment": "Sensores e Equipamentos",
    "shedStatusActiveDesc": "Operação normal habilitada",
    "shedSuspendConfirm": "Suspender \"{name}\"?",
    "syncChangesPending": "Há alterações a sincronizar",
    "syncForceSync": "Forçar sincronização",
    "syncJustNow": "Agora mesmo",
    "syncLastSync": "Última sincronização",
    "syncTitle": "Sincronização e Dados",
    "treatStepDiagMinLength": "Deve ter pelo menos 5 caracteres",
    "treatStepTreatmentMinLength": "Deve ter pelo menos 5 caracteres",
    "vacAgeApplication": "Idade de aplicação",
    "vacAgeInvalid": "A idade deve ser um número maior que 0",
    "vacNextApplication": "Próxima aplicação",
    "vacRouteLabel": "Via de aplicação *",
    "vacRouteRequired": "Via de aplicação *",
    "validateEggRateHigh": "A taxa de postura de {rate}% parece muito alta. Verifique os dados.",
    "ventaClientData": "Dados do Cliente",
    "ventaClientDocNumber": "Número do documento",
    "ventaClientDocument": "Número do documento *",
    "ventaDateOfLabel": "{day} de {month} {year} • {time}",
    "ventaReceiptTitle": "COMPROVANTE DE VENDA",
    "ventaShareReceiptTitle": "📋 COMPROVANTE DE VENDA",
    "ventaStepClientTitle": "Dados do Cliente",
    "ventaWhatToSell": "O que deseja vender?",
    "weighMethodDescManual": "Manual com balança",
    "weightCvRecommendedTitle": "Valores recomendados de CV:",
    "whatsappCollaboration": "Olá! Estou interessado em uma colaboração com Smart Granja Aves.",
    "whatsappMsgCollab": "Olá! Estou interessado em uma colaboração com Smart Granja Aves.",
    "notifInventoryMovement": "Movimento",
}


def _restore_placeholders(translated, original, original_placeholders):
    """Ensure translated string has the same placeholders as the original."""
    import re as _re
    translated_placeholders = _re.findall(r'\{(\w+)\}', translated)
    
    # If placeholders match, we're good
    if set(translated_placeholders) == set(original_placeholders):
        return translated
    
    # If no placeholders in original, return as-is
    if not original_placeholders:
        return translated
    
    # Try to map translated placeholders back to originals
    # by detecting which ones changed
    for orig_ph in original_placeholders:
        if "{" + orig_ph + "}" not in translated:
            # The placeholder was translated - we need to find and restore it
            # Check common translations of placeholder names
            for trans_ph in translated_placeholders:
                if trans_ph not in original_placeholders:
                    translated = translated.replace("{" + trans_ph + "}", "{" + orig_ph + "}")
                    translated_placeholders.remove(trans_ph)
                    break
    
    return translated


def translate_value(key, es_val, en_val):
    """Traduce un valor al portugués."""
    import re as _re
    
    # Si es el locale, cambiamos
    if key == '@@locale':
        return 'pt'
    
    # Primero intentamos mapeo directo por clave
    if key in DIRECT_KEY_TRANSLATIONS:
        return DIRECT_KEY_TRANSLATIONS[key]
    
    # Extraer placeholders originales del español para preservarlos
    original_placeholders = _re.findall(r'\{(\w+)\}', es_val)
    
    # Luego intentamos mapeo exacto del inglés
    if en_val in EN_TO_PT:
        result = EN_TO_PT[en_val]
        # Restaurar placeholders originales
        return _restore_placeholders(result, es_val, original_placeholders)
    
    # Luego intentamos mapeo exacto del español
    if es_val in ES_TO_PT:
        result = ES_TO_PT[es_val]
        return _restore_placeholders(result, es_val, original_placeholders)
    
    # Proteger placeholders antes de sustituir palabras
    protected = es_val
    placeholder_map = {}
    for i, ph in enumerate(original_placeholders):
        token = f"__PH{i}__"
        protected = protected.replace("{" + ph + "}", token)
        placeholder_map[token] = "{" + ph + "}"
    
    # Intentar traducir por sustitución de palabras desde el español
    result = protected
    for es_word, pt_word in WORD_MAP_ES_PT:
        if es_word in result:
            result = result.replace(es_word, pt_word)
    
    # Restaurar placeholders
    for token, original in placeholder_map.items():
        result = result.replace(token, original)
    
    # Si cambió algo, retornar el resultado
    if result != es_val:
        return result
    
    # Intentar traducir por sustitución de palabras desde el inglés
    if en_val and en_val != es_val:
        # Protect English placeholders too
        en_placeholders = _re.findall(r'\{(\w+)\}', en_val)
        protected_en = en_val
        en_ph_map = {}
        for i, ph in enumerate(en_placeholders):
            token = f"__EPH{i}__"
            protected_en = protected_en.replace("{" + ph + "}", token)
            en_ph_map[token] = "{" + ph + "}"
        
        result = protected_en
        for en_word, pt_word in WORD_MAP_EN_PT:
            if en_word in result:
                result = result.replace(en_word, pt_word)
        
        # Restore English placeholders
        for token, original in en_ph_map.items():
            result = result.replace(token, original)
        
        if result != en_val:
            return result
    
    # Fallback: devolver el valor español (mejor que nada)
    return es_val


def main():
    pt_data = {}
    
    # Iterar manteniendo el orden del archivo español
    for key in es_data:
        if key == '@@locale':
            pt_data['@@locale'] = 'pt'
            continue
        
        # Copiar metadata tal cual
        if key.startswith('@'):
            pt_data[key] = es_data[key]
            continue
        
        # Traducir valores
        es_val = es_data[key]
        en_val = en_data.get(key, es_val)
        pt_val = translate_value(key, es_val, en_val)
        pt_data[key] = pt_val
    
    # Escribir el archivo
    output_path = os.path.join(L10N_DIR, 'app_pt.arb')
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(pt_data, f, ensure_ascii=False, indent=2)
    
    # Estadísticas
    keys = [k for k in pt_data if not k.startswith('@')]
    translated = 0
    untranslated = 0
    for k in keys:
        es_val = es_data.get(k, '')
        if pt_data[k] != es_val:
            translated += 1
        else:
            untranslated += 1
    
    print(f"[OK] Archivo generado: {output_path}")
    print(f"Total claves: {len(keys)}")
    print(f"Traducidas: {translated}")
    print(f"Sin traducir (mantienen espanol): {untranslated}")
    
    # Listar las primeras 50 claves sin traducir para revisión
    if untranslated > 0:
        print(f"\n🔍 Primeras 50 claves sin traducir:")
        count = 0
        for k in keys:
            es_val = es_data.get(k, '')
            if pt_data[k] == es_val and es_val:
                print(f"  {k}: {es_val[:80]}")
                count += 1
                if count >= 50:
                    break


if __name__ == '__main__':
    main()
